/**
 * Run modes for the coding agent.
 */

export type {
	CapabilityBindingView,
	CapabilityCatalogView,
	CapabilityDescriptorView,
} from "./interactive/capabilities.ts";
export { InteractiveMode, type InteractiveModeOptions } from "./interactive/interactive-mode.ts";
export type { JsonAgentSessionEvent } from "./json-event.ts";
export { type PrintModeOptions, runPrintMode } from "./print-mode.ts";
export {
	AutomationRpcError,
	McpAuthRpcError,
	McpContentRpcError,
	type ModelInfo,
	type RpcMcpAuthInteraction,
	type RpcMcpAuthInteractiveOptions,
	RpcClient,
	type RpcClientOptions,
	type RpcClientTcpOptions,
	type RpcClientTransportOptions,
	type RpcEventListener,
	type RpcRunEventListener,
	type RpcRunStreamEvent,
} from "./rpc/rpc-client.ts";
export {
	RPC_TRANSPORT_LOOPBACK_HOST,
	RPC_TRANSPORT_PORT_MAX,
	RPC_TRANSPORT_PORT_MIN,
	RpcTransportAddressError,
	formatRpcTransportAddress,
	parseRpcTransportAddress,
	validateRpcTransportAddress,
	type RpcTransportAddress,
	type RpcTransportAddressErrorCode,
	type RpcTransportAddressParseResult,
	type TcpRpcAddress,
} from "./rpc/rpc-transport-address.ts";
export {
	RpcTransport,
	RpcTransportError,
	createRpcTransport,
	createTcpRpcTransport,
	type RpcTransportConnection,
	type RpcTransportDispatcher,
	type RpcTransportErrorCode,
	type RpcTransportErrorRecord,
	type RpcTransportOptions,
	type RpcTransportSink,
} from "./rpc/rpc-transport.ts";
export { runRpcMode, type RpcModeOptions } from "./rpc/rpc-mode.ts";
export {
	createRpcHostController,
	RpcHostController,
	type RpcHostControllerOptions,
	type RpcOutputSink,
	type RpcWireRecord,
	type RpcHostOutputRecord,
	type RpcHostOutputSink,
} from "./rpc/rpc-host.ts";
export type {
	AuditEvent,
	AuditEventType,
	AuditQuery,
	AuditQueryData,
	AuditQueryResult,
	AuditReplayData,
	AuditReplayQuery,
	AuditReplayResult,
	AuditWarning,
	AutomationError,
	AutomationErrorCode,
	GetExecutionPolicyData,
	GetModelRoutesData,
	InitializeData,
	RpcAutomationCommandType,
	RpcAutomationResponse,
	RpcAuditCommandType,
	RpcAuditQueryCommand,
	RpcAuditReplayCommand,
	RpcCommand,
	RpcExtensionUIRequest,
	RpcExtensionUIResponse,
	RpcMcpAttachmentReceipt,
	RpcMcpAuthCommandType,
	RpcMcpAuthError,
	RpcMcpAuthErrorCode,
	RpcMcpAuthListData,
	RpcMcpAuthResponse,
	RpcMcpAuthStartData,
	RpcMcpAuthStartStatus,
	RpcMcpAuthStatusData,
	RpcMcpAuthStatusValue,
	RpcMcpContentBlockSummary,
	RpcMcpContentCommandType,
	RpcMcpContentError,
	RpcMcpContentErrorCode,
	RpcMcpContentResponse,
	RpcMcpGetPromptReceipt,
	RpcMcpMaskedCredential,
	RpcMcpReadResourceReceipt,
	RpcResponse,
	RpcRunCommandType,
	RpcSchedulerCommandType,
	RpcSchedulerResponse,
	RpcSessionState,
	RpcSessionInfo,
	RpcSessionSearchOptions,
	RpcTaskCredentialCommandType,
	RpcTaskGateCommandType,
	RpcTaskGraphCommandType,
	RunAcceptedData,
	RunCancelData,
	RunGetData,
	RunReceipt,
	RunRecord,
	RunRecoveryState,
	RunStatus,
	RunStreamEvent,
	RunTerminalStatus,
	SchedulerStatusData,
	TaskCredentialDeliveryReceipt,
	TaskCredentialGetData,
	TaskCredentialGrant,
	TaskCredentialHeartbeatData,
	TaskCredentialIssueData,
	TaskCredentialListData,
	TaskCredentialRevokeData,
	TaskCredentialScope,
	TaskCredentialSettleData,
	TaskCredentialStatus,
	TaskGateErrorCode,
	TaskGateGetData,
	TaskGateListData,
	TaskGateMutationData,
	TaskGateRecord,
	TaskGateStatus,
	TaskGraphErrorCode,
	TaskGraphGateRef,
	TaskGraphGetData,
	TaskGraphListData,
	TaskGraphMutationData,
	TaskGraphNodeAvailability,
	TaskGraphNodeDefinition,
	TaskGraphNodeStatus,
	TaskGraphNodeView,
	TaskGraphRecord,
	TaskGraphRunRef,
	TaskGraphStatus,
	TaskGraphSummary,
} from "./rpc/rpc-types.ts";
