// Core session management

export { type Args, parseArgs } from "./cli/args.ts";

// Config paths
export {
	CONFIG_DIR_NAME,
	getAgentDir,
	getDocsPath,
	getExamplesPath,
	getPackageDir,
	getReadmePath,
	VERSION,
} from "./config.ts";
export {
	AgentSession,
	type AgentSessionConfig,
	type AgentSessionEvent,
	type AgentSessionEventListener,
	type ModelCycleResult,
	type ParsedSkillBlock,
	type PromptOptions,
	parseSkillBlock,
	type SessionStats,
} from "./core/agent-session.ts";
export { readStoredCredential } from "./core/auth-storage.ts";
// Compaction
export {
	type BranchPreparation,
	type BranchSummaryResult,
	type CollectEntriesResult,
	type CompactionResult,
	type CutPointResult,
	calculateContextTokens,
	collectEntriesForBranchSummary,
	compact,
	DEFAULT_COMPACTION_SETTINGS,
	estimateTokens,
	type FileOperations,
	findCutPoint,
	findTurnStartIndex,
	type GenerateBranchSummaryOptions,
	generateBranchSummary,
	generateSummary,
	generateSummaryWithUsage,
	getLastAssistantUsage,
	prepareBranchEntries,
	serializeConversation,
	shouldCompact,
} from "./core/compaction/index.ts";
export { createEventBus, type EventBus, type EventBusController } from "./core/event-bus.ts";
// Extension system
export type {
	AgentEndEvent,
	AgentSettledEvent,
	AgentStartEvent,
	AgentToolResult,
	AgentToolUpdateCallback,
	AppKeybinding,
	AutocompleteProviderFactory,
	BashToolCallEvent,
	BeforeAgentStartEvent,
	BeforeAgentStartEventResult,
	BeforeProviderHeadersEvent,
	BeforeProviderRequestEvent,
	BeforeProviderRequestEventResult,
	BuildSystemPromptOptions,
	CompactOptions,
	ContextEvent,
	ContextUsage,
	CustomToolCallEvent,
	EditToolCallEvent,
	EntryRenderer,
	EntryRenderOptions,
	ExecOptions,
	ExecResult,
	Extension,
	ExtensionActions,
	ExtensionAPI,
	ExtensionCommandContext,
	ExtensionCommandContextActions,
	ExtensionContext,
	ExtensionContextActions,
	ExtensionError,
	ExtensionEvent,
	ExtensionFactory,
	ExtensionFlag,
	ExtensionHandler,
	ExtensionRuntime,
	ExtensionShortcut,
	ExtensionUIContext,
	ExtensionUIDialogOptions,
	ExtensionWidgetOptions,
	FindToolCallEvent,
	GrepToolCallEvent,
	InlineExtension,
	InputEvent,
	InputEventResult,
	InputSource,
	KeybindingsManager,
	LoadExtensionsResult,
	LsToolCallEvent,
	MarkdownTransformContext,
	MarkdownTransformer,
	MessageEndEvent,
	MessageRenderer,
	MessageRenderOptions,
	MessageStartEvent,
	MessageUpdateEvent,
	ProjectTrustContext,
	ProjectTrustEvent,
	ProjectTrustEventDecision,
	ProjectTrustEventResult,
	ProjectTrustHandler,
	ProviderConfig,
	ProviderModelConfig,
	ReadToolCallEvent,
	RegisteredCommand,
	RegisteredTool,
	ResolvedCommand,
	SessionBeforeCompactEvent,
	SessionBeforeForkEvent,
	SessionBeforeSwitchEvent,
	SessionBeforeTreeEvent,
	SessionCompactEvent,
	SessionInfoChangedEvent,
	SessionShutdownEvent,
	SessionStartEvent,
	SessionTreeEvent,
	SlashCommandInfo,
	SlashCommandSource,
	SourceInfo,
	TerminalInputHandler,
	ToolCallEvent,
	ToolCallEventResult,
	ToolDefinition,
	ToolExecutionEndEvent,
	ToolExecutionMode,
	ToolExecutionStartEvent,
	ToolExecutionUpdateEvent,
	ToolInfo,
	ToolRenderResultOptions,
	ToolResultEvent,
	TurnEndEvent,
	TurnStartEvent,
	UserBashEvent,
	UserBashEventResult,
	WidgetPlacement,
	WorkingIndicatorOptions,
	WriteToolCallEvent,
} from "./core/extensions/index.ts";
export {
	createExtensionRuntime,
	defineTool,
	discoverAndLoadExtensions,
	ExtensionRunner,
	isBashToolResult,
	isEditToolResult,
	isFindToolResult,
	isGrepToolResult,
	isLsToolResult,
	isReadToolResult,
	isToolCallEventType,
	isWriteToolResult,
	wrapRegisteredTool,
	wrapRegisteredTools,
} from "./core/extensions/index.ts";
// Footer data provider (git branch + extension statuses - data not otherwise available to extensions)
export type { ReadonlyFooterDataProvider } from "./core/footer-data-provider.ts";
export { convertToLlm } from "./core/messages.ts";
export {
	classifyFallbackEligibility,
	createModelError,
	createPublicModelSummary,
	type FallbackEligibility,
	isFallbackEligible,
	MODEL_BINDING_PREFIX,
	MODEL_BROKER_SCHEMA_VERSION,
	type ModelBinding,
	type ModelBindingBudgetSummary,
	ModelBroker,
	type ModelBrokerBudgetPreflightInput,
	ModelBrokerError,
	type ModelBrokerOptions,
	type ModelBudget,
	type ModelBudgetPreflight,
	type ModelBudgetPreflightInput,
	type ModelBudgetPreflightResult,
	type ModelBudgetSettlement,
	type ModelBudgetSettlementResult,
	type ModelError,
	type ModelErrorCode,
	type ModelFallbackPolicy,
	type ModelFallbackReason,
	type ModelReference,
	type ModelReferenceInput,
	type ModelResolution,
	type ModelResolutionResult,
	type ModelResolutionSource,
	type ModelRole,
	type ModelRoleCatalogInput,
	type ModelRoleSelection,
	type ModelRoute,
	type ModelRouteCandidate,
	type ModelRouteCatalogInput,
	type ModelRouteSelection,
	type ModelThinkingLevel,
	type ModelUsage,
	type NormalizedModelReference,
	type NormalizedModelUsage,
	normalizeModelReference,
	normalizeModelUsage,
	type ProviderFailure,
	type ProviderFailureCategory,
	type PublicModelRole,
	type PublicModelRoute,
	type PublicModelSummary,
	preflightBudget,
	resolveModel,
	settleBudget,
	toPublicModelBinding,
	toPublicModelReference,
	type VisibleSideEffect,
	type VisibleSideEffectsInput,
} from "./core/model-broker.ts";
export {
	foldModelAttemptEntries,
	foldModelBindingEntries,
	foldModelBrokerLedger,
	MODEL_ATTEMPT_CUSTOM_TYPE,
	MODEL_ATTEMPT_SCHEMA_VERSION,
	MODEL_BINDING_CUSTOM_TYPE,
	MODEL_BINDING_SCHEMA_VERSION,
	MODEL_BROKER_LEDGER_SCHEMA_VERSION,
	type ModelAttempt,
	type ModelAttemptLedgerRecord,
	type ModelAttemptStatus,
	type ModelBindingLedgerRecord,
	type ModelBindingMode,
	type ModelBrokerLedgerDiagnostic,
	type ModelBrokerLedgerEntry,
	ModelBrokerLedgerError,
	type ModelBrokerLedgerErrorCode,
	type ModelBrokerLedgerReplay,
	type ModelBrokerLedgerSession,
	type ModelFailureCategory as LedgerModelFailureCategory,
	type ModelReference as LedgerModelReference,
	type ModelUsage as LedgerModelUsage,
	type PublicModelAttemptLedgerRecord,
	type PublicModelBindingLedgerRecord,
	type PublicModelReference,
	type PublicModelRouteCandidate,
	persistModelAttempt,
	persistModelBinding,
	readModelBrokerLedger,
	replayModelBrokerLedger,
	serializePublicModelAttempt,
	serializePublicModelBinding,
	serializePublicModelBrokerLedgerEntry,
} from "./core/model-broker-ledger.ts";
export {
	EXECUTION_POLICY_SCHEMA_VERSION,
	LEGACY_PROFILE,
	POLICY_APPROVE_COMMAND,
	POLICY_APPROVAL_OUTCOMES,
	POLICY_APPROVAL_SOURCES,
	POLICY_DEFAULT_PROFILE,
	POLICY_QUERY_COMMAND,
	POLICY_REJECT_COMMAND,
	PolicyError,
	authorizePolicyOperation,
	createPolicyApprovalRequest,
	createPolicySummary,
	freezePolicyBinding,
	freezePolicyProfile,
	resolveExecutionPolicy,
	resolveExecutionPolicyProfile,
	resolvePolicy,
	toPolicyDecisionSummary,
	toPolicyErrorView,
	toPublicPolicySummary,
	type ApprovalPolicy,
	type CredentialPolicy,
	type ExecutionPolicyProfile,
	type NetworkPolicy,
	type PolicyAction,
	type PolicyApprovalOutcome,
	type PolicyApprovalRequest,
	type PolicyApprovalSource,
	type PolicyBinding,
	type PolicyDecision,
	type PolicyDecisionSummary,
	type PolicyDecisionOutcome,
	type PolicyEnforcement,
	type PolicyErrorCode,
	type PolicyErrorView,
	type PolicyOperationRequest,
	type PolicyOperationSource,
	type PolicyResource,
	type PolicyResolution,
	type PolicyResolutionResult,
	type PolicySummary,
	type ProcessPolicy,
	type PublicPolicySummary,
	type SandboxCapabilities,
	type SandboxStatus,
	type WorkspacePolicy,
	type WorkspaceScope,
} from "./core/execution-policy.ts";
export type { PolicyApprovalLedgerRecord, PolicyApprovalLedgerResolution } from "./core/execution-policy-ledger.ts";
export {
	SandboxCapabilityError,
	SandboxError,
	SandboxHandleDisposedError,
	type SandboxDirectoryEntry,
	type SandboxHandle,
	type SandboxLifecycleStatus,
	type SandboxMCPTransportRequest,
	type SandboxOperationRequest,
	type SandboxOperationResult,
	type SandboxProvider,
} from "./core/sandbox.ts";
export {
	buildExecutionPolicySettings,
	createExecutionPolicySettingsView,
	getExecutionPolicyProfile,
	parseExecutionPolicySettings,
	resolveExecutionPolicySettings,
	validateExecutionPolicySettingsConfig,
	type ExecutionPolicySettings,
	type ExecutionPolicySettingsBuildOptions,
	type ExecutionPolicySettingsConfig,
	ExecutionPolicySettingsError,
} from "./core/execution-policy-settings.ts";
export {
	buildModelBrokerSettings,
	createEmptyModelBrokerSettings,
	createModelBrokerSettingsView,
	MODEL_BROKER_SETTINGS_VERSION,
	type ModelBrokerBudgetConfig,
	type ModelBrokerBudgetSettings,
	type ModelBrokerCandidateConfig,
	type ModelBrokerCostMetadata,
	type ModelBrokerCostTier,
	type ModelBrokerDiagnosticCode,
	type ModelBrokerFallbackConfig,
	type ModelBrokerFallbackReason,
	type ModelBrokerFallbackSettings,
	type ModelBrokerModelDescriptor,
	type ModelBrokerRoute,
	type ModelBrokerRouteCandidate,
	type ModelBrokerRouteConfig,
	type ModelBrokerSettings,
	type ModelBrokerSettingsBuildOptions,
	type ModelBrokerSettingsConfig,
	type ModelBrokerSettingsDiagnostic,
	ModelBrokerSettingsError,
	type ModelBrokerSettingsErrorCode,
	type ModelBrokerSettingsInput,
	type ModelBrokerSettingsScope,
	type ModelReference as ModelBrokerModelReference,
	parseModelBrokerSettings,
	resolveModelBrokerSettings,
	validateModelBrokerSettings,
} from "./core/model-broker-settings.ts";
export { ModelRegistry } from "./core/model-registry.ts";
export {
	type ModelScopeDiagnostic,
	type ResolveCliModelResult,
	type ResolveModelScopeResult,
	resolveCliModel,
	resolveModelScopeWithDiagnostics,
	type ScopedModel,
} from "./core/model-resolver.ts";
export {
	type CreateModelRuntimeOptions,
	CredentialSynchronizationError,
	type CredentialSynchronizationOperation,
	createModelBroker,
	ModelRuntime,
	type ModelRuntimeAuthOverrides,
} from "./core/model-runtime.ts";
export type {
	PackageManager,
	PathMetadata,
	ProgressCallback,
	ProgressEvent,
	ResolvedPaths,
	ResolvedResource,
} from "./core/package-manager.ts";
export { DefaultPackageManager } from "./core/package-manager.ts";
export type { ResourceCollision, ResourceDiagnostic, ResourceLoader } from "./core/resource-loader.ts";
export { DefaultResourceLoader, loadProjectContextFiles } from "./core/resource-loader.ts";
// SDK for programmatic usage
export {
	AgentSessionRuntime,
	type AgentSessionRuntimeDiagnostic,
	type AgentSessionServices,
	type CreateAgentSessionFromServicesOptions,
	type CreateAgentSessionOptions,
	type CreateAgentSessionResult,
	type CreateAgentSessionRuntimeFactory,
	type CreateAgentSessionRuntimeResult,
	type CreateAgentSessionServicesOptions,
	// Factory
	createAgentSession,
	createAgentSessionFromServices,
	createAgentSessionRuntime,
	createAgentSessionServices,
	createBashTool,
	// Tool factories (for custom cwd)
	createCodingTools,
	createEditTool,
	createFindTool,
	createGrepTool,
	createLsTool,
	createReadOnlyTools,
	createReadTool,
	createWriteTool,
	type PromptTemplate,
} from "./core/sdk.ts";
export {
	type BranchSummaryEntry,
	buildContextEntries,
	buildSessionContext,
	type CompactionEntry,
	CURRENT_SESSION_VERSION,
	type CustomEntry,
	type CustomMessageEntry,
	type FileEntry,
	getLatestCompactionEntry,
	type ModelChangeEntry,
	migrateSessionEntries,
	type NewSessionOptions,
	parseSessionEntries,
	type SessionContext,
	type SessionEntry,
	type SessionEntryBase,
	type SessionHeader,
	type SessionInfo,
	type SessionInfoEntry,
	SessionManager,
	type SessionMessageEntry,
	type SessionTreeNode,
	sessionEntryToContextMessages,
	type ThinkingLevelChangeEntry,
} from "./core/session-manager.ts";
export {
	type CompactionSettings,
	type DefaultProjectTrust,
	type FullscreenExitOutput,
	type ImageSettings,
	type PackageSource,
	type RetrySettings,
	SettingsManager,
	type SettingsManagerCreateOptions,
	type TuiMode,
} from "./core/settings-manager.ts";
// Skills
export {
	formatSkillsForPrompt,
	type LoadSkillsFromDirOptions,
	type LoadSkillsResult,
	loadSkills,
	loadSkillsFromDir,
	type Skill,
	type SkillFrontmatter,
} from "./core/skills.ts";
export { createSyntheticSourceInfo } from "./core/source-info.ts";
export { type EditDiffResult, generateDiffString, generateUnifiedPatch } from "./core/tools/edit-diff.ts";
// Tools
export {
	type BashOperations,
	type BashSpawnContext,
	type BashSpawnHook,
	type BashToolDetails,
	type BashToolInput,
	type BashToolOptions,
	createBashToolDefinition,
	createEditToolDefinition,
	createFindToolDefinition,
	createGrepToolDefinition,
	createLocalBashOperations,
	createLsToolDefinition,
	createReadToolDefinition,
	createWriteToolDefinition,
	DEFAULT_MAX_BYTES,
	DEFAULT_MAX_LINES,
	type EditOperations,
	type EditToolDetails,
	type EditToolInput,
	type EditToolOptions,
	type FindOperations,
	type FindToolDetails,
	type FindToolInput,
	type FindToolOptions,
	formatSize,
	type GrepOperations,
	type GrepToolDetails,
	type GrepToolInput,
	type GrepToolOptions,
	type LsOperations,
	type LsToolDetails,
	type LsToolInput,
	type LsToolOptions,
	type ReadOperations,
	type ReadToolDetails,
	type ReadToolInput,
	type ReadToolOptions,
	type ToolsOptions,
	type TruncationOptions,
	type TruncationResult,
	truncateHead,
	truncateLine,
	truncateTail,
	type WriteOperations,
	type WriteToolInput,
	type WriteToolOptions,
	withFileMutationQueue,
} from "./core/tools/index.ts";
export {
	hasTrustRequiringProjectResources,
	type ProjectTrustDecision,
	ProjectTrustStore,
	type ProjectTrustStoreEntry,
	type ProjectTrustUpdate,
} from "./core/trust-manager.ts";
// Main entry point
export { type MainOptions, main } from "./main.ts";
export type {
	AuditEvent,
	AuditEventType,
	AuditQuery,
	AuditQueryData,
	AuditQueryResult,
	AuditReplayData,
	AuditReplayQuery,
	AuditReplayResult,
	AuditWarning,
	AutomationError,
	AutomationErrorCode,
	CapabilityBindingView,
	CapabilityCatalogView,
	CapabilityDescriptorView,
	ExternalExecutionMapping,
	ExternalExecutionRef,
	ExternalMapData,
	ExternalMappingPersistenceResult,
	ExternalMappingRequest,
	GetExecutionPolicyData,
	GetModelRoutesData,
	InitializeData,
	RpcAutomationCommandType,
	RpcAutomationResponse,
	RpcAuditCommandType,
	RpcAuditQueryCommand,
	RpcAuditReplayCommand,
	RpcRunCommandType,
	RunAcceptedData,
	RunCancelData,
	RunGetData,
	RunReceipt,
	RunRecord,
	RunRecoveryState,
	RunStatus,
	RunStreamEvent,
	RunTerminalStatus,
} from "./modes/index.ts";
// Run modes for programmatic SDK usage
export {
	AutomationRpcError,
	InteractiveMode,
	type InteractiveModeOptions,
	type JsonAgentSessionEvent,
	type ModelInfo,
	type PrintModeOptions,
	RpcClient,
	type RpcClientOptions,
	type RpcCommand,
	type RpcEventListener,
	type RpcExtensionUIRequest,
	type RpcExtensionUIResponse,
	type RpcResponse,
	type RpcRunEventListener,
	type RpcRunStreamEvent,
	type RpcSessionState,
	runPrintMode,
	runRpcMode,
} from "./modes/index.ts";
// UI components for extensions
export {
	ArminComponent,
	AssistantMessageComponent,
	BashExecutionComponent,
	BorderedLoader,
	BranchSummaryMessageComponent,
	CompactionSummaryMessageComponent,
	CustomEditor,
	CustomMessageComponent,
	DynamicBorder,
	ExtensionEditorComponent,
	ExtensionInputComponent,
	ExtensionSelectorComponent,
	FooterComponent,
	keyHint,
	keyText,
	LoginDialogComponent,
	ModelSelectorComponent,
	OAuthSelectorComponent,
	type RenderDiffOptions,
	rawKeyHint,
	renderDiff,
	SessionSelectorComponent,
	type SettingsCallbacks,
	type SettingsConfig,
	SettingsSelectorComponent,
	ShowImagesSelectorComponent,
	SkillInvocationMessageComponent,
	ThemeSelectorComponent,
	ThinkingSelectorComponent,
	ToolExecutionComponent,
	type ToolExecutionOptions,
	TreeSelectorComponent,
	truncateToVisualLines,
	UserMessageComponent,
	UserMessageSelectorComponent,
	type VisualTruncateResult,
} from "./modes/interactive/components/index.ts";
// Theme utilities for custom tools and extensions
export {
	getLanguageFromPath,
	getMarkdownTheme,
	getSelectListTheme,
	getSettingsListTheme,
	highlightCode,
	initTheme,
	Theme,
	type ThemeColor,
} from "./modes/interactive/theme/theme.ts";
// Clipboard utilities
export { copyToClipboard } from "./utils/clipboard.ts";
export { parseFrontmatter, stripFrontmatter } from "./utils/frontmatter.ts";
export { convertToPng } from "./utils/image-convert.ts";
export { formatDimensionNote, type ResizedImage, resizeImage } from "./utils/image-resize.ts";
// Shell utilities
export { getShellConfig } from "./utils/shell.ts";
