// Core session management

export { type Args, parseArgs } from "./cli/args.ts";
export {
	PROMPT_TASK_DEPENDENCY_NAMES,
	PromptTaskCompositionError,
	createPromptTaskAdapter,
	type PromptTaskAdapter,
	type PromptTaskCompositionDependencies,
	type PromptTaskCompositionErrorCode,
	type PromptTaskCompositionRootOptions,
	type PromptTaskDependencyContext,
	type PromptTaskDependencyName,
	type PromptTaskDependencyResolution,
	type PromptTaskDependency,
	type PromptTaskEnvelopeInput,
	type PromptTaskExecution,
	type PromptTaskIdentity,
	type PromptTaskInput,
	type PromptTaskSettlement,
} from "./core/prompt-task-adapter.ts";

// Config paths
export {
	CONFIG_DIR_NAME,
	getAgentDir,
	getDocsPath,
	getExamplesPath,
	getPackageDir,
	getReadmePath,
	VERSION,
} from "./config.ts";
export {
	AgentSession,
	type AgentSessionEvent,
	type AgentSessionEventListener,
	type ModelCycleResult,
	type ParsedSkillBlock,
	type PromptOptions,
	parseSkillBlock,
	type SessionStats,
} from "./core/agent-session.ts";
export {
	TrustedSchedulerComposition,
	type SchedulerSafeStatus,
	type TrustedSchedulerCompositionOptions,
} from "./core/foundation-control-plane.ts";
export { SchedulerHost, type SchedulerHostOptions, type SchedulerHostTickResult } from "./core/scheduler.ts";
export { SchedulerQueueStore } from "./core/scheduler-queue.ts";
export { SchedulerExecutorRegistry, SchedulerInProcessTaskExecutorProvider } from "./core/scheduler-executors.ts";
export { SchedulerDispatchController } from "./core/scheduler-dispatch.ts";
export { SchedulerFanInController } from "./core/scheduler-fan-in.ts";
export { SchedulerMessageOrchestrator } from "./core/scheduler-messages.ts";
export { SchedulerHandoffController } from "./core/scheduler-handoff.ts";
export { SchedulerWorkflowController, type SchedulerWorkflowTickResult } from "./core/scheduler-workflow.ts";
export { SchedulerDeadlockController, type SchedulerDeadlockTickResult } from "./core/scheduler-deadlock.ts";
// Task Credential lifecycle service (session-owned; RPC Host registers it via AgentSession.getTaskCredentialService())
export {
	TaskCredentialService,
	type TaskCredentialGateInvalidationInput,
	type TaskCredentialGraphNodeTerminalInput,
	type TaskCredentialLifecycleReasonCode,
	type TaskCredentialPreflightFactsInput,
	type TaskCredentialPreflightResolver,
	type TaskCredentialRenewInput,
	type TaskCredentialRunIssueContext,
	type TaskCredentialRunTerminalInput,
	type TaskCredentialServiceIssueResult,
	type TaskCredentialServiceMutationResult,
	type TaskCredentialServiceOptions,
	type TaskCredentialServiceRenewResult,
	type TaskCredentialServiceRevokeInput,
	type TaskCredentialServiceSettleInput,
	type TaskCredentialSignalOutcome,
	type TaskCredentialWorkerDetachInput,
} from "./core/task-credential-service.ts";
// Task Credential / Lease public contract (safe records only; the
// material-bearing test provider, target projection request, and provider
// handles stay module-private and are never exported).
export {
	TASK_CREDENTIAL_ACTION,
	TASK_CREDENTIAL_DELIVERY_STATUS,
	TASK_CREDENTIAL_ERROR_CODES,
	TASK_CREDENTIAL_SCHEMA_VERSION,
	TASK_CREDENTIAL_STATUS,
	TaskCredentialError,
	type TaskCredentialAction,
	type TaskCredentialDeliveryReceipt,
	type TaskCredentialDeliveryStatus,
	type TaskCredentialErrorCode,
	type TaskCredentialErrorView,
	type TaskCredentialGrant,
	type TaskCredentialIssueRequest,
	type TaskCredentialScope,
	type TaskCredentialStatus,
	type TaskCredentialTransitionOptions,
	type TaskCredentialTtlBounds,
	type TaskExecutionBinding,
} from "./core/task-credential-lease.ts";
export {
	createTaskCredentialNullTarget,
	type TaskCredentialIssuer,
	type TaskCredentialProvider,
	type TaskCredentialProviderAvailability,
	type TaskCredentialProviderIssueRequest,
	type TaskCredentialProviderProjectRequest,
	type TaskCredentialProviderReceipt,
	type TaskCredentialProviderReceiptStatus,
	type TaskCredentialProviderRenewRequest,
	type TaskCredentialProviderRevokeRequest,
	type TaskCredentialTarget,
	type TaskCredentialTargetCapabilities,
	type TaskCredentialTargetCapabilitiesRequest,
	type TaskCredentialTargetRenewRequest,
	type TaskCredentialTargetRevokeRequest,
} from "./core/task-credential-provider.ts";
export {
	TASK_CREDENTIAL_CUSTOM_TYPE,
	type TaskCredentialSession,
	type TaskCredentialWarning,
	type TaskCredentialWarningCode,
} from "./core/task-credential-store.ts";
export { readStoredCredential } from "./core/auth-storage.ts";
export {
	canonicalizeMCPServerUrl,
	deriveMCPServerIdentity,
	getMCPAuthInstallationId,
	isMCPCredential,
	isScopeSubset,
	listMCPCredentialStatuses,
	MCPAuthStorage,
	MCPAuthStorageError,
	mcpCredentialKey,
	type MCPAuthStorageOptions,
	type MCPCredentialStatus,
	type MCPStoredTokens,
	type MCPTokenBinding,
	type MCPTokenResponse,
} from "./core/mcp-auth-storage.ts";
// Compaction
export {
	type BranchPreparation,
	type BranchSummaryResult,
	type CollectEntriesResult,
	type CompactionResult,
	type CutPointResult,
	calculateContextTokens,
	collectEntriesForBranchSummary,
	compact,
	DEFAULT_COMPACTION_SETTINGS,
	estimateTokens,
	type FileOperations,
	findCutPoint,
	findTurnStartIndex,
	type GenerateBranchSummaryOptions,
	generateBranchSummary,
	generateSummary,
	generateSummaryWithUsage,
	getLastAssistantUsage,
	prepareBranchEntries,
	serializeConversation,
	shouldCompact,
} from "./core/compaction/index.ts";
export { createEventBus, type EventBus, type EventBusController } from "./core/event-bus.ts";
export {
	BINDING_ASSOCIATION_ID_PREFIX,
	BINDING_ASSOCIATION_SCHEMA_VERSION,
	BINDING_HANDLE_ID_PREFIX,
	BINDING_HANDLE_SCHEMA_VERSION,
	associateBindingHandles,
	BindingHandleError,
	createBindingAssociation,
	createBindingHandle,
	createBindingRevision,
	createRunBindingAssociation,
	createStableBindingId,
	deriveBindingHandleId,
	isBindingAssociation,
	isBindingHandle,
	isRunBindingAssociation,
	parseBindingAssociation,
	parseBindingHandle,
	parseRunBindingAssociation,
	projectAgentBindingHandles,
	projectRunBindingAssociation,
	serializePublicBindingAssociation,
	serializePublicBindingHandle,
	serializePublicBindingReference,
	serializePublicRunBindingAssociation,
	toPublicBindingReference,
	type BindingAssociation,
	type BindingDomain,
	type BindingHandle,
	type BindingHandleErrorCode,
	type BindingHandleInput,
	type PublicBindingReference,
	type PublicBindingSummary,
	type PublicBindingSummaryValue,
	type RunBindingAssociation,
} from "./core/binding-handles.ts";
export {
	createCapabilityBindingHandle,
	createCapabilityBindingView,
	getCapabilityBindingRevision,
	isCapabilityBindingHandle,
	serializePublicCapabilityBindingHandle,
	toPublicCapabilityBindingHandle,
	toCapabilityBindingHandle,
	type CapabilityBinding,
} from "./core/capability-registry.ts";
export {
	EXECUTION_ASSOCIATION_CUSTOM_TYPE,
	EXECUTION_ASSOCIATION_SCHEMA_VERSION,
	type ExecutionAssociationRecord,
	type ExecutionAssociationSession,
	getExecutionAssociations,
	isExecutionAssociationRecord,
	parseExecutionAssociation,
} from "./core/execution-association.ts";
export {
	classifyAssistantFailure,
	classifyProviderFailure,
	type ExecutionErrorClassification,
	type ExecutionErrorKind,
	type ProviderFailureClassificationOptions,
} from "./core/execution-error.ts";
export {
	type ApprovalPolicy,
	authorizePolicyOperation,
	type CredentialPolicy,
	createPolicyApprovalRequest,
	createPolicyBindingHandle,
	createPolicySummary,
	EXECUTION_POLICY_SCHEMA_VERSION,
	type ExecutionPolicyProfile,
	freezePolicyBinding,
	freezePolicyProfile,
	getPolicyBindingRevision,
	isPolicyBindingHandle,
	isTaskCredentialPolicyResource,
	LEGACY_PROFILE,
	type NetworkPolicy,
	POLICY_APPROVAL_OUTCOMES,
	POLICY_APPROVAL_SOURCES,
	POLICY_APPROVE_COMMAND,
	POLICY_DEFAULT_PROFILE,
	POLICY_QUERY_COMMAND,
	POLICY_REJECT_COMMAND,
	type PolicyAction,
	type PolicyApprovalOutcome,
	type PolicyApprovalRequest,
	type PolicyApprovalSource,
	type PolicyBinding,
	type PolicyDecision,
	type PolicyDecisionOutcome,
	type PolicyDecisionSummary,
	type PolicyEnforcement,
	PolicyError,
	type PolicyErrorCode,
	type PolicyErrorView,
	type PolicyOperationRequest,
	type PolicyOperationSource,
	type PolicyResolution,
	type PolicyResolutionResult,
	type PolicyResource,
	type PolicySummary,
	type ProcessPolicy,
	type PublicPolicySummary,
	resolveExecutionPolicy,
	resolveExecutionPolicyProfile,
	resolvePolicy,
	resolveTaskCredentialPreflight,
	serializePublicPolicyBindingHandle,
	type SandboxCapabilities,
	type SandboxStatus,
	TASK_CREDENTIAL_POLICY_RESOURCES,
	TASK_CREDENTIAL_PREFLIGHT_OPERATIONS,
	type TaskCredentialGatePreflight,
	type TaskCredentialPolicyResource,
	type TaskCredentialPreflightInput,
	type TaskCredentialPreflightOperation,
	type TaskCredentialPreflightResult,
	type TaskCredentialProviderPreflight,
	type TaskCredentialSandboxPreflight,
	taskCredentialPolicyResource,
	toPolicyDecisionSummary,
	toPolicyErrorView,
	toPublicPolicyBindingHandle,
	toPublicPolicySummary,
	toPolicyBindingHandle,
	type WorkspacePolicy,
	type WorkspaceScope,
} from "./core/execution-policy.ts";
export type { PolicyApprovalLedgerRecord, PolicyApprovalLedgerResolution } from "./core/execution-policy-ledger.ts";
export {
	buildExecutionPolicySettings,
	createExecutionPolicySettingsView,
	type ExecutionPolicySettings,
	type ExecutionPolicySettingsBuildOptions,
	type ExecutionPolicySettingsConfig,
	ExecutionPolicySettingsError,
	getExecutionPolicyProfile,
	parseExecutionPolicySettings,
	resolveExecutionPolicySettings,
	validateExecutionPolicySettingsConfig,
} from "./core/execution-policy-settings.ts";
// Extension system
export type {
	AgentEndEvent,
	AgentSettledEvent,
	AgentStartEvent,
	AgentToolResult,
	AgentToolUpdateCallback,
	AppKeybinding,
	AutocompleteProviderFactory,
	BashToolCallEvent,
	BeforeAgentStartEvent,
	BeforeAgentStartEventResult,
	BeforeProviderHeadersEvent,
	BeforeProviderRequestEvent,
	BeforeProviderRequestEventResult,
	BuildSystemPromptOptions,
	CompactOptions,
	ContextEvent,
	ContextUsage,
	CustomToolCallEvent,
	EditToolCallEvent,
	EntryRenderer,
	EntryRenderOptions,
	ExecOptions,
	ExecResult,
	Extension,
	ExtensionActions,
	ExtensionAPI,
	ExtensionCommandContext,
	ExtensionCommandContextActions,
	ExtensionContext,
	ExtensionContextActions,
	ExtensionError,
	ExtensionEvent,
	ExtensionFactory,
	ExtensionFlag,
	ExtensionHandler,
	ExtensionRuntime,
	ExtensionShortcut,
	ExtensionUIContext,
	ExtensionUIDialogOptions,
	ExtensionWidgetOptions,
	FindToolCallEvent,
	GrepToolCallEvent,
	InlineExtension,
	InputEvent,
	InputEventResult,
	InputSource,
	KeybindingsManager,
	LoadExtensionsResult,
	LsToolCallEvent,
	MarkdownTransformContext,
	MarkdownTransformer,
	MessageEndEvent,
	MessageRenderer,
	MessageRenderOptions,
	MessageStartEvent,
	MessageUpdateEvent,
	ProjectTrustContext,
	ProjectTrustEvent,
	ProjectTrustEventDecision,
	ProjectTrustEventResult,
	ProjectTrustHandler,
	ProviderConfig,
	ProviderModelConfig,
	ReadToolCallEvent,
	RegisteredCommand,
	RegisteredTool,
	ResolvedCommand,
	SessionBeforeCompactEvent,
	SessionBeforeForkEvent,
	SessionBeforeSwitchEvent,
	SessionBeforeTreeEvent,
	SessionCompactEvent,
	SessionInfoChangedEvent,
	SessionShutdownEvent,
	SessionStartEvent,
	SessionTreeEvent,
	SlashCommandInfo,
	SlashCommandSource,
	SourceInfo,
	TerminalInputHandler,
	ToolCallEvent,
	ToolCallEventResult,
	ToolDefinition,
	ToolExecutionEndEvent,
	ToolExecutionMode,
	ToolExecutionStartEvent,
	ToolExecutionUpdateEvent,
	ToolInfo,
	ToolRenderResultOptions,
	ToolResultEvent,
	TurnEndEvent,
	TurnStartEvent,
	UserBashEvent,
	UserBashEventResult,
	WidgetPlacement,
	WorkingIndicatorOptions,
	WriteToolCallEvent,
} from "./core/extensions/index.ts";
export {
	createExtensionRuntime,
	defineTool,
	discoverAndLoadExtensions,
	ExtensionRunner,
	isBashToolResult,
	isEditToolResult,
	isFindToolResult,
	isGrepToolResult,
	isLsToolResult,
	isReadToolResult,
	isToolCallEventType,
	isWriteToolResult,
	wrapRegisteredTool,
	wrapRegisteredTools,
} from "./core/extensions/index.ts";
// Footer data provider (git branch + extension statuses - data not otherwise available to extensions)
export type { ReadonlyFooterDataProvider } from "./core/footer-data-provider.ts";
export { convertToLlm } from "./core/messages.ts";
export {
	classifyFallbackEligibility,
	createModelError,
	createPublicModelSummary,
	type FallbackEligibility,
	isFallbackEligible,
	MODEL_BINDING_PREFIX,
	MODEL_BROKER_SCHEMA_VERSION,
	type ModelBinding,
	type ModelBindingBudgetSummary,
	ModelBroker,
	createModelBindingHandle,
	getModelBindingRevision,
	isModelBindingHandle,
	serializePublicModelBindingHandle,
	toPublicModelBindingHandle,
	type ModelBrokerBudgetPreflightInput,
	ModelBrokerError,
	type ModelBrokerOptions,
	type ModelBudget,
	type ModelBudgetPreflight,
	type ModelBudgetPreflightInput,
	type ModelBudgetPreflightResult,
	type ModelBudgetSettlement,
	type ModelBudgetSettlementResult,
	type ModelError,
	type ModelErrorCode,
	type ModelFallbackPolicy,
	type ModelFallbackReason,
	type ModelReference,
	type ModelReferenceInput,
	type ModelResolution,
	type ModelResolutionResult,
	type ModelResolutionSource,
	type ModelRole,
	type ModelRoleCatalogInput,
	type ModelRoleSelection,
	type ModelRoute,
	type ModelRouteCandidate,
	type ModelRouteCatalogInput,
	type ModelRouteSelection,
	type ModelThinkingLevel,
	type ModelUsage,
	type NormalizedModelReference,
	type NormalizedModelUsage,
	normalizeModelReference,
	normalizeModelUsage,
	type ProviderFailure,
	type ProviderFailureCategory,
	type PublicModelRole,
	type PublicModelRoute,
	type PublicModelSummary,
	preflightBudget,
	resolveModel,
	settleBudget,
	toPublicModelBinding,
	toPublicModelReference,
	type VisibleSideEffect,
	type VisibleSideEffectsInput,
} from "./core/model-broker.ts";
export {
	foldModelAttemptEntries,
	foldModelBindingEntries,
	foldModelBrokerLedger,
	MODEL_ATTEMPT_CUSTOM_TYPE,
	MODEL_ATTEMPT_SCHEMA_VERSION,
	MODEL_BINDING_CUSTOM_TYPE,
	MODEL_BINDING_SCHEMA_VERSION,
	MODEL_BROKER_LEDGER_SCHEMA_VERSION,
	type ModelAttempt,
	type ModelAttemptLedgerRecord,
	type ModelAttemptStatus,
	type ModelBindingLedgerRecord,
	type ModelBindingMode,
	type ModelBrokerLedgerDiagnostic,
	type ModelBrokerLedgerEntry,
	ModelBrokerLedgerError,
	type ModelBrokerLedgerErrorCode,
	type ModelBrokerLedgerReplay,
	type ModelBrokerLedgerSession,
	createModelLedgerBindingHandle,
	isModelLedgerBindingHandle,
	type ModelFailureCategory as LedgerModelFailureCategory,
	type ModelReference as LedgerModelReference,
	type ModelUsage as LedgerModelUsage,
	type PublicModelAttemptLedgerRecord,
	type PublicModelBindingLedgerRecord,
	type PublicModelReference,
	type PublicModelRouteCandidate,
	persistModelAttempt,
	persistModelBinding,
	readModelBrokerLedger,
	replayModelBrokerLedger,
	serializePublicModelAttempt,
	serializePublicModelBinding,
	serializePublicModelBrokerLedgerEntry,
	toModelLedgerBindingHandle,
} from "./core/model-broker-ledger.ts";
export {
	SandboxCapabilityError,
	SandboxCredentialChannel,
	SandboxError,
	SandboxHandleDisposedError,
	createSandboxBindingHandle,
	isSandboxBindingHandle,
	preflightTaskCredentialDelivery,
	serializePublicSandboxBindingHandle,
	toSandboxBindingHandle,
	toPublicSandboxBindingHandle,
	type SandboxCredentialChannelOptions,
	type SandboxCredentialDeliveryOutcome,
	type SandboxCredentialDeliveryRequest,
	type SandboxCredentialDeliveryResult,
	type SandboxCredentialPreflightResult,
	type SandboxCredentialRenewRequest,
	type SandboxCredentialRevokeRequest,
	type SandboxCredentialRevokeResult,
	type SandboxDirectoryEntry,
	type SandboxBindingHandleOptions,
	type SandboxHandle,
	type SandboxLifecycleStatus,
	type SandboxMCPTransportRequest,
	type SandboxOperationRequest,
	type SandboxOperationResult,
	type SandboxProvider,
	type TaskCredentialDeliveryPreflightResult,
} from "./core/sandbox.ts";
export {
	REMOTE_ARTIFACT_KINDS,
	REMOTE_OPERATION_ERROR_CATEGORIES,
	REMOTE_OPERATION_CUSTOM_TYPE,
	REMOTE_OPERATION_LEDGER_SCHEMA_VERSION,
	REMOTE_OPERATION_SCHEMA_VERSION,
	REMOTE_OPERATION_SIDE_EFFECT_STATES,
	REMOTE_OPERATION_STATUSES,
	RemoteOperationError,
	createSessionRemoteOperationLedger,
	executeRemoteOperation,
	isRemoteOperationReceipt,
	isTaskLeaseReference,
	startRemoteOperation,
	toRemoteOperationErrorInfo,
	type ArtifactReference,
	type OperationId,
	type RemoteArtifactKind,
	type RemoteArtifactRef,
	type RemoteArtifactReference,
	type RemoteOperationBindingRefs,
	type RemoteOperationErrorCategory,
	type RemoteOperationErrorCode,
	type RemoteOperationErrorInfo,
	type RemoteOperationExecutionContext,
	type RemoteOperationHandle,
	type RemoteOperationHeartbeat,
	type RemoteOperationId,
	type RemoteOperationInvoker,
	type RemoteOperationLease,
	type RemoteOperationLeaseId,
	type RemoteOperationLedger,
	type RemoteOperationLedgerSession,
	type RemoteOperationProvider,
	type RemoteOperationReceipt,
	type RemoteOperationRequest,
	type RemoteOperationResult,
	type RemoteOperationRunStatus,
	type RemoteOperationSideEffectState,
	type RemoteOperationStartOptions,
	type RemoteOperationStatus,
	type RemoteOperationTerminalStatus,
	type RemoteOperationTransport,
	type RemoteOperationTaskLeaseVerifier,
	type TaskLeaseReference,
	type TaskLeaseVerificationResult,
} from "./core/remote-operation.ts";
// The single current External Connector contract and trusted registry.
export type { ExternalAgentConnector } from "@aos-agent/agent-core";
export {
	EXTERNAL_CONNECTOR_PROVIDER_CLASSES,
	createExternalConnectorRegistry,
	isExternalConnectorSelection,
	serializeExternalConnectorSelection,
	type ExternalConnectorDescriptor,
	type ExternalConnectorProviderClass,
	type ExternalConnectorRegistration,
	type ExternalConnectorRegistry,
	type ExternalConnectorResolvedSelection,
	type ExternalConnectorSelection,
} from "./core/external-agent-registry.ts";
export {
	executeExternalConnectorProductRun,
	externalConnectorProductIdentity,
	type ExternalConnectorProductExecution,
	type ExternalConnectorProductExecutionInput,
} from "./core/external-connector-product.ts";
export {
	CANONICAL_EXTERNAL_AGENT_INPUT_HARD_LIMITS,
	CANONICAL_EXTERNAL_AGENT_INPUT_SCHEMA_VERSION,
	ExternalAgentInputError,
	fingerprintCanonicalExternalAgentInput,
	gateCanonicalExternalAgentInputBeforeAcceptance,
	validateCanonicalExternalAgentInput,
	type CanonicalExternalAgentArtifactReadHandle,
	type CanonicalExternalAgentArtifactReference,
	type CanonicalExternalAgentInput,
	type ExternalAgentArtifactInspection,
	type ExternalAgentInputAdmissionOptions,
} from "./core/external-agent-input.ts";
export {
	projectExternalModelForExecution,
	type ExternalModelFallbackDecision,
	type ExternalModelProjectionGateInput,
	type ExternalModelProjectionGateResult,
	type ExternalResolvedModelProjection,
} from "./core/external-model-projection.ts";
export {
	buildModelBrokerSettings,
	createEmptyModelBrokerSettings,
	createModelBrokerSettingsView,
	MODEL_BROKER_SETTINGS_VERSION,
	type ModelBrokerBudgetConfig,
	type ModelBrokerBudgetSettings,
	type ModelBrokerCandidateConfig,
	type ModelBrokerCostMetadata,
	type ModelBrokerCostTier,
	type ModelBrokerDiagnosticCode,
	type ModelBrokerFallbackConfig,
	type ModelBrokerFallbackReason,
	type ModelBrokerFallbackSettings,
	type ModelBrokerModelDescriptor,
	type ModelBrokerRoute,
	type ModelBrokerRouteCandidate,
	type ModelBrokerRouteConfig,
	type ModelBrokerSettings,
	type ModelBrokerSettingsBuildOptions,
	type ModelBrokerSettingsConfig,
	type ModelBrokerSettingsDiagnostic,
	ModelBrokerSettingsError,
	type ModelBrokerSettingsErrorCode,
	type ModelBrokerSettingsInput,
	type ModelBrokerSettingsScope,
	type ModelReference as ModelBrokerModelReference,
	parseModelBrokerSettings,
	resolveModelBrokerSettings,
	validateModelBrokerSettings,
} from "./core/model-broker-settings.ts";
export { ModelRegistry } from "./core/model-registry.ts";
export {
	type ModelScopeDiagnostic,
	type ResolveCliModelResult,
	type ResolveModelScopeResult,
	resolveCliModel,
	resolveModelScopeWithDiagnostics,
	type ScopedModel,
} from "./core/model-resolver.ts";
export {
	type CreateModelRuntimeOptions,
	CredentialSynchronizationError,
	type CredentialSynchronizationOperation,
	createModelBroker,
	ModelRuntime,
	type ModelRuntimeAuthOverrides,
} from "./core/model-runtime.ts";
export {
	createOperationBoundary,
	type OperationBoundary,
	type OperationBoundaryOptions,
} from "./core/operation-boundary.ts";
export type {
	PackageManager,
	PathMetadata,
	ProgressCallback,
	ProgressEvent,
	ResolvedPaths,
	ResolvedResource,
} from "./core/package-manager.ts";
export { DefaultPackageManager } from "./core/package-manager.ts";
export type { ResourceCollision, ResourceDiagnostic, ResourceLoader } from "./core/resource-loader.ts";
export { DefaultResourceLoader, loadProjectContextFiles } from "./core/resource-loader.ts";
// SDK for programmatic usage
export {
	AgentSessionRuntime,
	type AgentSessionRuntimeDiagnostic,
	type AgentSessionServices,
	type AgentRuntimeComposition,
	type AgentRuntimeCompositionContext,
	type AgentRuntimeCompositionFactory,
	type AgentRuntimeCompositionOptions,
	type CreateAgentSessionFromServicesOptions,
	type CreateAgentSessionOptions,
	type CreateAgentSessionResult,
	type CreateAgentSessionRuntimeFactory,
	type CreateAgentSessionRuntimeResult,
	type CreateAgentSessionServicesOptions,
	// Factory
	createAgentSession,
	createAgentSessionFromServices,
	createAgentSessionRuntime,
	createAgentSessionServices,
	createAgentRuntimeCompositionFactory,
	createTrustedWorkerSandboxComposition,
	listAllSessions,
	listSessions,
	type SessionCreationOptions,
	type TrustedWorkerSandboxComposition,
	type TrustedWorkerSandboxFactory,
	type TrustedWorkerSandboxProviderOptions,
	type TrustedExternalConnectorRegistryFactory,
	type TrustedSchedulerCompositionFactory,
	type TrustedSchedulerRuntimeOptions,
	type TrustedSubagentCompositionFactory,
	type TrustedTaskCredentialProviderFactory,
	type TrustedToolGatewayFactory,
	createBashTool,
	// Tool factories (for custom cwd)
	createCodingTools,
	createEditTool,
	createFindTool,
	createGrepTool,
	createLsTool,
	createReadOnlyTools,
	createReadTool,
	createWriteTool,
	type MCPAuthCallbackMode,
	type MCPAuthStartOptions,
	type MCPAuthStartResult,
	type PromptTemplate,
} from "./core/sdk.ts";
export {
	RUNTIME_SESSION_SURFACES,
	createRuntimeSessionSurfaceAdapter,
	isRuntimeSessionSurface,
	type RuntimeSessionSurfaceAdapter,
	type RuntimeSessionSurface,
} from "./core/runtime-session-surface.ts";
export {
	createSessionBranchBoundary,
	createSessionCheckpoint,
	getSessionBoundaries,
	isSessionBoundaryRecord,
	recoverSessionCheckpoint,
	SESSION_BOUNDARY_CUSTOM_TYPE,
	SESSION_BOUNDARY_SCHEMA_VERSION,
	SessionBoundaryError,
	type SessionBoundaryKind,
	type SessionBoundaryRecord,
	type SessionBoundaryStatus,
} from "./core/session-boundary.ts";
export {
	type BranchSummaryEntry,
	buildContextEntries,
	buildSessionContext,
	type CompactionEntry,
	CURRENT_SESSION_VERSION,
	type CustomEntry,
	type CustomMessageEntry,
	type FileEntry,
	getLatestCompactionEntry,
	type ModelChangeEntry,
	migrateSessionEntries,
	type NewSessionOptions,
	parseSessionEntries,
	type SessionContext,
	type SessionEntry,
	type SessionEntryBase,
	type SessionHeader,
	type SessionInfo,
	type SessionInfoEntry,
	type SessionMessageEntry,
	type SessionTreeNode,
	sessionEntryToContextMessages,
	type ThinkingLevelChangeEntry,
} from "./core/session-manager.ts";
export {
	DEFAULT_SESSION_WRITE_LOCK_RETRY_DELAY_MS,
	DEFAULT_SESSION_WRITE_LOCK_STALE_MS,
	DEFAULT_SESSION_WRITE_LOCK_TIMEOUT_MS,
	SessionWriteCoordinationError,
	SessionWriteCoordinator,
	type SessionWriteCoordinationErrorCode,
	type SessionWriteCoordinatorOptions,
} from "./core/session-write-coordinator.ts";
export {
	type CompactionSettings,
	type DefaultProjectTrust,
	type FullscreenExitOutput,
	type ImageSettings,
	type PackageSource,
	type RetrySettings,
	SettingsManager,
	type SettingsManagerCreateOptions,
	type TuiMode,
} from "./core/settings-manager.ts";
// Skills
export {
	formatSkillsForPrompt,
	type LoadSkillsFromDirOptions,
	type LoadSkillsResult,
	loadSkills,
	loadSkillsFromDir,
	type Skill,
	type SkillFrontmatter,
} from "./core/skills.ts";
export { createSyntheticSourceInfo } from "./core/source-info.ts";
export { type EditDiffResult, generateDiffString, generateUnifiedPatch } from "./core/tools/edit-diff.ts";
// Tools
export {
	type BashOperations,
	type BashSpawnContext,
	type BashSpawnHook,
	type BashToolDetails,
	type BashToolInput,
	type BashToolOptions,
	createBashToolDefinition,
	createEditToolDefinition,
	createFindToolDefinition,
	createGrepToolDefinition,
	createLocalBashOperations,
	createLsToolDefinition,
	createReadToolDefinition,
	createWriteToolDefinition,
	DEFAULT_MAX_BYTES,
	DEFAULT_MAX_LINES,
	type EditOperations,
	type EditToolDetails,
	type EditToolInput,
	type EditToolOptions,
	type FindOperations,
	type FindToolDetails,
	type FindToolInput,
	type FindToolOptions,
	formatSize,
	type GrepOperations,
	type GrepToolDetails,
	type GrepToolInput,
	type GrepToolOptions,
	type LsOperations,
	type LsToolDetails,
	type LsToolInput,
	type LsToolOptions,
	type ReadOperations,
	type ReadToolDetails,
	type ReadToolInput,
	type ReadToolOptions,
	type ToolsOptions,
	type TruncationOptions,
	type TruncationResult,
	truncateHead,
	truncateLine,
	truncateTail,
	type WriteOperations,
	type WriteToolInput,
	type WriteToolOptions,
	withFileMutationQueue,
} from "./core/tools/index.ts";
export {
	hasTrustRequiringProjectResources,
	type ProjectTrustDecision,
	ProjectTrustStore,
	type ProjectTrustStoreEntry,
	type ProjectTrustUpdate,
} from "./core/trust-manager.ts";
// Main entry point
export { type MainOptions, main } from "./main.ts";
export type {
	AuditEvent,
	AuditEventType,
	AuditQuery,
	AuditQueryData,
	AuditQueryResult,
	AuditReplayData,
	AuditReplayQuery,
	AuditReplayResult,
	AuditWarning,
	AutomationError,
	AutomationErrorCode,
	CapabilityBindingView,
	CapabilityCatalogView,
	CapabilityDescriptorView,
	ExternalExecutionMapping,
	ExternalExecutionRef,
	ExternalMapData,
	ExternalMappingPersistenceResult,
	ExternalMappingRequest,
	GetExecutionPolicyData,
	GetModelRoutesData,
	InitializeData,
	RpcAuditCommandType,
	RpcAuditQueryCommand,
	RpcAuditReplayCommand,
	RpcAutomationCommandType,
	RpcAutomationResponse,
	RpcMcpAuthInteraction,
	RpcMcpAuthInteractiveOptions,
	RpcTransportAddress,
	RpcTransportAddressErrorCode,
	RpcTransportAddressParseResult,
	RpcTransportConnection,
	RpcTransportDispatcher,
	RpcTransportErrorCode,
	RpcTransportErrorRecord,
	RpcTransportOptions,
	RpcTransportSink,
	TcpRpcAddress,
	RpcRunCommandType,
	RpcSchedulerCommandType,
	RpcSchedulerResponse,
	RpcTaskCredentialCommandType,
	RpcTaskGateCommandType,
	RunAcceptedData,
	RunCancelData,
	RunGetData,
	RunReceipt,
	RunRecord,
	RunRecoveryState,
	RunStatus,
	RunStreamEvent,
	RunTerminalStatus,
	SchedulerStatusData,
	TaskCredentialGetData,
	TaskCredentialHeartbeatData,
	TaskCredentialIssueData,
	TaskCredentialListData,
	TaskCredentialRevokeData,
	TaskCredentialSettleData,
	TaskGateErrorCode,
	TaskGateGetData,
	TaskGateListData,
	TaskGateMutationData,
	TaskGateRecord,
	TaskGateStatus,
	RpcTaskGraphCommandType,
	TaskGraphErrorCode,
	TaskGraphGateRef,
	TaskGraphGetData,
	TaskGraphListData,
	TaskGraphMutationData,
	TaskGraphNodeAvailability,
	TaskGraphNodeDefinition,
	TaskGraphNodeStatus,
	TaskGraphNodeView,
	TaskGraphRecord,
	TaskGraphRunRef,
	TaskGraphStatus,
	TaskGraphSummary,
} from "./modes/index.ts";
// Run modes for programmatic SDK usage
export {
	AutomationRpcError,
	McpAuthRpcError,
	McpContentRpcError,
	InteractiveMode,
	type InteractiveModeOptions,
	type JsonAgentSessionEvent,
	type ModelInfo,
	type PrintModeOptions,
	RpcClient,
	type RpcClientOptions,
	type RpcClientTcpOptions,
	type RpcClientTransportOptions,
	RPC_TRANSPORT_LOOPBACK_HOST,
	RPC_TRANSPORT_PORT_MAX,
	RPC_TRANSPORT_PORT_MIN,
	RpcTransport,
	RpcTransportAddressError,
	RpcTransportError,
	createRpcTransport,
	createTcpRpcTransport,
	formatRpcTransportAddress,
	parseRpcTransportAddress,
	validateRpcTransportAddress,
	createRpcHostController,
	RpcHostController,
	type RpcHostControllerOptions,
	type RpcOutputSink,
	type RpcWireRecord,
	type RpcHostOutputRecord,
	type RpcHostOutputSink,
	type RpcCommand,
	type RpcEventListener,
	type RpcExtensionUIRequest,
	type RpcExtensionUIResponse,
	type RpcResponse,
	type RpcRunEventListener,
	type RpcRunStreamEvent,
	type RpcModeOptions,
	type RpcSessionState,
	runPrintMode,
	runRpcMode,
} from "./modes/index.ts";
// UI components for extensions
export {
	ArminComponent,
	AssistantMessageComponent,
	BashExecutionComponent,
	BorderedLoader,
	BranchSummaryMessageComponent,
	CompactionSummaryMessageComponent,
	CustomEditor,
	CustomMessageComponent,
	DynamicBorder,
	ExtensionEditorComponent,
	ExtensionInputComponent,
	ExtensionSelectorComponent,
	FooterComponent,
	keyHint,
	keyText,
	LoginDialogComponent,
	ModelSelectorComponent,
	OAuthSelectorComponent,
	type RenderDiffOptions,
	rawKeyHint,
	renderDiff,
	SessionSelectorComponent,
	type SettingsCallbacks,
	type SettingsConfig,
	SettingsSelectorComponent,
	ShowImagesSelectorComponent,
	SkillInvocationMessageComponent,
	ThemeSelectorComponent,
	ThinkingSelectorComponent,
	ToolExecutionComponent,
	type ToolExecutionOptions,
	TreeSelectorComponent,
	truncateToVisualLines,
	UserMessageComponent,
	UserMessageSelectorComponent,
	type VisualTruncateResult,
} from "./modes/interactive/components/index.ts";
// Theme utilities for custom tools and extensions
export {
	getLanguageFromPath,
	getMarkdownTheme,
	getSelectListTheme,
	getSettingsListTheme,
	highlightCode,
	initTheme,
	Theme,
	type ThemeColor,
} from "./modes/interactive/theme/theme.ts";
// Clipboard utilities
export { copyToClipboard } from "./utils/clipboard.ts";
export { parseFrontmatter, stripFrontmatter } from "./utils/frontmatter.ts";
export { convertToPng } from "./utils/image-convert.ts";
export { formatDimensionNote, type ResizedImage, resizeImage } from "./utils/image-resize.ts";
// Shell utilities
export { getShellConfig } from "./utils/shell.ts";
