import { Result, type Result as ResultValue } from "../result.ts";
import { redactProjection } from "./errors.ts";
import { canonicalFoundationJson } from "./identity.ts";

export const EVENT_SCHEMA_VERSION = 1 as const;
export type EventSchemaVersion = typeof EVENT_SCHEMA_VERSION;
export type FoundationJsonValue = null | boolean | number | string | FoundationJsonValue[] | { [key: string]: FoundationJsonValue };
export type EventCategoryClass = "durable" | "live" | "derived";
export type EventProducer = "harness" | "reducer" | "model" | "tool" | "queue" | "role" | "goal" | "workflow" | "ask" | "artifact" | "migration" | "subagent";
export type EventConsumer = "observer" | "recovery" | "reducer" | "audit" | "rpc" | "ui" | "sdk" | "workflow" | "control_plane";
export interface EventCorrelationRef { sessionId: string; laneId?: string; operationId?: string; workerId?: string; runId?: string; turnId?: string; stepId?: string; toolCallId?: string; roleId?: string; roleRevisionId?: string; modelProfileId?: string; modelProfileRevisionId?: string; bindingId?: string; bindingEpochId?: string; attemptId?: string; attemptReceiptId?: string; workerReceiptId?: string; agentInstanceId?: string; goalId?: string; planId?: string; stageId?: string; taskId?: string; dispatchId?: string; taskResultId?: string; runReceiptId?: string; workflowId?: string; askId?: string; artifactId?: string; receiptId?: string; }
export type DurableEventCategory = "session.created" | "session.closed" | "lane.created" | "lane.moved" | "message.persisted" | "operation.started" | "operation.finished" | "abort.requested" | "step.checkpointed" | "write.deferred" | "tool.started" | "tool.finished" | "queue.enqueued" | "queue.cancelled" | "usage.recorded" | "model.request" | "compaction.persisted" | "navigation.completed" | "binding.activated" | "binding.created" | "binding.revised" | "binding.epoch_activated" | "attempt.started" | "attempt.finished" | "attempt_receipt.written" | "task_result.settled" | "run_receipt.written" | "role.created" | "role.revised" | "role.tombstoned" | "profile.created" | "profile.revised" | "profile.tombstoned" | "task.created" | "task.updated" | "dispatch.created" | "dispatch.updated" | "worker.lifecycle_transitioned" | "worker.operation_recorded" | "worker_receipt.written" | "goal.created" | "goal.updated" | "plan.created" | "plan.updated" | "todo.created" | "todo.updated" | "todo.completed" | "ask.created" | "ask.answered" | "ask.expired" | "ask.escalated" | "ask.cancelled" | "workflow.started" | "workflow.paused" | "workflow.resumed" | "workflow.stopped" | "workflow.step_transitioned" | "artifact.registered" | "migration.applied" | "subagent.lifecycle_transitioned" | "subagent.mailbox_message_sent" | "subagent.mailbox_message_acknowledged" | "subagent.worktree_recorded" | "scheduler.queue_transitioned" | "scheduler.claim_acquired" | "scheduler.claim_renewed" | "scheduler.claim_released" | "scheduler.dispatch_transitioned" | "scheduler.executor_selected" | "scheduler.join_recorded" | "scheduler.message_posted" | "scheduler.message_acked" | "scheduler.handoff_transitioned" | "scheduler.wake_scheduled" | "scheduler.wake_fired" | "scheduler.deadlock_detected";
export type LiveEventCategory = "stream.text" | "stream.thinking" | "stream.tool_progress" | "stream.partial_result" | "turn.started" | "turn.finished";
export type DerivedEventCategory = "run_start" | "run_end" | "snapshot.session" | "snapshot.lane" | "resume_boundary.derived" | "queue.derived" | "pending_writes.derived" | "budget.derived" | "usage.derived" | "epoch.derived" | "position.derived" | "attempt.derived" | "run.derived";
export type EventCategoryId = DurableEventCategory | LiveEventCategory | DerivedEventCategory;
export type EventReplayRule = "must" | "never";
export type EventRetention = "ledger" | "session" | "ephemeral";
export type EventMigration = "stable" | "additive";
export interface EventCatalogEntryBase<TClass extends EventCategoryClass = EventCategoryClass> { category: EventCategoryId; class: TClass; schemaVersion: 1; producer: EventProducer; consumers: readonly EventConsumer[]; stableFields: readonly string[]; correlationFields: readonly (keyof EventCorrelationRef)[]; replay: EventReplayRule; retention: EventRetention; migration: EventMigration; redacted: readonly string[]; description: string; }
export interface DurableEventCatalogEntry extends EventCatalogEntryBase<"durable"> { replay: "must"; retention: "ledger"; derivedFrom?: never; }
export interface LiveEventCatalogEntry extends EventCatalogEntryBase<"live"> { replay: "never"; retention: "ephemeral"; derivedFrom?: never; }
export interface DerivedEventCatalogEntry extends EventCatalogEntryBase<"derived"> { replay: "never"; retention: "session"; derivedFrom: readonly DurableEventCategory[]; }
export type EventCatalogEntry = DurableEventCatalogEntry | LiveEventCatalogEntry | DerivedEventCatalogEntry;

const durableCategories: readonly DurableEventCategory[] = ["session.created", "session.closed", "lane.created", "lane.moved", "message.persisted", "operation.started", "operation.finished", "abort.requested", "step.checkpointed", "write.deferred", "tool.started", "tool.finished", "queue.enqueued", "queue.cancelled", "usage.recorded", "model.request", "compaction.persisted", "navigation.completed", "binding.activated", "binding.created", "binding.revised", "binding.epoch_activated", "attempt.started", "attempt.finished", "attempt_receipt.written", "task_result.settled", "run_receipt.written", "role.created", "role.revised", "role.tombstoned", "profile.created", "profile.revised", "profile.tombstoned", "task.created", "task.updated", "dispatch.created", "dispatch.updated", "worker.lifecycle_transitioned", "worker.operation_recorded", "worker_receipt.written", "goal.created", "goal.updated", "plan.created", "plan.updated", "todo.created", "todo.updated", "todo.completed", "ask.created", "ask.answered", "ask.expired", "ask.escalated", "ask.cancelled", "workflow.started", "workflow.paused", "workflow.resumed", "workflow.stopped", "workflow.step_transitioned", "artifact.registered", "migration.applied", "subagent.lifecycle_transitioned", "subagent.mailbox_message_sent", "subagent.mailbox_message_acknowledged", "subagent.worktree_recorded", "scheduler.queue_transitioned", "scheduler.claim_acquired", "scheduler.claim_renewed", "scheduler.claim_released", "scheduler.dispatch_transitioned", "scheduler.executor_selected", "scheduler.join_recorded", "scheduler.message_posted", "scheduler.message_acked", "scheduler.handoff_transitioned", "scheduler.wake_scheduled", "scheduler.wake_fired", "scheduler.deadlock_detected"];
const liveCategories: readonly LiveEventCategory[] = ["stream.text", "stream.thinking", "stream.tool_progress", "stream.partial_result", "turn.started", "turn.finished"];
const derivedCategories: readonly DerivedEventCategory[] = ["run_start", "run_end", "snapshot.session", "snapshot.lane", "resume_boundary.derived", "queue.derived", "pending_writes.derived", "budget.derived", "usage.derived", "epoch.derived", "position.derived", "attempt.derived", "run.derived"];
export type RoleEventPayload = { schemaVersion: 1; roleId: string; roleRevisionId: string; revision: number; scope: "global" | "project"; [key: string]: FoundationJsonValue };
export type ProfileEventPayload = { schemaVersion: 1; profileId: string; profileRevisionId: string; revision: number; [key: string]: FoundationJsonValue };
export type BindingEventPayload = { schemaVersion: 1; bindingId: string; taskId: string; [key: string]: FoundationJsonValue };
export type BindingEpochEventPayload = { schemaVersion: 1; bindingId: string; bindingEpochId: string; taskId: string; attemptId: string; ordinal: number; [key: string]: FoundationJsonValue };
export type AttemptEventPayload = { schemaVersion: 1; attemptId: string; dispatchId: string; taskId: string; [key: string]: FoundationJsonValue };
export type AttemptReceiptEventPayload = { schemaVersion: 1; attemptReceiptId: string; attemptId: string; taskId: string; [key: string]: FoundationJsonValue };
export type TaskEventPayload = { schemaVersion: 1; taskId: string; goalId: string; [key: string]: FoundationJsonValue };
export type DispatchEventPayload = { schemaVersion: 1; dispatchId: string; taskId: string; [key: string]: FoundationJsonValue };
export type WorkerLifecycleStatus = "new" | "starting" | "ready" | "running" | "cancelling" | "completed" | "failed" | "cancelled" | "lost" | "reclaiming" | "reclaimed" | "reclaim_unknown";
export type WorkerLifecycleEventPayload = { schemaVersion: 1; workerId: string; providerId: string; sessionId: string; laneId: string; status: WorkerLifecycleStatus; revision: number; [key: string]: FoundationJsonValue };
export type WorkerOperationEventPayload = { schemaVersion: 1; workerId: string; providerId: string; sessionId: string; laneId: string; operationId: string; phase: string; revision: number; [key: string]: FoundationJsonValue };
export type WorkerReceiptEventPayload = { schemaVersion: 1; workerReceiptId: string; operationId: string; [key: string]: FoundationJsonValue };
export type TaskResultEventPayload = { schemaVersion: 1; taskResultId: string; taskId: string; [key: string]: FoundationJsonValue };
export type RunReceiptEventPayload = { schemaVersion: 1; runReceiptId: string; runId: string; [key: string]: FoundationJsonValue };
export type GoalEventPayload = { schemaVersion: 1; goalId: string; sessionId: string; revision: number; [key: string]: FoundationJsonValue };
export type PlanEventPayload = { schemaVersion: 1; planId: string; goalId: string; revision: number; [key: string]: FoundationJsonValue };
export type TodoEventPayload = { schemaVersion: 1; todoId: string; revision: number; [key: string]: FoundationJsonValue };
export type AskEventPayload = { schemaVersion: 1; askId: string; sessionId: string; revision: number; [key: string]: FoundationJsonValue };
export type WorkflowEventPayload = { schemaVersion: 1; workflowId: string; revision: number; [key: string]: FoundationJsonValue };
export type ArtifactEventPayload = { schemaVersion: 1; artifactId: string; digest: string; [key: string]: FoundationJsonValue };
export type SubagentLifecycleEventPayload = { schemaVersion: 1; childAgentInstanceId: string; parentAgentInstanceId: string; ancestorIds: string[]; depth: number; spawnId: string; taskId: string; dispatchId: string; attemptId: string; bindingId: string; bindingEpochIds: string[]; providerKind: "in_process" | "fork" | "agent_runtime_host"; providerId: string; forkScope: "none" | "all" | "recent_n" | "task_package"; status: "spawning" | "running" | "awaiting_input" | "background" | "cancelling" | "succeeded" | "failed" | "cancelled" | "lost" | "closed"; revision: number; createdAt: string; terminalAt?: string; attemptReceiptId?: string; taskResultId?: string } & Record<string, FoundationJsonValue>;
export type SubagentMailboxMessageSentEventPayload = { schemaVersion: 1; messageId: string; fromAgentInstanceId: string; toAgentInstanceId: string; kind: "input" | "query" | "notice" | "result_ref"; body: FoundationJsonValue; correlation: { sessionId: string; laneId: string; taskId: string; attemptId: string; agentInstanceId: string; [key: string]: FoundationJsonValue }; createdAt: string; [key: string]: FoundationJsonValue };
export type SubagentMailboxMessageAcknowledgedEventPayload = { schemaVersion: 1; messageId: string; fromAgentInstanceId: string; toAgentInstanceId: string; at: string; byAttemptId: string; [key: string]: FoundationJsonValue };
export type SubagentWorktreeEventPayload = { schemaVersion: 1; childAgentInstanceId: string; attemptId: string; baseRef: string; worktreeDigest: string; apply?: { status: "applied" | "conflict" | "unknown"; at: string; [key: string]: FoundationJsonValue }; cleanedUp?: boolean } & Record<string, FoundationJsonValue>;
export type SchedulerQueueEventPayload = { schemaVersion: 1; queueEntryId: string; sessionId: string; taskId: string; state: string; revision: number; [key: string]: FoundationJsonValue };
export type SchedulerClaimEventPayload = { schemaVersion: 1; claimId: string; queueEntryId: string; taskId: string; ownerId: string; revision: number; [key: string]: FoundationJsonValue };
export type SchedulerDispatchEventPayload = { schemaVersion: 1; queueEntryId: string; claimId: string; dispatchId: string; providerId: string; providerClass: string; status: string; revision: number; [key: string]: FoundationJsonValue };
export type SchedulerSelectionEventPayload = { schemaVersion: 1; queueEntryId: string; taskId: string; chosenProviderId: string; inputsDigest: string; decidedAt: string; [key: string]: FoundationJsonValue };
export type SchedulerJoinEventPayload = { schemaVersion: 1; joinId: string; taskId: string; policy: string; [key: string]: FoundationJsonValue };
export type SchedulerMessageEventPayload = { schemaVersion: 1; messageId: string; threadId: string; fromSessionId: string; toSessionId: string; type: string; ack: string; revision: number; [key: string]: FoundationJsonValue };
export type SchedulerHandoffEventPayload = { schemaVersion: 1; transferId: string; taskId: string; fromOwnerId: string; toOwnerId: string; state: string; revision: number; [key: string]: FoundationJsonValue };
export type SchedulerWakeEventPayload = { schemaVersion: 1; wakeId: string; workflowId: string; dueAt: string; revision: number; [key: string]: FoundationJsonValue };
export type SchedulerDeadlockEventPayload = { schemaVersion: 1; detectionId: string; detectedAt: string; [key: string]: FoundationJsonValue };
export interface EventPayloadMap {
	"role.created": RoleEventPayload; "role.revised": RoleEventPayload; "role.tombstoned": RoleEventPayload;
	"profile.created": ProfileEventPayload; "profile.revised": ProfileEventPayload; "profile.tombstoned": ProfileEventPayload;
	"binding.created": BindingEventPayload; "binding.revised": BindingEventPayload; "binding.activated": BindingEventPayload; "binding.epoch_activated": BindingEpochEventPayload;
	"attempt.started": AttemptEventPayload; "attempt.finished": AttemptEventPayload; "attempt_receipt.written": AttemptReceiptEventPayload;
	"task.created": TaskEventPayload; "task.updated": TaskEventPayload; "dispatch.created": DispatchEventPayload; "dispatch.updated": DispatchEventPayload;
	"worker.lifecycle_transitioned": WorkerLifecycleEventPayload; "worker.operation_recorded": WorkerOperationEventPayload;
	"worker_receipt.written": WorkerReceiptEventPayload; "task_result.settled": TaskResultEventPayload; "run_receipt.written": RunReceiptEventPayload;
	"goal.created": GoalEventPayload; "goal.updated": GoalEventPayload; "plan.created": PlanEventPayload; "plan.updated": PlanEventPayload;
	"todo.created": TodoEventPayload; "todo.updated": TodoEventPayload; "todo.completed": TodoEventPayload; "ask.created": AskEventPayload; "ask.answered": AskEventPayload; "ask.expired": AskEventPayload; "ask.escalated": AskEventPayload; "ask.cancelled": AskEventPayload;
	"workflow.started": WorkflowEventPayload; "workflow.paused": WorkflowEventPayload; "workflow.resumed": WorkflowEventPayload; "workflow.stopped": WorkflowEventPayload; "workflow.step_transitioned": WorkflowEventPayload;
	"artifact.registered": ArtifactEventPayload;
	"subagent.lifecycle_transitioned": SubagentLifecycleEventPayload; "subagent.mailbox_message_sent": SubagentMailboxMessageSentEventPayload; "subagent.mailbox_message_acknowledged": SubagentMailboxMessageAcknowledgedEventPayload; "subagent.worktree_recorded": SubagentWorktreeEventPayload;
	"scheduler.queue_transitioned": SchedulerQueueEventPayload;
	"scheduler.claim_acquired": SchedulerClaimEventPayload; "scheduler.claim_renewed": SchedulerClaimEventPayload; "scheduler.claim_released": SchedulerClaimEventPayload;
	"scheduler.dispatch_transitioned": SchedulerDispatchEventPayload; "scheduler.executor_selected": SchedulerSelectionEventPayload; "scheduler.join_recorded": SchedulerJoinEventPayload;
	"scheduler.message_posted": SchedulerMessageEventPayload; "scheduler.message_acked": SchedulerMessageEventPayload;
	"scheduler.handoff_transitioned": SchedulerHandoffEventPayload;
	"scheduler.wake_scheduled": SchedulerWakeEventPayload; "scheduler.wake_fired": SchedulerWakeEventPayload;
	"scheduler.deadlock_detected": SchedulerDeadlockEventPayload;
}
export type EventPayloadForCategory<TCategory extends EventCategoryId> = TCategory extends keyof EventPayloadMap ? EventPayloadMap[TCategory] : FoundationJsonValue;
const producerFor = (category: string): EventProducer => category.startsWith("scheduler") ? "harness" : category.startsWith("role") || category.startsWith("binding") || category.startsWith("profile") ? "role" : category.startsWith("goal") || category.startsWith("plan") || category.startsWith("task") || category.startsWith("dispatch") || category.startsWith("attempt") || category.startsWith("worker_receipt") || category.startsWith("task_result") || category.startsWith("run_receipt") ? "harness" : category.startsWith("ask") ? "ask" : category.startsWith("workflow") ? "workflow" : category.startsWith("artifact") ? "artifact" : category.startsWith("stream") ? "model" : category.startsWith("subagent") ? "subagent" : "harness";
const derivedFrom: Readonly<Record<DerivedEventCategory, readonly DurableEventCategory[]>> = {
	run_start: ["operation.started"], run_end: ["run_receipt.written"], "snapshot.session": ["session.created", "session.closed", "operation.started", "operation.finished", "task.updated", "run_receipt.written"], "snapshot.lane": ["lane.created", "lane.moved", "navigation.completed"],
	"resume_boundary.derived": ["operation.finished", "attempt.finished", "run_receipt.written"], "queue.derived": ["queue.enqueued", "queue.cancelled"], "pending_writes.derived": ["write.deferred", "operation.finished"], "budget.derived": ["usage.recorded"], "usage.derived": ["usage.recorded"], "epoch.derived": ["binding.epoch_activated"], "position.derived": ["step.checkpointed", "navigation.completed"], "attempt.derived": ["attempt.started", "attempt.finished", "attempt_receipt.written"], "run.derived": ["task_result.settled", "run_receipt.written"],
};
const correlationFor = (category: EventCategoryId): readonly (keyof EventCorrelationRef)[] => {
	if (category.startsWith("role")) return ["sessionId", "roleId", "roleRevisionId"];
	if (category.startsWith("profile")) return ["sessionId", "modelProfileId", "modelProfileRevisionId"];
	if (category.startsWith("binding")) return ["sessionId", "taskId", "bindingId", "bindingEpochId", "roleRevisionId", "modelProfileRevisionId"];
	if (category.startsWith("attempt_receipt")) return ["sessionId", "taskId", "attemptId", "attemptReceiptId", "dispatchId", "agentInstanceId"];
	if (category.startsWith("attempt")) return ["sessionId", "taskId", "dispatchId", "attemptId", "bindingId", "agentInstanceId"];
	if (category.startsWith("worker.")) return ["sessionId", "laneId", "workerId", "operationId", "runId", "bindingId", "bindingEpochId", "attemptId", "receiptId"];
	if (category.startsWith("worker_receipt")) return ["sessionId", "taskId", "operationId", "workerReceiptId"];
	if (category.startsWith("task_result")) return ["sessionId", "taskId", "attemptReceiptId", "taskResultId"];
	if (category.startsWith("run_receipt")) return ["sessionId", "runId", "taskResultId", "runReceiptId"];
	if (category.startsWith("task")) return ["sessionId", "goalId", "taskId"];
	if (category.startsWith("dispatch")) return ["sessionId", "taskId", "dispatchId", "bindingId"];
	if (category.startsWith("goal")) return ["sessionId", "goalId"];
	if (category.startsWith("plan")) return ["sessionId", "goalId", "planId"];
	if (category.startsWith("todo")) return ["sessionId", "goalId", "taskId"];
	if (category.startsWith("ask")) return ["sessionId", "askId", "taskId", "goalId"];
	if (category.startsWith("workflow")) return ["sessionId", "workflowId", "goalId", "planId", "stageId", "stepId"];
	if (category.startsWith("artifact")) return ["sessionId", "artifactId", "taskId", "attemptId"];
	if (category === "subagent.lifecycle_transitioned") return ["sessionId", "laneId", "agentInstanceId", "taskId", "dispatchId", "attemptId"];
	if (category === "subagent.mailbox_message_sent" || category === "subagent.mailbox_message_acknowledged") return ["sessionId", "laneId", "agentInstanceId", "taskId", "attemptId"];
	if (category === "subagent.worktree_recorded") return ["sessionId", "laneId", "agentInstanceId", "attemptId"];
	if (category.startsWith("scheduler")) return ["sessionId", "taskId", "dispatchId", "attemptId", "workflowId", "askId"];
	if (category.startsWith("stream") || category.startsWith("turn")) return ["sessionId", "laneId", "runId", "turnId", "stepId"];
	return ["sessionId", "laneId", "operationId", "runId", "turnId", "stepId"];
};
interface EventPayloadRuleV1 { required: readonly string[]; allowed: readonly string[]; stringFields: readonly string[]; integerFields: readonly string[]; optionalStringFields?: readonly string[]; stringValues?: Readonly<Record<string, readonly string[]>>; }
const typedPayloadRules: Readonly<Record<string, EventPayloadRuleV1>> = {
	"role.created": { required: ["schemaVersion", "roleId", "roleRevisionId", "revision", "scope"], allowed: ["schemaVersion", "roleId", "roleRevisionId", "revision", "scope", "fingerprint"], stringFields: ["roleId", "roleRevisionId", "scope"], integerFields: ["revision"] },
	"role.revised": { required: ["schemaVersion", "roleId", "roleRevisionId", "revision", "scope"], allowed: ["schemaVersion", "roleId", "roleRevisionId", "revision", "scope", "fingerprint"], stringFields: ["roleId", "roleRevisionId", "scope"], integerFields: ["revision"] },
	"role.tombstoned": { required: ["schemaVersion", "roleId", "roleRevisionId", "revision", "scope"], allowed: ["schemaVersion", "roleId", "roleRevisionId", "revision", "scope", "fingerprint"], stringFields: ["roleId", "roleRevisionId", "scope"], integerFields: ["revision"] },
	"profile.created": { required: ["schemaVersion", "profileId", "profileRevisionId", "revision"], allowed: ["schemaVersion", "profileId", "profileRevisionId", "revision", "fingerprint"], stringFields: ["profileId", "profileRevisionId"], integerFields: ["revision"] },
	"profile.revised": { required: ["schemaVersion", "profileId", "profileRevisionId", "revision"], allowed: ["schemaVersion", "profileId", "profileRevisionId", "revision", "fingerprint"], stringFields: ["profileId", "profileRevisionId"], integerFields: ["revision"] },
	"profile.tombstoned": { required: ["schemaVersion", "profileId", "profileRevisionId", "revision"], allowed: ["schemaVersion", "profileId", "profileRevisionId", "revision", "fingerprint"], stringFields: ["profileId", "profileRevisionId"], integerFields: ["revision"] },
	"binding.created": { required: ["schemaVersion", "bindingId", "taskId"], allowed: ["schemaVersion", "bindingId", "taskId", "revision", "fingerprint"], stringFields: ["bindingId", "taskId"], integerFields: ["revision"] },
	"binding.revised": { required: ["schemaVersion", "bindingId", "taskId"], allowed: ["schemaVersion", "bindingId", "taskId", "revision", "fingerprint"], stringFields: ["bindingId", "taskId"], integerFields: ["revision"] },
	"binding.activated": { required: ["schemaVersion", "bindingId", "taskId"], allowed: ["schemaVersion", "bindingId", "taskId", "revision", "fingerprint"], stringFields: ["bindingId", "taskId"], integerFields: ["revision"] },
	"binding.epoch_activated": { required: ["schemaVersion", "bindingId", "bindingEpochId", "taskId", "attemptId", "ordinal"], allowed: ["schemaVersion", "bindingId", "bindingEpochId", "taskId", "attemptId", "ordinal"], stringFields: ["bindingId", "bindingEpochId", "taskId", "attemptId"], integerFields: ["ordinal"] },
	"attempt.started": { required: ["schemaVersion", "attemptId", "dispatchId", "taskId"], allowed: ["schemaVersion", "attemptId", "dispatchId", "taskId"], stringFields: ["attemptId", "dispatchId", "taskId"], integerFields: [] },
	"attempt.finished": { required: ["schemaVersion", "attemptId", "dispatchId", "taskId"], allowed: ["schemaVersion", "attemptId", "dispatchId", "taskId"], stringFields: ["attemptId", "dispatchId", "taskId"], integerFields: [] },
	"attempt_receipt.written": { required: ["schemaVersion", "attemptReceiptId", "attemptId", "taskId"], allowed: ["schemaVersion", "attemptReceiptId", "attemptId", "taskId"], stringFields: ["attemptReceiptId", "attemptId", "taskId"], integerFields: [] },
	"task.created": { required: ["schemaVersion", "taskId", "goalId"], allowed: ["schemaVersion", "taskId", "goalId", "revision", "fingerprint"], stringFields: ["taskId", "goalId"], integerFields: ["revision"] },
	"task.updated": { required: ["schemaVersion", "taskId", "goalId"], allowed: ["schemaVersion", "taskId", "goalId", "revision", "fingerprint"], stringFields: ["taskId", "goalId"], integerFields: ["revision"] },
	"dispatch.created": { required: ["schemaVersion", "dispatchId", "taskId"], allowed: ["schemaVersion", "dispatchId", "taskId", "revision"], stringFields: ["dispatchId", "taskId"], integerFields: ["revision"] },
	"dispatch.updated": { required: ["schemaVersion", "dispatchId", "taskId"], allowed: ["schemaVersion", "dispatchId", "taskId", "revision"], stringFields: ["dispatchId", "taskId"], integerFields: ["revision"] },
	"worker.lifecycle_transitioned": { required: ["schemaVersion", "workerId", "providerId", "sessionId", "laneId", "status", "revision"], allowed: ["schemaVersion", "workerId", "providerId", "sessionId", "laneId", "status", "revision", "runId", "bindingId", "bindingEpochId", "attemptId", "profileId", "createdAt", "readyAt", "endedAt", "lastHeartbeatAt", "activeOperationId", "operationId", "receiptId"], stringFields: ["workerId", "providerId", "sessionId", "laneId", "status"], integerFields: ["revision"], optionalStringFields: ["runId", "bindingId", "bindingEpochId", "attemptId", "profileId", "createdAt", "readyAt", "endedAt", "lastHeartbeatAt", "activeOperationId", "operationId", "receiptId"], stringValues: { status: ["new", "starting", "ready", "running", "cancelling", "completed", "failed", "cancelled", "lost", "reclaiming", "reclaimed", "reclaim_unknown"] } },
	"worker.operation_recorded": { required: ["schemaVersion", "workerId", "providerId", "sessionId", "laneId", "operationId", "phase", "revision"], allowed: ["schemaVersion", "workerId", "providerId", "sessionId", "laneId", "operationId", "phase", "revision", "sideEffectState", "receiptId", "recordedAt"], stringFields: ["workerId", "providerId", "sessionId", "laneId", "operationId", "phase"], integerFields: ["revision"], optionalStringFields: ["sideEffectState", "receiptId", "recordedAt"] },
	"worker_receipt.written": { required: ["schemaVersion", "workerReceiptId", "operationId"], allowed: ["schemaVersion", "workerReceiptId", "operationId", "taskId"], stringFields: ["workerReceiptId", "operationId"], integerFields: [] },
	"task_result.settled": { required: ["schemaVersion", "taskResultId", "taskId"], allowed: ["schemaVersion", "taskResultId", "taskId"], stringFields: ["taskResultId", "taskId"], integerFields: [] },
	"run_receipt.written": { required: ["schemaVersion", "runReceiptId", "runId"], allowed: ["schemaVersion", "runReceiptId", "runId"], stringFields: ["runReceiptId", "runId"], integerFields: [] },
	"goal.created": { required: ["schemaVersion", "goalId", "sessionId", "revision"], allowed: ["schemaVersion", "goalId", "sessionId", "revision"], stringFields: ["goalId", "sessionId"], integerFields: ["revision"] },
	"goal.updated": { required: ["schemaVersion", "goalId", "sessionId", "revision"], allowed: ["schemaVersion", "goalId", "sessionId", "revision"], stringFields: ["goalId", "sessionId"], integerFields: ["revision"] },
	"plan.created": { required: ["schemaVersion", "planId", "goalId", "revision"], allowed: ["schemaVersion", "planId", "goalId", "revision"], stringFields: ["planId", "goalId"], integerFields: ["revision"] },
	"plan.updated": { required: ["schemaVersion", "planId", "goalId", "revision"], allowed: ["schemaVersion", "planId", "goalId", "revision"], stringFields: ["planId", "goalId"], integerFields: ["revision"] },
	"todo.created": { required: ["schemaVersion", "todoId", "revision"], allowed: ["schemaVersion", "todoId", "taskId", "goalId", "revision"], stringFields: ["todoId", "taskId", "goalId"], integerFields: ["revision"] },
	"todo.updated": { required: ["schemaVersion", "todoId", "revision"], allowed: ["schemaVersion", "todoId", "taskId", "goalId", "revision"], stringFields: ["todoId", "taskId", "goalId"], integerFields: ["revision"] },
	"todo.completed": { required: ["schemaVersion", "todoId", "revision"], allowed: ["schemaVersion", "todoId", "taskId", "goalId", "revision"], stringFields: ["todoId", "taskId", "goalId"], integerFields: ["revision"] },
	"ask.created": { required: ["schemaVersion", "askId", "sessionId", "revision"], allowed: ["schemaVersion", "askId", "sessionId", "revision"], stringFields: ["askId", "sessionId"], integerFields: ["revision"] },
	"ask.answered": { required: ["schemaVersion", "askId", "sessionId", "revision"], allowed: ["schemaVersion", "askId", "sessionId", "revision"], stringFields: ["askId", "sessionId"], integerFields: ["revision"] },
	"ask.expired": { required: ["schemaVersion", "askId", "sessionId", "revision"], allowed: ["schemaVersion", "askId", "sessionId", "revision"], stringFields: ["askId", "sessionId"], integerFields: ["revision"] },
	"ask.escalated": { required: ["schemaVersion", "askId", "sessionId", "revision"], allowed: ["schemaVersion", "askId", "sessionId", "revision"], stringFields: ["askId", "sessionId"], integerFields: ["revision"] },
	"ask.cancelled": { required: ["schemaVersion", "askId", "sessionId", "revision"], allowed: ["schemaVersion", "askId", "sessionId", "revision"], stringFields: ["askId", "sessionId"], integerFields: ["revision"] },
	"workflow.started": { required: ["schemaVersion", "workflowId", "revision"], allowed: ["schemaVersion", "workflowId", "goalId", "revision", "stepId"], stringFields: ["workflowId", "goalId", "stepId"], integerFields: ["revision"] },
	"workflow.paused": { required: ["schemaVersion", "workflowId", "revision"], allowed: ["schemaVersion", "workflowId", "goalId", "revision", "stepId"], stringFields: ["workflowId", "goalId", "stepId"], integerFields: ["revision"] },
	"workflow.resumed": { required: ["schemaVersion", "workflowId", "revision"], allowed: ["schemaVersion", "workflowId", "goalId", "revision", "stepId"], stringFields: ["workflowId", "goalId", "stepId"], integerFields: ["revision"] },
	"workflow.stopped": { required: ["schemaVersion", "workflowId", "revision"], allowed: ["schemaVersion", "workflowId", "goalId", "revision", "stepId"], stringFields: ["workflowId", "goalId", "stepId"], integerFields: ["revision"] },
	"workflow.step_transitioned": { required: ["schemaVersion", "workflowId", "revision", "stepId"], allowed: ["schemaVersion", "workflowId", "goalId", "revision", "stepId"], stringFields: ["workflowId", "goalId", "stepId"], integerFields: ["revision"] },
	"artifact.registered": { required: ["schemaVersion", "artifactId", "digest"], allowed: ["schemaVersion", "artifactId", "digest"], stringFields: ["artifactId", "digest"], integerFields: [] },
	"subagent.lifecycle_transitioned": { required: ["schemaVersion", "childAgentInstanceId", "parentAgentInstanceId", "ancestorIds", "depth", "spawnId", "taskId", "dispatchId", "attemptId", "bindingId", "bindingEpochIds", "providerKind", "providerId", "forkScope", "status", "revision", "createdAt"], allowed: ["schemaVersion", "childAgentInstanceId", "parentAgentInstanceId", "ancestorIds", "depth", "spawnId", "taskId", "dispatchId", "attemptId", "bindingId", "bindingEpochIds", "providerKind", "providerId", "forkScope", "status", "revision", "createdAt", "terminalAt", "attemptReceiptId", "taskResultId"], stringFields: ["childAgentInstanceId", "parentAgentInstanceId", "spawnId", "taskId", "dispatchId", "attemptId", "bindingId", "providerKind", "providerId", "forkScope", "status", "createdAt"], integerFields: ["depth", "revision"], optionalStringFields: ["terminalAt", "attemptReceiptId", "taskResultId"], stringValues: { providerKind: ["in_process", "fork", "agent_runtime_host"], forkScope: ["none", "all", "recent_n", "task_package"], status: ["spawning", "running", "awaiting_input", "background", "cancelling", "succeeded", "failed", "cancelled", "lost", "closed"] } },
	"subagent.mailbox_message_sent": { required: ["schemaVersion", "messageId", "fromAgentInstanceId", "toAgentInstanceId", "kind", "body", "correlation", "createdAt"], allowed: ["schemaVersion", "messageId", "fromAgentInstanceId", "toAgentInstanceId", "kind", "body", "correlation", "createdAt"], stringFields: ["messageId", "fromAgentInstanceId", "toAgentInstanceId", "kind", "createdAt"], integerFields: [], stringValues: { kind: ["input", "query", "notice", "result_ref"] } },
	"subagent.mailbox_message_acknowledged": { required: ["schemaVersion", "messageId", "fromAgentInstanceId", "toAgentInstanceId", "at", "byAttemptId"], allowed: ["schemaVersion", "messageId", "fromAgentInstanceId", "toAgentInstanceId", "at", "byAttemptId"], stringFields: ["messageId", "fromAgentInstanceId", "toAgentInstanceId", "at", "byAttemptId"], integerFields: [] },
	"subagent.worktree_recorded": { required: ["schemaVersion", "childAgentInstanceId", "attemptId", "baseRef", "worktreeDigest"], allowed: ["schemaVersion", "childAgentInstanceId", "attemptId", "baseRef", "worktreeDigest", "apply", "cleanedUp"], stringFields: ["childAgentInstanceId", "attemptId", "baseRef", "worktreeDigest"], integerFields: [] },
	"scheduler.queue_transitioned": { required: ["schemaVersion", "queueEntryId", "sessionId", "taskId", "state", "revision"], allowed: ["schemaVersion", "queueEntryId", "sessionId", "taskId", "state", "revision", "nodeId", "graphRevision", "claimId", "workflowId", "goalId"], stringFields: ["queueEntryId", "sessionId", "taskId", "state"], integerFields: ["revision"], optionalStringFields: ["nodeId", "claimId", "workflowId", "goalId"], stringValues: { state: ["queued", "claimed", "dispatched", "settled", "cancelled", "expired"] } },
	"scheduler.claim_acquired": { required: ["schemaVersion", "claimId", "queueEntryId", "taskId", "ownerId", "revision"], allowed: ["schemaVersion", "claimId", "queueEntryId", "taskId", "ownerId", "revision", "sessionId"], stringFields: ["claimId", "queueEntryId", "taskId", "ownerId"], integerFields: ["revision"], optionalStringFields: ["sessionId"] },
	"scheduler.claim_renewed": { required: ["schemaVersion", "claimId", "queueEntryId", "taskId", "ownerId", "revision"], allowed: ["schemaVersion", "claimId", "queueEntryId", "taskId", "ownerId", "revision", "sessionId"], stringFields: ["claimId", "queueEntryId", "taskId", "ownerId"], integerFields: ["revision"], optionalStringFields: ["sessionId"] },
	"scheduler.claim_released": { required: ["schemaVersion", "claimId", "queueEntryId", "taskId", "ownerId", "revision"], allowed: ["schemaVersion", "claimId", "queueEntryId", "taskId", "ownerId", "revision", "sessionId"], stringFields: ["claimId", "queueEntryId", "taskId", "ownerId"], integerFields: ["revision"], optionalStringFields: ["sessionId"] },
	"scheduler.dispatch_transitioned": { required: ["schemaVersion", "queueEntryId", "claimId", "dispatchId", "providerId", "providerClass", "status", "revision"], allowed: ["schemaVersion", "queueEntryId", "claimId", "dispatchId", "providerId", "providerClass", "status", "revision", "attemptId", "reservationId"], stringFields: ["queueEntryId", "claimId", "dispatchId", "providerId", "providerClass", "status"], integerFields: ["revision"], optionalStringFields: ["attemptId", "reservationId"], stringValues: { providerClass: ["scheduler", "task_executor", "agent", "external_connector"], status: ["prepared", "in_flight", "settled", "cancelled", "expired"] } },
	"scheduler.executor_selected": { required: ["schemaVersion", "queueEntryId", "taskId", "chosenProviderId", "inputsDigest", "decidedAt", "scoreCount"], allowed: ["schemaVersion", "queueEntryId", "taskId", "chosenProviderId", "inputsDigest", "decidedAt", "scoreCount"], stringFields: ["queueEntryId", "taskId", "chosenProviderId", "inputsDigest", "decidedAt"], integerFields: ["scoreCount"] },
	"scheduler.join_recorded": { required: ["schemaVersion", "joinId", "taskId", "policy"], allowed: ["schemaVersion", "joinId", "taskId", "policy", "settledTaskResultId"], stringFields: ["joinId", "taskId", "policy"], integerFields: [], optionalStringFields: ["settledTaskResultId"], stringValues: { policy: ["require_all", "allow_partial"] } },
	"scheduler.message_posted": { required: ["schemaVersion", "messageId", "threadId", "fromSessionId", "toSessionId", "type", "ack", "revision"], allowed: ["schemaVersion", "messageId", "threadId", "fromSessionId", "toSessionId", "type", "ack", "revision", "taskId", "workflowId", "askId", "transferId", "payloadDigest"], stringFields: ["messageId", "threadId", "fromSessionId", "toSessionId", "type", "ack"], integerFields: ["revision"], optionalStringFields: ["taskId", "workflowId", "askId", "transferId", "payloadDigest"], stringValues: { type: ["handoff.offer", "handoff.answer", "result.ready", "result.reclaim", "wake", "note"], ack: ["none", "required"] } },
	"scheduler.message_acked": { required: ["schemaVersion", "messageId", "threadId", "fromSessionId", "toSessionId", "type", "ack", "revision"], allowed: ["schemaVersion", "messageId", "threadId", "fromSessionId", "toSessionId", "type", "ack", "revision", "taskId", "workflowId", "askId", "transferId", "payloadDigest"], stringFields: ["messageId", "threadId", "fromSessionId", "toSessionId", "type", "ack"], integerFields: ["revision"], optionalStringFields: ["taskId", "workflowId", "askId", "transferId", "payloadDigest"], stringValues: { type: ["handoff.offer", "handoff.answer", "result.ready", "result.reclaim", "wake", "note"], ack: ["none", "required"] } },
	"scheduler.handoff_transitioned": { required: ["schemaVersion", "transferId", "taskId", "fromOwnerId", "toOwnerId", "state", "revision"], allowed: ["schemaVersion", "transferId", "taskId", "fromOwnerId", "toOwnerId", "state", "revision", "reasonSummary"], stringFields: ["transferId", "taskId", "fromOwnerId", "toOwnerId", "state"], integerFields: ["revision"], optionalStringFields: ["reasonSummary"], stringValues: { state: ["offered", "accepted", "rejected", "timed_out", "cancelled"] } },
	"scheduler.wake_scheduled": { required: ["schemaVersion", "wakeId", "workflowId", "dueAt", "revision"], allowed: ["schemaVersion", "wakeId", "workflowId", "dueAt", "revision", "stepId", "firedAt"], stringFields: ["wakeId", "workflowId", "dueAt"], integerFields: ["revision"], optionalStringFields: ["stepId", "firedAt"] },
	"scheduler.wake_fired": { required: ["schemaVersion", "wakeId", "workflowId", "dueAt", "revision"], allowed: ["schemaVersion", "wakeId", "workflowId", "dueAt", "revision", "stepId", "firedAt"], stringFields: ["wakeId", "workflowId", "dueAt"], integerFields: ["revision"], optionalStringFields: ["stepId", "firedAt"] },
	"scheduler.deadlock_detected": { required: ["schemaVersion", "detectionId", "detectedAt", "memberCount", "failedCount"], allowed: ["schemaVersion", "detectionId", "detectedAt", "memberCount", "failedCount"], stringFields: ["detectionId", "detectedAt"], integerFields: ["memberCount", "failedCount"] },
};
function typedEventPayload(category: EventCategoryId, value: unknown): value is FoundationJsonValue {
	try { canonicalFoundationJson(value); } catch { return false; }
	const rule = typedPayloadRules[category]; if (!rule) return true;
	if (typeof value !== "object" || value === null || Array.isArray(value)) return false;
	const record = value as Record<string, unknown>;
	if (Object.keys(record).some((key) => !rule.allowed.includes(key)) || rule.required.some((key) => !(key in record))) return false;
	if (record.schemaVersion !== 1 || rule.stringFields.some((key) => typeof record[key] !== "string" || (record[key] as string).length === 0) || rule.optionalStringFields?.some((key) => record[key] !== undefined && (typeof record[key] !== "string" || (record[key] as string).length === 0)) || rule.integerFields.some((key) => typeof record[key] !== "number" || !Number.isInteger(record[key])) || Object.entries(rule.stringValues ?? {}).some(([key, allowed]) => typeof record[key] !== "string" || !allowed.includes(record[key] as string))) return false;
	if (category === "subagent.lifecycle_transitioned") {
		if (!stringArray(record.ancestorIds, false) || !stringArray(record.bindingEpochIds, false) || record.depth !== record.ancestorIds.length || record.depth === 0 || record.ancestorIds.at(-1) !== record.parentAgentInstanceId || record.ancestorIds.includes(record.childAgentInstanceId as string)) return false;
		const terminal = ["succeeded", "failed", "cancelled", "lost", "closed"].includes(record.status as string);
		if (!canonicalTimestamp(record.createdAt) || (record.terminalAt !== undefined && (!canonicalTimestamp(record.terminalAt) || record.terminalAt < record.createdAt)) || terminal !== (record.terminalAt !== undefined) || (!terminal && (record.attemptReceiptId !== undefined || record.taskResultId !== undefined)) || (record.taskResultId !== undefined && record.attemptReceiptId === undefined) || (record.status === "spawning" && record.revision !== 0)) return false;
	}
	if (category === "subagent.mailbox_message_sent" && (!mailboxCorrelation(record.correlation) || record.correlation.agentInstanceId !== record.toAgentInstanceId || !canonicalTimestamp(record.createdAt))) return false;
	if (category === "subagent.mailbox_message_acknowledged" && !canonicalTimestamp(record.at)) return false;
	if (category === "subagent.worktree_recorded") {
		if (typeof record.baseRef !== "string" || !/^[A-Za-z0-9][A-Za-z0-9._/-]{0,511}$/.test(record.baseRef) || record.baseRef.includes("..") || typeof record.worktreeDigest !== "string" || !/^sha256:[a-f0-9]{64}$/.test(record.worktreeDigest) || (record.cleanedUp !== undefined && typeof record.cleanedUp !== "boolean")) return false;
		if (record.apply !== undefined && (!plain(record.apply) || !exactKeys(record.apply, ["status", "at"]) || !["applied", "conflict", "unknown"].includes(record.apply.status as string) || !canonicalTimestamp(record.apply.at))) return false;
	}
	return true;
}
function entry(category: EventCategoryId): EventCatalogEntry {
	if ((durableCategories as readonly string[]).includes(category)) return { category, class: "durable", schemaVersion: 1, producer: producerFor(category), consumers: ["observer", "rpc", "sdk", "audit"], stableFields: ["category", "eventId", "sequence", "timestamp", "correlation", "payload"], correlationFields: correlationFor(category), replay: "must", retention: "ledger", migration: "additive", redacted: category.startsWith("goal") || category.startsWith("ask") ? ["prompt", "answer", "acceptanceCriteria"] : category === "subagent.mailbox_message_sent" ? ["body"] : category.startsWith("scheduler") ? ["prompt", "payload", "content", "answer"] : [], description: `Durable ${category} ledger event` };
	if ((liveCategories as readonly string[]).includes(category)) return { category, class: "live", schemaVersion: 1, producer: producerFor(category), consumers: ["observer", "rpc", "ui", "sdk"], stableFields: ["category", "eventId", "offset", "timestamp", "correlation", "payload"], correlationFields: correlationFor(category), replay: "never", retention: "ephemeral", migration: "additive", redacted: category === "stream.thinking" ? ["delta"] : [], description: `Live ${category} stream delta` };
	return { category, class: "derived", schemaVersion: 1, producer: producerFor(category), consumers: ["observer", "rpc", "sdk"], stableFields: ["category", "eventId", "sequence", "timestamp", "correlation", "payload"], correlationFields: correlationFor(category), replay: "never", retention: "session", migration: "stable", redacted: [], derivedFrom: derivedFrom[category as DerivedEventCategory], description: `Derived ${category} projection` };
}
const catalog = {} as Record<EventCategoryId, EventCatalogEntry>;
for (const category of [...durableCategories, ...liveCategories, ...derivedCategories]) catalog[category] = entry(category);
export const EVENT_CATALOG: Readonly<Record<EventCategoryId, EventCatalogEntry>> = Object.freeze(catalog);
export function eventCatalogEntries(): readonly EventCatalogEntry[] { return Object.values(EVENT_CATALOG); }
export function lookupEventCategory(category: string): EventCatalogEntry | undefined { return EVENT_CATALOG[category as EventCategoryId]; }
export function eventClass(category: EventCategoryId): EventCategoryClass { return EVENT_CATALOG[category].class; }
export function isDurableEventCategory(category: string): category is DurableEventCategory { return EVENT_CATALOG[category as EventCategoryId]?.class === "durable"; }
export function isLiveEventCategory(category: string): category is LiveEventCategory { return EVENT_CATALOG[category as EventCategoryId]?.class === "live"; }
export function isDerivedEventCategory(category: string): category is DerivedEventCategory { return EVENT_CATALOG[category as EventCategoryId]?.class === "derived"; }
export function partitionEventCatalog(): { durable: readonly DurableEventCatalogEntry[]; live: readonly LiveEventCatalogEntry[]; derived: readonly DerivedEventCatalogEntry[] } {
	const durable: DurableEventCatalogEntry[] = []; const live: LiveEventCatalogEntry[] = []; const derived: DerivedEventCatalogEntry[] = [];
	for (const item of Object.values(EVENT_CATALOG)) { if (item.class === "durable") durable.push(item); else if (item.class === "live") live.push(item); else derived.push(item); }
	return { durable, live, derived };
}

export interface DurableEventEnvelope<TCategory extends DurableEventCategory = DurableEventCategory, TPayload extends FoundationJsonValue = FoundationJsonValue> { schemaVersion: 1; class: "durable"; category: TCategory; eventId: string; streamId: string; sequence: number; timestamp: string; correlation: EventCorrelationRef; payload: TPayload; }
export interface LiveDeltaEnvelope<TCategory extends LiveEventCategory = LiveEventCategory, TPayload extends FoundationJsonValue = FoundationJsonValue> { schemaVersion: 1; class: "live"; category: TCategory; eventId: string; streamId: string; offset: number; timestamp: string; correlation: EventCorrelationRef; payload: TPayload; }
export interface DerivedEventEnvelope<TPayload extends FoundationJsonValue = FoundationJsonValue> { schemaVersion: 1; class: "derived"; category: DerivedEventCategory; eventId: string; streamId: string; sequence: number; timestamp: string; correlation: EventCorrelationRef; payload: TPayload; }
 export type FoundationEventEnvelope = DurableEventEnvelope | LiveDeltaEnvelope | DerivedEventEnvelope;
export interface CreateEventInput<TCorrelation extends EventCorrelationRef = EventCorrelationRef, TPayload extends FoundationJsonValue = FoundationJsonValue> { eventId: string; streamId: string; correlation: TCorrelation; timestamp: string; payload: TPayload; }
export interface CreateDurableEventInput<TCategory extends DurableEventCategory = DurableEventCategory> extends CreateEventInput<EventCorrelationRef, EventPayloadForCategory<TCategory>> { category: TCategory; sequence: number; }
export function createDurableEvent<TCategory extends DurableEventCategory>(input: CreateDurableEventInput<TCategory>): DurableEventEnvelope<TCategory, EventPayloadForCategory<TCategory>> { const envelope: DurableEventEnvelope<TCategory, EventPayloadForCategory<TCategory>> = { schemaVersion: 1, class: "durable", category: input.category, eventId: input.eventId, streamId: input.streamId, sequence: input.sequence, timestamp: input.timestamp, correlation: input.correlation, payload: input.payload }; const checked = validateDurableEvent(envelope); if (!checked.ok) throw checked.error; return envelope; }
export interface CreateLiveDeltaInput<TCategory extends LiveEventCategory = LiveEventCategory> extends CreateEventInput<EventCorrelationRef, FoundationJsonValue> { category: TCategory; offset: number; }
export function createLiveDelta<TCategory extends LiveEventCategory>(input: CreateLiveDeltaInput<TCategory>): LiveDeltaEnvelope<TCategory, FoundationJsonValue> { const envelope: LiveDeltaEnvelope<TCategory, FoundationJsonValue> = { schemaVersion: 1, class: "live", category: input.category, eventId: input.eventId, streamId: input.streamId, offset: input.offset, timestamp: input.timestamp, correlation: input.correlation, payload: input.payload }; const checked = validateLiveDelta(envelope); if (!checked.ok) throw checked.error; return envelope; }
export interface CreateDerivedEventInput<TCategory extends DerivedEventCategory = DerivedEventCategory> extends CreateEventInput<EventCorrelationRef, FoundationJsonValue> { category: TCategory; sequence: number; }
export function createDerivedEvent<TCategory extends DerivedEventCategory>(input: CreateDerivedEventInput<TCategory>): DerivedEventEnvelope<FoundationJsonValue> { const envelope: DerivedEventEnvelope<FoundationJsonValue> = { schemaVersion: 1, class: "derived", category: input.category, eventId: input.eventId, streamId: input.streamId, sequence: input.sequence, timestamp: input.timestamp, correlation: input.correlation, payload: input.payload }; const checked = validateDerivedEvent(envelope); if (!checked.ok) throw checked.error; return envelope; }

export type EventEnvelopeErrorCode = "event_envelope_unknown_category" | "event_envelope_class_mismatch" | "event_envelope_invalid_schema_version" | "event_envelope_invalid_sequence" | "event_envelope_invalid_shape";
export class EventEnvelopeError extends Error { readonly _tag = "EventEnvelopeErrorV1" as const; readonly code: EventEnvelopeErrorCode; constructor(code: EventEnvelopeErrorCode, message: string) { super(String(message).replace(/https?:\/\/[^\s]+/g, "[redacted-url]")); this.name = "EventEnvelopeErrorV1"; this.code = code; } }
function plain(value: unknown): value is Record<string, unknown> { return typeof value === "object" && value !== null && !Array.isArray(value); }
function stringValue(value: unknown): value is string { return typeof value === "string" && value.length > 0; }
function stringArray(value: unknown, allowEmpty: boolean): value is string[] { return Array.isArray(value) && (allowEmpty || value.length > 0) && value.every((item) => stringValue(item)) && new Set(value).size === value.length; }
function canonicalTimestamp(value: unknown): value is string { if (typeof value !== "string" || !/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}\.\d{3}Z$/.test(value)) return false; const parsed = new Date(value); return Number.isFinite(parsed.getTime()) && parsed.toISOString() === value; }
function mailboxCorrelation(value: unknown): value is { sessionId: string; laneId: string; taskId: string; attemptId: string; agentInstanceId: string } {
	return plain(value) && exactKeys(value, ["sessionId", "laneId", "taskId", "attemptId", "agentInstanceId"]) && stringValue(value.sessionId) && stringValue(value.laneId) && stringValue(value.taskId) && stringValue(value.attemptId) && stringValue(value.agentInstanceId);
}
function jsonValue(value: unknown): value is FoundationJsonValue {
	try { canonicalFoundationJson(value); return true; } catch { return false; }
}
export function validateEventPayloadForCategory(category: EventCategoryId, value: unknown): value is FoundationJsonValue { return typedEventPayload(category, value); }
const correlationKeys: readonly (keyof EventCorrelationRef)[] = ["sessionId", "laneId", "operationId", "workerId", "runId", "turnId", "stepId", "toolCallId", "roleId", "roleRevisionId", "modelProfileId", "modelProfileRevisionId", "bindingId", "bindingEpochId", "attemptId", "attemptReceiptId", "workerReceiptId", "agentInstanceId", "goalId", "planId", "stageId", "taskId", "dispatchId", "taskResultId", "runReceiptId", "workflowId", "askId", "artifactId", "receiptId"];
function correlation(value: unknown): value is EventCorrelationRef {
	if (!plain(value) || !stringValue(value.sessionId) || !Object.keys(value).every((key) => correlationKeys.includes(key as keyof EventCorrelationRef))) return false;
	return Object.values(value).every((item) => stringValue(item));
}
function typedEventCorrelation(category: DurableEventCategory, correlationValue: EventCorrelationRef, payloadValue: FoundationJsonValue): boolean {
	if (category !== "worker.lifecycle_transitioned" && category !== "worker.operation_recorded" && !category.startsWith("subagent.") && !category.startsWith("scheduler.")) return true;
	if (!plain(payloadValue)) return false;
	if (category.startsWith("scheduler.")) {
		const identityFields = ["sessionId", "taskId", "dispatchId", "attemptId", "workflowId", "askId"] as const;
		return identityFields.every((field) => payloadValue[field] === undefined || correlationValue[field] === payloadValue[field]);
	}
	if (category === "worker.lifecycle_transitioned" || category === "worker.operation_recorded") {
		if (correlationValue.sessionId !== payloadValue.sessionId || correlationValue.laneId !== payloadValue.laneId || correlationValue.workerId !== payloadValue.workerId) return false;
		if (category === "worker.operation_recorded") return correlationValue.operationId === payloadValue.operationId;
		const operationId = payloadValue.operationId ?? payloadValue.activeOperationId;
		return operationId === undefined || correlationValue.operationId === operationId;
	}
	if (!stringValue(correlationValue.laneId) || !stringValue(correlationValue.agentInstanceId) || !stringValue(correlationValue.attemptId)) return false;
	if (category === "subagent.lifecycle_transitioned") return stringValue(correlationValue.taskId) && stringValue(correlationValue.dispatchId) && correlationValue.agentInstanceId === payloadValue.childAgentInstanceId && correlationValue.taskId === payloadValue.taskId && correlationValue.dispatchId === payloadValue.dispatchId && correlationValue.attemptId === payloadValue.attemptId;
	if (category === "subagent.mailbox_message_sent") return mailboxCorrelation(payloadValue.correlation) && correlationValue.sessionId === payloadValue.correlation.sessionId && correlationValue.laneId === payloadValue.correlation.laneId && correlationValue.taskId === payloadValue.correlation.taskId && correlationValue.attemptId === payloadValue.correlation.attemptId && correlationValue.agentInstanceId === payloadValue.correlation.agentInstanceId && correlationValue.agentInstanceId === payloadValue.toAgentInstanceId;
	if (category === "subagent.mailbox_message_acknowledged") return stringValue(correlationValue.taskId) && correlationValue.agentInstanceId === payloadValue.toAgentInstanceId && correlationValue.attemptId === payloadValue.byAttemptId;
	return correlationValue.agentInstanceId === payloadValue.childAgentInstanceId && correlationValue.attemptId === payloadValue.attemptId;
}
function exactKeys(value: Record<string, unknown>, allowed: readonly string[]): boolean { return Object.keys(value).every((key) => allowed.includes(key)); }
export function validateDurableEvent(value: unknown): ResultValue<DurableEventEnvelope, EventEnvelopeError> {
	if (!plain(value) || !exactKeys(value, ["schemaVersion", "class", "category", "eventId", "streamId", "sequence", "timestamp", "correlation", "payload"])) return Result.err(new EventEnvelopeError("event_envelope_invalid_shape", "durable event has an invalid exact shape"));
	if (value.schemaVersion !== 1) return Result.err(new EventEnvelopeError("event_envelope_invalid_schema_version", "unsupported event schema version"));
	if (typeof value.category !== "string" || !isDurableEventCategory(value.category)) return Result.err(new EventEnvelopeError("event_envelope_unknown_category", "unknown durable event category"));
	if (value.class !== "durable") return Result.err(new EventEnvelopeError("event_envelope_class_mismatch", "durable category must use class durable"));
	if (!stringValue(value.eventId) || !stringValue(value.streamId) || !stringValue(value.timestamp) || typeof value.sequence !== "number" || !Number.isInteger(value.sequence) || value.sequence < 0 || !correlation(value.correlation) || !jsonValue(value.payload) || !typedEventPayload(value.category, value.payload) || !typedEventCorrelation(value.category, value.correlation, value.payload)) return Result.err(new EventEnvelopeError("event_envelope_invalid_shape", "durable event fields are invalid"));
	return Result.ok({ schemaVersion: 1, class: "durable", category: value.category as DurableEventCategory, eventId: value.eventId as string, streamId: value.streamId as string, sequence: value.sequence as number, timestamp: value.timestamp as string, correlation: value.correlation as EventCorrelationRef, payload: value.payload as FoundationJsonValue });
}
export function validateLiveDelta(value: unknown): ResultValue<LiveDeltaEnvelope, EventEnvelopeError> {
	if (!plain(value) || !exactKeys(value, ["schemaVersion", "class", "category", "eventId", "streamId", "offset", "timestamp", "correlation", "payload"])) return Result.err(new EventEnvelopeError("event_envelope_invalid_shape", "live event has an invalid exact shape"));
	if (value.schemaVersion !== 1) return Result.err(new EventEnvelopeError("event_envelope_invalid_schema_version", "unsupported event schema version"));
	if (typeof value.category !== "string" || !isLiveEventCategory(value.category)) return Result.err(new EventEnvelopeError("event_envelope_unknown_category", "unknown live event category"));
	if (value.class !== "live") return Result.err(new EventEnvelopeError("event_envelope_class_mismatch", "live category must use class live"));
	if (!stringValue(value.eventId) || !stringValue(value.streamId) || !stringValue(value.timestamp) || typeof value.offset !== "number" || !Number.isInteger(value.offset) || value.offset < 0 || !correlation(value.correlation) || !jsonValue(value.payload) || !typedEventPayload(value.category, value.payload)) return Result.err(new EventEnvelopeError("event_envelope_invalid_shape", "live event fields are invalid"));
	return Result.ok({ schemaVersion: 1, class: "live", category: value.category as LiveEventCategory, eventId: value.eventId as string, streamId: value.streamId as string, offset: value.offset as number, timestamp: value.timestamp as string, correlation: value.correlation as EventCorrelationRef, payload: value.payload as FoundationJsonValue });
}
export function validateDerivedEvent(value: unknown): ResultValue<DerivedEventEnvelope, EventEnvelopeError> {
	if (!plain(value) || !exactKeys(value, ["schemaVersion", "class", "category", "eventId", "streamId", "sequence", "timestamp", "correlation", "payload"])) return Result.err(new EventEnvelopeError("event_envelope_invalid_shape", "derived event has an invalid exact shape"));
	if (value.schemaVersion !== 1) return Result.err(new EventEnvelopeError("event_envelope_invalid_schema_version", "unsupported event schema version"));
	if (typeof value.category !== "string" || !isDerivedEventCategory(value.category)) return Result.err(new EventEnvelopeError("event_envelope_unknown_category", "unknown derived event category"));
	if (value.class !== "derived") return Result.err(new EventEnvelopeError("event_envelope_class_mismatch", "derived category must use class derived"));
	if (!stringValue(value.eventId) || !stringValue(value.streamId) || !stringValue(value.timestamp) || typeof value.sequence !== "number" || !Number.isInteger(value.sequence) || value.sequence < 0 || !correlation(value.correlation) || !jsonValue(value.payload) || !typedEventPayload(value.category, value.payload)) return Result.err(new EventEnvelopeError("event_envelope_invalid_shape", "derived event fields are invalid"));
	return Result.ok({ schemaVersion: 1, class: "derived", category: value.category as DerivedEventCategory, eventId: value.eventId as string, streamId: value.streamId as string, sequence: value.sequence as number, timestamp: value.timestamp as string, correlation: value.correlation as EventCorrelationRef, payload: value.payload as FoundationJsonValue });
}
export function redactEventValue(value: FoundationJsonValue, extraRedacted: ReadonlySet<string>): FoundationJsonValue { const redacted = redactProjection(value) as FoundationJsonValue; if (typeof redacted !== "object" || redacted === null || Array.isArray(redacted)) return redacted; const copy: Record<string, FoundationJsonValue> = { ...redacted }; for (const key of extraRedacted) if (key in copy) copy[key] = "[redacted]"; return copy; }
export interface EventPublicProjection { schemaVersion: 1; class: EventCategoryClass; category: EventCategoryId; eventId: string; streamId: string; sequence?: number; offset?: number; timestamp: string; correlation: EventCorrelationRef; payload: FoundationJsonValue; }
export function projectEventEnvelope(envelope: FoundationEventEnvelope): EventPublicProjection { const entry = EVENT_CATALOG[envelope.category]; const redactedPayload = redactEventValue(envelope.payload, new Set(entry.redacted)); const payload = (envelope.category === "subagent.mailbox_message_sent" || envelope.category === "subagent.mailbox_message_acknowledged") && plain(envelope.payload) && plain(redactedPayload) && stringValue(envelope.payload.messageId) ? { ...redactedPayload, messageId: envelope.payload.messageId } : redactedPayload; const base = { schemaVersion: 1 as const, class: envelope.class, category: envelope.category, eventId: envelope.eventId, streamId: envelope.streamId, timestamp: envelope.timestamp, correlation: envelope.correlation, payload }; return envelope.class === "live" ? { ...base, offset: envelope.offset } : { ...base, sequence: envelope.sequence }; }
export function serializeDurableEvent(value: DurableEventEnvelope): string { const checked = validateDurableEvent(value); if (!checked.ok) throw checked.error; return stableEventJson(checked.value); }
export function serializeLiveDelta(value: LiveDeltaEnvelope): string { const checked = validateLiveDelta(value); if (!checked.ok) throw checked.error; return stableEventJson(checked.value); }
export function serializeDerivedEvent(value: DerivedEventEnvelope): string { const checked = validateDerivedEvent(value); if (!checked.ok) throw checked.error; return stableEventJson(checked.value); }
export function parseDurableEvent(text: string): ResultValue<DurableEventEnvelope, EventEnvelopeError> { try { return validateDurableEvent(JSON.parse(text) as unknown); } catch { return Result.err(new EventEnvelopeError("event_envelope_invalid_shape", "event payload is not valid JSON")); } }
export function parseLiveDelta(text: string): ResultValue<LiveDeltaEnvelope, EventEnvelopeError> { try { return validateLiveDelta(JSON.parse(text) as unknown); } catch { return Result.err(new EventEnvelopeError("event_envelope_invalid_shape", "event payload is not valid JSON")); } }
export function parseDerivedEvent(text: string): ResultValue<DerivedEventEnvelope, EventEnvelopeError> { try { return validateDerivedEvent(JSON.parse(text) as unknown); } catch { return Result.err(new EventEnvelopeError("event_envelope_invalid_shape", "event payload is not valid JSON")); } }
function stableEventJson(value: FoundationEventEnvelope): string { if (value.class === "durable") return JSON.stringify({ ...value, payload: value.payload }); if (value.class === "live") return JSON.stringify({ ...value, payload: value.payload }); return JSON.stringify({ ...value, payload: value.payload }); }
