import { Result, type Result as ResultValue } from "../result.ts";
import { Type } from "typebox";
import { BudgetUsageV1Schema, BudgetV1Schema, type BudgetUsageV1, type BudgetV1 } from "./budget.ts";
import { FoundationError, type PublicExecutionErrorV1 } from "./errors.ts";
import { ArtifactRefV1Schema, type ArtifactDescriptorV1, type ArtifactRefV1, RevisionReferenceV1Schema, type RevisionReferenceV1 } from "./reference.ts";
import type { SideEffectStateV1 } from "./side-effect.ts";
import { AgentBindingV1Schema, AgentInstanceV1Schema, BindingEpochV1Schema, ModelProfileV1Schema, RoleRevisionV1Schema, type AgentBindingV1, type AgentInstanceV1, type BindingEpochV1, type ModelProfileV1, type RoleRevisionV1 } from "./role.ts";
import { AttemptV1Schema, type AttemptV1, type DispatchV1, SpawnAgentIntentV1Schema, type SpawnAgentIntentV1, TaskEnvelopeV1Schema, type TaskEnvelopeV1 } from "./task.ts";
import { PublicExecutionErrorV1Schema, type AttemptReceiptV1, type WorkerReceiptV1 } from "./results.ts";
import type { FoundationEventEnvelopeV1, FoundationJsonValue } from "./event-catalog.ts";
import { canonicalFoundationJson } from "./identity.ts";
import { FoundationJsonValueSchema, parseExactShape, serializeExactShape, validateExactShape } from "./schema.ts";

export type FoundationProviderClassV1 = "operation_worker" | "scheduler" | "task_executor" | "agent" | "external_connector" | "gateway" | "store" | "quota" | "transport" | "observer";
export const PROVIDER_KINDS = ["model", "tool", "sandbox", "operation", "external"] as const;
export interface ExecutionProviderDescriptorV1 { schemaVersion: 1; providerId: string; providerClass: "operation_worker" | "scheduler" | "task_executor" | "agent" | "external_connector"; }
export interface FoundationProviderCapabilityV1 { schemaVersion: 1; id: string; version: number; }
export interface FoundationProviderV1 { readonly schemaVersion: 1; readonly providerId: string; readonly providerClass: FoundationProviderClassV1; capabilities(): Promise<readonly FoundationProviderCapabilityV1[]>; dispose(): Promise<void>; }
export interface SandboxOperationRequestV1 { schemaVersion: 1; operationId: string; taskId?: string; dispatchId?: string; attemptId?: string; credentialTargets?: readonly string[]; workspace?: string; deadlineAt?: number; }
export interface SandboxOperationProvider extends FoundationProviderV1 { readonly providerClass: "operation_worker"; start(request: SandboxOperationRequestV1, options?: { signal?: AbortSignal }): Promise<Result<WorkerReceiptV1, FoundationError>>; cancel(operationId: string): Promise<Result<void, FoundationError>>; }
export type OperationWorkerProviderV1 = SandboxOperationProvider;
export interface ChildSpawnRequestV1 { schemaVersion: 1; spawnId: string; parentSpawn?: SpawnAgentIntentV1; taskEnvelope: TaskEnvelopeV1; roleRevision: RoleRevisionV1; modelProfile: ModelProfileV1; parentAttemptId?: string; parentAgentInstanceId?: string; forkScope: "none" | "all" | "recent_n" | "task_package"; recentN?: number; taskPackageRef?: string; }
export interface ChildSpawnResultV1 { schemaVersion: 1; attempt: AttemptV1; agentInstance: AgentInstanceV1; initialBindingEpoch: BindingEpochV1; }
export interface ChildAgentProvider extends FoundationProviderV1 { readonly providerClass: "agent"; spawn(request: ChildSpawnRequestV1, options?: { signal?: AbortSignal }): Promise<Result<ChildSpawnResultV1, FoundationError>>; resume(attemptId: string, options?: { signal?: AbortSignal }): Promise<Result<AttemptReceiptV1, FoundationError>>; cancel(attemptId: string): Promise<Result<void, FoundationError>>; }
export type AgentProviderV1 = ChildAgentProvider;
/** A TaskExecutor creates Attempts and settles AttemptReceipts; Operation Workers are excluded. */
export interface TaskExecutorProvider extends FoundationProviderV1 { readonly providerClass: "scheduler" | "task_executor" | "agent" | "external_connector"; createAttempt(dispatch: DispatchV1, binding: AgentBindingV1): Promise<Result<AttemptV1, FoundationError>>; runAttempt(attempt: AttemptV1, options?: { signal?: AbortSignal }): Promise<Result<AttemptReceiptV1, FoundationError>>; cancelAttempt(attemptId: string): Promise<Result<void, FoundationError>>; }
/** Explicit line-12B non-agent scheduler surface. It cannot carry an AgentInstance. */
export interface SchedulerTaskExecutorProvider extends TaskExecutorProvider { readonly providerClass: "scheduler" | "task_executor"; }
export interface ConnectorCapabilitySnapshotV1 { schemaVersion: 1; providerId: string; protocol: string; capabilityVersion: number; resumeSupported: boolean; modelAccess: "none" | "agent_owned" | "aos_gateway"; toolAccess?: readonly string[]; }
export interface ExternalAgentStartRequestV1 { schemaVersion: 1; requestId: string; task: TaskEnvelopeV1; binding: AgentBindingV1; translatedConfig?: FoundationJsonValue; deadlineAt?: number; }
export interface ExternalAgentConnector extends FoundationProviderV1 { readonly providerClass: "external_connector"; probe(): Promise<Result<ConnectorCapabilitySnapshotV1, FoundationError>>; start(request: ExternalAgentStartRequestV1, options?: { signal?: AbortSignal }): Promise<Result<AttemptV1, FoundationError>>; resume(attemptId: string): Promise<Result<AttemptReceiptV1, FoundationError>>; cancel(attemptId: string): Promise<Result<void, FoundationError>>; }
export interface ToolGatewayContextV1 { schemaVersion: 1; bindingId: string; bindingEpochId: string; taskId: string; attemptId?: string; agentInstanceId?: string; }
export interface ToolGatewayRequestV1 { schemaVersion: 1; toolCallId: string; toolName: string; namespace?: string; originalArguments: FoundationJsonValue; context: ToolGatewayContextV1; idempotencyKey?: string; deadlineAt?: number; }
export interface ToolExecutionResultV1 { schemaVersion: 1; toolCallId: string; toolName: string; ok: boolean; sideEffectState: SideEffectStateV1; artifacts?: readonly ArtifactRefV1[]; error?: PublicExecutionErrorV1; toolReceiptRef?: string; }
export interface ToolGateway extends FoundationProviderV1 { readonly providerClass: "gateway"; execute(request: ToolGatewayRequestV1, options?: { signal?: AbortSignal }): Promise<Result<ToolExecutionResultV1, FoundationError>>; }
export interface ScopedModelRequestV1 { schemaVersion: 1; requestId: string; modelProfileRevision: RevisionReferenceV1; bindingEpochId: string; taskId: string; attemptId?: string; agentInstanceId?: string; input: FoundationJsonValue; }
export interface ScopedModelResultV1 { schemaVersion: 1; requestId: string; usage: BudgetUsageV1; stopReason: "stop" | "length" | "tool_use" | "error" | "aborted"; error?: PublicExecutionErrorV1; }
export interface ScopedModelGateway extends FoundationProviderV1 { readonly providerClass: "gateway"; stream(request: ScopedModelRequestV1, options?: { signal?: AbortSignal }): Promise<Result<ScopedModelResultV1, FoundationError>>; }
export interface ArtifactPutResultV1 { schemaVersion: 1; ref: string; sizeBytes: number; }
export interface ArtifactVerifyResultV1 { schemaVersion: 1; digestValid: boolean; }
export interface ArtifactStoreProvider extends FoundationProviderV1 { readonly providerClass: "store"; put(descriptor: ArtifactDescriptorV1, data: Uint8Array): Promise<Result<ArtifactPutResultV1, FoundationError>>; get(ref: string): Promise<Result<Uint8Array, FoundationError>>; verify(artifactId: string): Promise<Result<ArtifactVerifyResultV1, FoundationError>>; delete(artifactId: string): Promise<Result<void, FoundationError>>; }
export interface QuotaAttributionV1 { schemaVersion: 1; taskId: string; goalId?: string; runId?: string; attemptId?: string; agentInstanceId?: string; providerId: string; ownerKind: "host" | "operation_worker" | "agent_executor" | "external_connector"; }
export interface QuotaReservationV1 { schemaVersion: 1; reservationId: string; attribution: QuotaAttributionV1; budget: BudgetV1; grantedAt: string; expiresAt?: string; }
export interface QuotaProvider extends FoundationProviderV1 { readonly providerClass: "quota"; reserve(attribution: QuotaAttributionV1, budget: BudgetV1, options?: { signal?: AbortSignal }): Promise<Result<QuotaReservationV1, FoundationError>>; settle(reservation: QuotaReservationV1, usage: BudgetUsageV1): Promise<Result<BudgetUsageV1, FoundationError>>; }
export interface TransportInitializeResultV1 { schemaVersion: 1; protocolVersion: 1; features: readonly string[]; }
export interface TransportObserverCursorV1 { schemaVersion: 1; sessionId: string; sequence: number; catalogVersion: 1; }
export interface TransportAdapter extends FoundationProviderV1 { readonly providerClass: "transport"; initialize(): Promise<Result<TransportInitializeResultV1, FoundationError>>; attach(sessionId: string, cursor?: TransportObserverCursorV1): Promise<Result<TransportObserverCursorV1, FoundationError>>; observe(from: TransportObserverCursorV1, onEvent: (event: FoundationEventEnvelopeV1) => void, options?: { signal?: AbortSignal }): Promise<Result<void, FoundationError>>; }
export interface ProductTimelineEntryV1 { schemaVersion: 1; sequence: number; kind: "ask" | "task_result" | "run_receipt" | "artifact"; ref: { type: string; id: string }; recordedAt: string; }
export interface ProductAcceptanceFactV1 { schemaVersion: 1; factId: string; outcome: string; }
export interface ProductObserverAdapter extends FoundationProviderV1 { readonly providerClass: "observer"; operatorIntents(sessionId: string, after?: number): Promise<Result<readonly ProductTimelineEntryV1[], FoundationError>>; acceptanceFacts(taskId: string): Promise<Result<readonly ProductAcceptanceFactV1[], FoundationError>>; timeline(runId: string): Promise<Result<readonly ProductTimelineEntryV1[], FoundationError>>; }

/** Boundary implementations call this before emitting any provider payload. */
export function validateProviderJsonV1(value: unknown): value is FoundationJsonValue {
	try { canonicalFoundationJson(value); return true; } catch { return false; }
}

export const SandboxOperationRequestV1Schema = Type.Object({ schemaVersion: Type.Literal(1), operationId: Type.String({ minLength: 1 }), taskId: Type.Optional(Type.String({ minLength: 1 })), dispatchId: Type.Optional(Type.String({ minLength: 1 })), attemptId: Type.Optional(Type.String({ minLength: 1 })), credentialTargets: Type.Optional(Type.Array(Type.String({ minLength: 1 }))), workspace: Type.Optional(Type.String({ minLength: 1 })), deadlineAt: Type.Optional(Type.Number({ minimum: 0 })) }, { additionalProperties: false });
export const FoundationProviderCapabilityV1Schema = Type.Object({ schemaVersion: Type.Literal(1), id: Type.String({ minLength: 1 }), version: Type.Integer({ minimum: 1 }) }, { additionalProperties: false });
export const ConnectorCapabilitySnapshotV1Schema = Type.Object({ schemaVersion: Type.Literal(1), providerId: Type.String({ minLength: 1 }), protocol: Type.String({ minLength: 1 }), capabilityVersion: Type.Integer({ minimum: 1 }), resumeSupported: Type.Boolean(), modelAccess: Type.Union([Type.Literal("none"), Type.Literal("agent_owned"), Type.Literal("aos_gateway")]), toolAccess: Type.Optional(Type.Array(Type.String({ minLength: 1 }))) }, { additionalProperties: false });
export const ChildSpawnRequestV1Schema = Type.Object({ schemaVersion: Type.Literal(1), spawnId: Type.String({ minLength: 1 }), parentSpawn: Type.Optional(SpawnAgentIntentV1Schema), taskEnvelope: TaskEnvelopeV1Schema, roleRevision: RoleRevisionV1Schema, modelProfile: ModelProfileV1Schema, parentAttemptId: Type.Optional(Type.String({ minLength: 1 })), parentAgentInstanceId: Type.Optional(Type.String({ minLength: 1 })), forkScope: Type.Union([Type.Literal("none"), Type.Literal("all"), Type.Literal("recent_n"), Type.Literal("task_package")]), recentN: Type.Optional(Type.Integer({ minimum: 1 })), taskPackageRef: Type.Optional(Type.String({ minLength: 1 })) }, { additionalProperties: false });
export const ExternalAgentStartRequestV1Schema = Type.Object({ schemaVersion: Type.Literal(1), requestId: Type.String({ minLength: 1 }), task: TaskEnvelopeV1Schema, binding: AgentBindingV1Schema, translatedConfig: Type.Optional(FoundationJsonValueSchema), deadlineAt: Type.Optional(Type.Number({ minimum: 0 })) }, { additionalProperties: false });
export const ToolGatewayContextV1Schema = Type.Object({ schemaVersion: Type.Literal(1), bindingId: Type.String({ minLength: 1 }), bindingEpochId: Type.String({ minLength: 1 }), taskId: Type.String({ minLength: 1 }), attemptId: Type.Optional(Type.String({ minLength: 1 })), agentInstanceId: Type.Optional(Type.String({ minLength: 1 })) }, { additionalProperties: false });
export const ToolGatewayRequestV1Schema = Type.Object({ schemaVersion: Type.Literal(1), toolCallId: Type.String({ minLength: 1 }), toolName: Type.String({ minLength: 1 }), namespace: Type.Optional(Type.String({ minLength: 1 })), originalArguments: FoundationJsonValueSchema, context: ToolGatewayContextV1Schema, idempotencyKey: Type.Optional(Type.String({ minLength: 1 })), deadlineAt: Type.Optional(Type.Number({ minimum: 0 })) }, { additionalProperties: false });
export const ScopedModelRequestV1Schema = Type.Object({ schemaVersion: Type.Literal(1), requestId: Type.String({ minLength: 1 }), modelProfileRevision: RevisionReferenceV1Schema, bindingEpochId: Type.String({ minLength: 1 }), taskId: Type.String({ minLength: 1 }), attemptId: Type.Optional(Type.String({ minLength: 1 })), agentInstanceId: Type.Optional(Type.String({ minLength: 1 })), input: FoundationJsonValueSchema }, { additionalProperties: false });
export const TransportObserverCursorV1Schema = Type.Object({ schemaVersion: Type.Literal(1), sessionId: Type.String({ minLength: 1 }), sequence: Type.Integer({ minimum: 0 }), catalogVersion: Type.Literal(1) }, { additionalProperties: false });
export const TransportInitializeResultV1Schema = Type.Object({ schemaVersion: Type.Literal(1), protocolVersion: Type.Literal(1), features: Type.Array(Type.String({ minLength: 1 })) }, { additionalProperties: false });
export const ChildSpawnResultV1Schema = Type.Object({ schemaVersion: Type.Literal(1), attempt: AttemptV1Schema, agentInstance: AgentInstanceV1Schema, initialBindingEpoch: BindingEpochV1Schema }, { additionalProperties: false });
export const ToolExecutionResultV1Schema = Type.Object({ schemaVersion: Type.Literal(1), toolCallId: Type.String({ minLength: 1 }), toolName: Type.String({ minLength: 1 }), ok: Type.Boolean(), sideEffectState: Type.Union([Type.Literal("none"), Type.Literal("unknown"), Type.Literal("side_effect_unknown")]), artifacts: Type.Optional(Type.Array(ArtifactRefV1Schema)), error: Type.Optional(PublicExecutionErrorV1Schema), toolReceiptRef: Type.Optional(Type.String({ minLength: 1 })) }, { additionalProperties: false });
export const ScopedModelResultV1Schema = Type.Object({ schemaVersion: Type.Literal(1), requestId: Type.String({ minLength: 1 }), usage: BudgetUsageV1Schema, stopReason: Type.Union([Type.Literal("stop"), Type.Literal("length"), Type.Literal("tool_use"), Type.Literal("error"), Type.Literal("aborted")]), error: Type.Optional(PublicExecutionErrorV1Schema) }, { additionalProperties: false });
export const ArtifactPutResultV1Schema = Type.Object({ schemaVersion: Type.Literal(1), ref: Type.String({ minLength: 1 }), sizeBytes: Type.Integer({ minimum: 0 }) }, { additionalProperties: false });
export const ArtifactVerifyResultV1Schema = Type.Object({ schemaVersion: Type.Literal(1), digestValid: Type.Boolean() }, { additionalProperties: false });
export const QuotaAttributionV1Schema = Type.Object({ schemaVersion: Type.Literal(1), taskId: Type.String({ minLength: 1 }), goalId: Type.Optional(Type.String({ minLength: 1 })), runId: Type.Optional(Type.String({ minLength: 1 })), attemptId: Type.Optional(Type.String({ minLength: 1 })), agentInstanceId: Type.Optional(Type.String({ minLength: 1 })), providerId: Type.String({ minLength: 1 }), ownerKind: Type.Union([Type.Literal("host"), Type.Literal("operation_worker"), Type.Literal("agent_executor"), Type.Literal("external_connector")]) }, { additionalProperties: false });
export const QuotaReservationV1Schema = Type.Object({ schemaVersion: Type.Literal(1), reservationId: Type.String({ minLength: 1 }), attribution: QuotaAttributionV1Schema, budget: BudgetV1Schema, grantedAt: Type.String({ minLength: 1 }), expiresAt: Type.Optional(Type.String({ minLength: 1 })) }, { additionalProperties: false });
export const ProductTimelineEntryV1Schema = Type.Object({ schemaVersion: Type.Literal(1), sequence: Type.Integer({ minimum: 0 }), kind: Type.Union([Type.Literal("ask"), Type.Literal("task_result"), Type.Literal("run_receipt"), Type.Literal("artifact")]), ref: Type.Object({ type: Type.String({ minLength: 1 }), id: Type.String({ minLength: 1 }) }, { additionalProperties: false }), recordedAt: Type.String({ minLength: 1 }) }, { additionalProperties: false });
export const ProductAcceptanceFactV1Schema = Type.Object({ schemaVersion: Type.Literal(1), factId: Type.String({ minLength: 1 }), outcome: Type.String({ minLength: 1 }) }, { additionalProperties: false });
export const ExecutionProviderDescriptorV1Schema = Type.Object({ schemaVersion: Type.Literal(1), providerId: Type.String({ minLength: 1 }), providerClass: Type.Union([Type.Literal("operation_worker"), Type.Literal("scheduler"), Type.Literal("task_executor"), Type.Literal("agent"), Type.Literal("external_connector")]) }, { additionalProperties: false });
function validateProviderBoundary<T>(schema: Parameters<typeof validateExactShape>[0], value: unknown, kind: string, jsonFields: readonly string[] = []): ResultValue<T, FoundationError> {
	const record = value !== null && typeof value === "object" && !Array.isArray(value) ? value as Record<string, unknown> : undefined;
	if (record !== undefined && jsonFields.some((field) => record[field] !== undefined && !validateProviderJsonV1(record[field]))) return Result.err(new FoundationError("foundation_schema_invalid_shape", `${kind} contains a non-JSON payload`));
	return validateExactShape<T>(schema, value, kind);
}
export function validateSandboxOperationRequestV1(value: unknown): ResultValue<SandboxOperationRequestV1, FoundationError> { return validateProviderBoundary<SandboxOperationRequestV1>(SandboxOperationRequestV1Schema, value, "sandbox_operation_request"); }
export function validateFoundationProviderCapabilityV1(value: unknown): ResultValue<FoundationProviderCapabilityV1, FoundationError> { return validateProviderBoundary<FoundationProviderCapabilityV1>(FoundationProviderCapabilityV1Schema, value, "provider_capability"); }
export function validateExecutionProviderDescriptorV1(value: unknown): ResultValue<ExecutionProviderDescriptorV1, FoundationError> { return validateProviderBoundary<ExecutionProviderDescriptorV1>(ExecutionProviderDescriptorV1Schema, value, "execution_provider_descriptor"); }
export function serializeSandboxOperationRequestV1(value: SandboxOperationRequestV1): string { return serializeExactShape(SandboxOperationRequestV1Schema, value, "sandbox_operation_request"); }
export function parseSandboxOperationRequestV1(text: string): ResultValue<SandboxOperationRequestV1, FoundationError> { return parseExactShape(SandboxOperationRequestV1Schema, text, "sandbox_operation_request"); }
export function validateConnectorCapabilitySnapshotV1(value: unknown): ResultValue<ConnectorCapabilitySnapshotV1, FoundationError> { return validateProviderBoundary<ConnectorCapabilitySnapshotV1>(ConnectorCapabilitySnapshotV1Schema, value, "connector_capability_snapshot"); }
export function validateChildSpawnRequestV1(value: unknown): ResultValue<ChildSpawnRequestV1, FoundationError> { return validateProviderBoundary<ChildSpawnRequestV1>(ChildSpawnRequestV1Schema, value, "child_spawn_request"); }
export function validateExternalAgentStartRequestV1(value: unknown): ResultValue<ExternalAgentStartRequestV1, FoundationError> { return validateProviderBoundary<ExternalAgentStartRequestV1>(ExternalAgentStartRequestV1Schema, value, "external_agent_start_request", ["task", "binding", "translatedConfig"]); }
export function validateToolGatewayRequestV1(value: unknown): ResultValue<ToolGatewayRequestV1, FoundationError> { return validateProviderBoundary<ToolGatewayRequestV1>(ToolGatewayRequestV1Schema, value, "tool_gateway_request", ["originalArguments"]); }
export function validateScopedModelRequestV1(value: unknown): ResultValue<ScopedModelRequestV1, FoundationError> { return validateProviderBoundary<ScopedModelRequestV1>(ScopedModelRequestV1Schema, value, "scoped_model_request", ["modelProfileRevision", "input"]); }
export function validateChildSpawnResultV1(value: unknown): ResultValue<ChildSpawnResultV1, FoundationError> { return validateProviderBoundary<ChildSpawnResultV1>(ChildSpawnResultV1Schema, value, "child_spawn_result"); }
export function validateToolExecutionResultV1(value: unknown): ResultValue<ToolExecutionResultV1, FoundationError> { return validateProviderBoundary<ToolExecutionResultV1>(ToolExecutionResultV1Schema, value, "tool_execution_result"); }
export function validateScopedModelResultV1(value: unknown): ResultValue<ScopedModelResultV1, FoundationError> { return validateProviderBoundary<ScopedModelResultV1>(ScopedModelResultV1Schema, value, "scoped_model_result"); }
export function validateArtifactPutResultV1(value: unknown): ResultValue<ArtifactPutResultV1, FoundationError> { return validateProviderBoundary<ArtifactPutResultV1>(ArtifactPutResultV1Schema, value, "artifact_put_result"); }
export function validateArtifactVerifyResultV1(value: unknown): ResultValue<ArtifactVerifyResultV1, FoundationError> { return validateProviderBoundary<ArtifactVerifyResultV1>(ArtifactVerifyResultV1Schema, value, "artifact_verify_result"); }
export function validateQuotaAttributionV1(value: unknown): ResultValue<QuotaAttributionV1, FoundationError> { return validateProviderBoundary<QuotaAttributionV1>(QuotaAttributionV1Schema, value, "quota_attribution"); }
export function validateQuotaReservationV1(value: unknown): ResultValue<QuotaReservationV1, FoundationError> { return validateProviderBoundary<QuotaReservationV1>(QuotaReservationV1Schema, value, "quota_reservation"); }
export function validateProductTimelineEntryV1(value: unknown): ResultValue<ProductTimelineEntryV1, FoundationError> { return validateProviderBoundary<ProductTimelineEntryV1>(ProductTimelineEntryV1Schema, value, "product_timeline_entry"); }
export function validateProductAcceptanceFactV1(value: unknown): ResultValue<ProductAcceptanceFactV1, FoundationError> { return validateProviderBoundary<ProductAcceptanceFactV1>(ProductAcceptanceFactV1Schema, value, "product_acceptance_fact"); }
export function serializeConnectorCapabilitySnapshotV1(value: ConnectorCapabilitySnapshotV1): string { return serializeExactShape(ConnectorCapabilitySnapshotV1Schema, value, "connector_capability_snapshot"); }
export function parseConnectorCapabilitySnapshotV1(text: string): ResultValue<ConnectorCapabilitySnapshotV1, FoundationError> { return parseExactShape(ConnectorCapabilitySnapshotV1Schema, text, "connector_capability_snapshot"); }
export function serializeChildSpawnRequestV1(value: ChildSpawnRequestV1): string { return serializeExactShape(ChildSpawnRequestV1Schema, value, "child_spawn_request"); }
export function parseChildSpawnRequestV1(text: string): ResultValue<ChildSpawnRequestV1, FoundationError> { return parseExactShape(ChildSpawnRequestV1Schema, text, "child_spawn_request"); }
export function serializeExternalAgentStartRequestV1(value: ExternalAgentStartRequestV1): string { return serializeExactShape(ExternalAgentStartRequestV1Schema, value, "external_agent_start_request"); }
export function parseExternalAgentStartRequestV1(text: string): ResultValue<ExternalAgentStartRequestV1, FoundationError> { return parseExactShape(ExternalAgentStartRequestV1Schema, text, "external_agent_start_request"); }
export function serializeToolGatewayRequestV1(value: ToolGatewayRequestV1): string { return serializeExactShape(ToolGatewayRequestV1Schema, value, "tool_gateway_request"); }
export function parseToolGatewayRequestV1(text: string): ResultValue<ToolGatewayRequestV1, FoundationError> { return parseExactShape(ToolGatewayRequestV1Schema, text, "tool_gateway_request"); }
export function serializeScopedModelRequestV1(value: ScopedModelRequestV1): string { return serializeExactShape(ScopedModelRequestV1Schema, value, "scoped_model_request"); }
export function parseScopedModelRequestV1(text: string): ResultValue<ScopedModelRequestV1, FoundationError> { return parseExactShape(ScopedModelRequestV1Schema, text, "scoped_model_request"); }
export function serializeChildSpawnResultV1(value: ChildSpawnResultV1): string { return serializeExactShape(ChildSpawnResultV1Schema, value, "child_spawn_result"); }
export function parseChildSpawnResultV1(text: string): ResultValue<ChildSpawnResultV1, FoundationError> { return parseExactShape(ChildSpawnResultV1Schema, text, "child_spawn_result"); }
export function serializeToolExecutionResultV1(value: ToolExecutionResultV1): string { return serializeExactShape(ToolExecutionResultV1Schema, value, "tool_execution_result"); }
export function parseToolExecutionResultV1(text: string): ResultValue<ToolExecutionResultV1, FoundationError> { return parseExactShape(ToolExecutionResultV1Schema, text, "tool_execution_result"); }
export function serializeScopedModelResultV1(value: ScopedModelResultV1): string { return serializeExactShape(ScopedModelResultV1Schema, value, "scoped_model_result"); }
export function parseScopedModelResultV1(text: string): ResultValue<ScopedModelResultV1, FoundationError> { return parseExactShape(ScopedModelResultV1Schema, text, "scoped_model_result"); }
export function serializeFoundationProviderCapabilityV1(value: FoundationProviderCapabilityV1): string { return serializeExactShape(FoundationProviderCapabilityV1Schema, value, "provider_capability"); }
export function parseFoundationProviderCapabilityV1(text: string): ResultValue<FoundationProviderCapabilityV1, FoundationError> { return parseExactShape(FoundationProviderCapabilityV1Schema, text, "provider_capability"); }
export function serializeArtifactPutResultV1(value: ArtifactPutResultV1): string { return serializeExactShape(ArtifactPutResultV1Schema, value, "artifact_put_result"); }
export function parseArtifactPutResultV1(text: string): ResultValue<ArtifactPutResultV1, FoundationError> { return parseExactShape(ArtifactPutResultV1Schema, text, "artifact_put_result"); }
export function serializeArtifactVerifyResultV1(value: ArtifactVerifyResultV1): string { return serializeExactShape(ArtifactVerifyResultV1Schema, value, "artifact_verify_result"); }
export function parseArtifactVerifyResultV1(text: string): ResultValue<ArtifactVerifyResultV1, FoundationError> { return parseExactShape(ArtifactVerifyResultV1Schema, text, "artifact_verify_result"); }
export function serializeQuotaAttributionV1(value: QuotaAttributionV1): string { return serializeExactShape(QuotaAttributionV1Schema, value, "quota_attribution"); }
export function parseQuotaAttributionV1(text: string): ResultValue<QuotaAttributionV1, FoundationError> { return parseExactShape(QuotaAttributionV1Schema, text, "quota_attribution"); }
export function serializeQuotaReservationV1(value: QuotaReservationV1): string { return serializeExactShape(QuotaReservationV1Schema, value, "quota_reservation"); }
export function parseQuotaReservationV1(text: string): ResultValue<QuotaReservationV1, FoundationError> { return parseExactShape(QuotaReservationV1Schema, text, "quota_reservation"); }
export function serializeProductTimelineEntryV1(value: ProductTimelineEntryV1): string { return serializeExactShape(ProductTimelineEntryV1Schema, value, "product_timeline_entry"); }
export function parseProductTimelineEntryV1(text: string): ResultValue<ProductTimelineEntryV1, FoundationError> { return parseExactShape(ProductTimelineEntryV1Schema, text, "product_timeline_entry"); }
export function serializeProductAcceptanceFactV1(value: ProductAcceptanceFactV1): string { return serializeExactShape(ProductAcceptanceFactV1Schema, value, "product_acceptance_fact"); }
export function parseProductAcceptanceFactV1(text: string): ResultValue<ProductAcceptanceFactV1, FoundationError> { return parseExactShape(ProductAcceptanceFactV1Schema, text, "product_acceptance_fact"); }
