/**
 * AOS Agent Foundation v1 capability manifest.
 *
 * This module is the machine-checkable ledger for the Foundation v1 one-shot seal
 * (rows 01-10 and 10A of the architecture atlas). It contains:
 *
 * - `FOUNDATION_V1_CAPABILITY_CLOSURES`: exactly 79 closure entries with ids
 *   `1..73, 98, 127, 128, 129, 145, 146`. Each entry records the high-level rows
 *   it closes, the closure kind (implemented / regression_locked / contract_sealed),
 *   the owning module, the stable public contract, the persistence surface, the
 *   nonempty test coverage, the post-T0 implementation stages that own it
 *   (implementation-stages field), and the later consumer line plus the later
 *   capability ids that remain future-only.
 * - `FOUNDATION_V1_FUTURE_CAPABILITY_OWNERS`: exactly 71 future owner entries with
 *   ids `74..97, 99..126, 130..144, 147..150`. Each entry records the later owner
 *   line and the explicit upstream Foundation contracts it consumes, so nothing in
 *   `1..150` is lost and nothing future is mislabeled as closed.
 *
 * Closure and future id sets are disjoint and their union is exactly `1..150`.
 * `foundation-capability-manifest.test.ts` proves these invariants.
 *
 * Owner and test paths are concrete evidence references. A closure status records
 * only the front-layer claim made by this manifest: `contract_sealed` freezes a
 * contract without claiming a later provider, while `implemented` and
 * `regression_locked` require the referenced implementation and tests to exist.
 *
 * Truthfulness rule applied when a capability has multiple closure kinds in the
 * PR ledger (for example "implemented, regression_locked"): the single
 * `closure` value is the strongest forward-looking claim that applies:
 * `contract_sealed` if contract sealing is part of the closure, otherwise
 * `regression_locked` if regression locking applies, otherwise `implemented`.
 */

/** Status of a Foundation v1 capability closure. See module doc for the selection rule. */
export type FoundationCapabilityClosureStatus = "implemented" | "regression_locked" | "contract_sealed";

/** Later consumer line that may only implement the provider/consumer side of a frozen contract. */
export type FoundationLaterConsumerLine = "11" | "12A" | "12B" | "13" | "14" | "15";

/** High-level atlas row identifiers (rows 01-10 plus 10A) owned by this seal. */
export type FoundationHighLevelRow = "01" | "02" | "03" | "04" | "05" | "06" | "07" | "08" | "09" | "10" | "10A";

/**
 * Post-T0 implementation stage owning one or more closure capabilities, matching
 * the stage column of the Foundation seal implementation plan table
 * (`AOS_AGENT_FOUNDATION_V1_SEAL_IMPLEMENTATION_PLAN.md`, section
 * "能力编号到实施阶段的精确归属"). T12 is the final seal stage and lists every
 * closure id. Overlaps across stages are integration work, not duplication.
 */
export type FoundationImplementationStage = "T1" | "T2" | "T3" | "T4" | "T5" | "T6" | "T7" | "T8" | "T9" | "T10" | "T11" | "T12";

/**
 * Closure entry for one Foundation v1 capability. The front layer of the capability
 * is closed by this seal; when {@link laterConsumer} is present, only the listed
 * later side stays future-only.
 */
export interface FoundationCapabilityClosureV1 {
	/** Capability id, unique across the closure manifest. */
	id: number;
	/** High-level atlas rows (01-10 or 10A) that use this capability. Exact per-id mapping is asserted in tests. */
	highLevelRows: readonly FoundationHighLevelRow[];
	/** Post-T0 implementation stages owning this capability. Nonempty; exact per-stage sets are asserted in tests. */
	implementationStages: readonly FoundationImplementationStage[];
	/** Closure kind. Must not overclaim: contract-sealed items never claim a concrete provider is done. */
	closure: FoundationCapabilityClosureStatus;
	/** Module that owns the front-layer closure in this seal. */
	ownerModule: string;
	/** Stable public contract frozen by this closure (schema, state, error, version). Required for contract_sealed. */
	publicContract?: string;
	/** Durable persistence/migration surface that backs the closure. */
	persistence?: string;
	/** Nonempty final-audit test references assigned to this closure; resolved at T12. */
	tests: readonly string[];
	/** Later line that may only implement the provider/consumer side. */
	laterConsumer?: FoundationLaterConsumerLine;
	/** Capability ids that stay future-only behind this closure. Nonempty whenever laterConsumer is set. */
	laterCapabilityIds?: readonly number[];
}

/**
 * Future owner entry for a capability that is NOT closed by Foundation v1.
 * Records the later owner line and the explicit Foundation upstream contracts it
 * consumes, proving the id is covered by a later line instead of dropped.
 */
export interface FoundationFutureCapabilityOwnerV1 {
	/** Capability id, unique across the future owner map. */
	id: number;
	/** Later line responsible for closing this capability. */
	laterOwner: FoundationLaterConsumerLine;
	/** Capability title from the architecture atlas. */
	title: string;
	/** What the later line must implement, and only that. */
	description: string;
	/** Explicit Foundation contracts this later capability consumes. Never empty. */
	consumedFoundationContracts: readonly string[];
}

const rows = <const R extends readonly FoundationHighLevelRow[]>(...r: R): R => r;

const stages = <const S extends readonly FoundationImplementationStage[]>(...s: S): S => s;

const closures = [
	// ---- 01-28: single agent loop ----
	{
		id: 1,
		highLevelRows: rows("01", "03"),
		implementationStages: stages("T1", "T3", "T9", "T10", "T12"),
		closure: "regression_locked",
		ownerModule: "packages/agent/src/harness/agent-harness.ts",
		publicContract: "FoundationEnvelopeV1 command/event envelope and RunReceipt terminal output shared by every entry surface",
		persistence: "Session JSONL ledger durable command/event/RunReceipt records",
		tests: [
			"packages/agent/test/harness/agent-harness-runtime.test.ts",
			"packages/coding-agent/test/suite/agent-session-runtime.test.ts",
			"packages/coding-agent/test/public-api-contract.test.ts",
		],
		laterConsumer: "15",
		laterCapabilityIds: [147, 148, 150],
	},
	{
		id: 2,
		highLevelRows: rows("02"),
		implementationStages: stages("T3", "T9", "T12"),
		closure: "regression_locked",
		ownerModule: "packages/agent/src/harness/agent-harness.ts",
		publicContract: "AgentHarness v2 Agent Loop contract (model call, tool call, result backfill) reused by parent and child executors",
		persistence: "Session ledger operation/action records driven by the reducer",
		tests: [
			"packages/agent/test/harness/agent-harness-runtime.test.ts",
			"packages/coding-agent/test/suite/agent-session-runtime.test.ts",
		],
		laterConsumer: "12A",
		laterCapabilityIds: [90, 111, 112, 114],
	},
	{
		id: 3,
		highLevelRows: rows("01", "03"),
		implementationStages: stages("T1", "T3", "T9", "T10", "T12"),
		closure: "implemented",
		ownerModule: "packages/agent/src/harness/events.ts",
		publicContract: "Typed event catalog with durable/live/derived classification, cursor, gap detection and resume semantics",
		persistence: "Durable events appended to the Session ledger; live deltas are discardable",
		tests: [
			"packages/agent/test/harness/events.test.ts",
			"packages/agent/test/harness/foundation-contracts.test.ts",
			"packages/coding-agent/test/rpc-client-replay-recovery.test.ts",
		],
		laterConsumer: "14",
		laterCapabilityIds: [142, 143],
	},
	{
		id: 4,
		highLevelRows: rows("02", "05", "09"),
		implementationStages: stages("T3", "T4", "T8", "T12"),
		closure: "contract_sealed",
		ownerModule: "packages/agent/src/harness/tool-gateway.ts",
		publicContract: "ToolGateway contract unifying local tools, MCP, sandbox operations and external tool providers",
		persistence: "ToolReceipt durable records written by the tool pipeline finalize stage",
		tests: [
			"packages/agent/test/harness/t4-tool-gateway.test.ts",
			"packages/agent/test/harness/t4-tool-runtime.test.ts",
			"packages/agent/test/harness/foundation-provider-conformance.test.ts",
		],
		laterConsumer: "13",
		laterCapabilityIds: [63, 64, 65],
	},
	{
		id: 5,
		highLevelRows: rows("02", "08"),
		implementationStages: stages("T3", "T4", "T12"),
		closure: "implemented",
		ownerModule: "packages/agent/src/harness/tool-pipeline.ts",
		publicContract: "Parallel tool quota, conflict detection, partial failure and deterministic AttemptReceipt/TaskResult join",
		persistence: "Tool batch and join facts in the Session ledger",
		tests: [
			"packages/agent/test/harness/t4-tool-runtime.test.ts",
			"packages/coding-agent/test/rpc-task-graph.test.ts",
		],
		laterConsumer: "12B",
		laterCapabilityIds: [121, 122],
	},
	{
		id: 6,
		highLevelRows: rows("02", "04", "05", "06"),
		implementationStages: stages("T3", "T4", "T8", "T11", "T12"),
		closure: "regression_locked",
		ownerModule: "packages/agent/src/harness/agent-harness.ts",
		publicContract: "Single cancellation signal and deadline propagated to model, tool, MCP, sandbox and provider boundaries",
		persistence: "Cancel/deadline facts and terminal failure records in the ledger",
		tests: [
			"packages/agent/test/harness/agent-harness-runtime.test.ts",
			"packages/coding-agent/test/run-lifecycle.test.ts",
			"packages/coding-agent/test/rpc-tcp-cancel-idempotency.test.ts",
		],
		laterConsumer: "11",
		laterCapabilityIds: [82, 83, 86],
	},
	{
		id: 7,
		highLevelRows: rows("02", "04"),
		implementationStages: stages("T3", "T4", "T8", "T11", "T12"),
		closure: "regression_locked",
		ownerModule: "packages/agent/src/agent-errors.ts",
		publicContract: "Tagged stable error codes, retry decision, and side-effect-unknown semantics shared by model, tool, worker and executor",
		persistence: "Stable error codes and retry outcomes recorded in durable records",
		tests: [
			"packages/agent/test/agent-loop-errors.test.ts",
			"packages/agent/test/harness/recovery-conformance.test.ts",
		],
		laterConsumer: "13",
		laterCapabilityIds: [132, 133],
	},
	{
		id: 8,
		highLevelRows: rows("02", "09"),
		implementationStages: stages("T3", "T6", "T8", "T12"),
		closure: "regression_locked",
		ownerModule: "packages/agent/src/harness/foundation/model-profile.ts",
		publicContract: "Versioned RoleDefinition/RoleRevision referencing an independent ModelProfile; ModelBroker routes bound to goal/run/task/AgentInstance role",
		persistence: "RoleRevision and ModelProfile durable objects; credentials never persisted on them",
		tests: [
			"packages/agent/test/harness/agent-harness-runtime.test.ts",
			"packages/agent/test/harness/foundation-provider-conformance.test.ts",
			"packages/agent/test/harness/foundation-contracts.test.ts",
			"packages/coding-agent/test/rpc-task-graph.test.ts",
		],
		laterConsumer: "13",
		laterCapabilityIds: [110, 112],
	},
	{
		id: 9,
		highLevelRows: rows("02"),
		implementationStages: stages("T3", "T6", "T8", "T12"),
		closure: "implemented",
		ownerModule: "packages/agent/src/harness/foundation/model-profile.ts",
		publicContract: "Effort and service tier inherited through ModelProfile with traceable source and frozen into AgentBinding",
		persistence: "ModelProfile versioned records with fallback and budget",
		tests: ["packages/agent/test/harness/agent-harness-runtime.test.ts", "packages/agent/test/harness/foundation-contracts.test.ts", "packages/agent/test/harness/t4-runtime-lifecycle.test.ts", "packages/agent/test/harness/foundation-provider-conformance.test.ts"],
		laterConsumer: "13",
		laterCapabilityIds: [110],
	},
	{
		id: 10,
		highLevelRows: rows("02", "08"),
		implementationStages: stages("T3", "T6", "T8", "T12"),
		closure: "regression_locked",
		ownerModule: "packages/agent/src/harness/foundation/binding.ts",
		publicContract: "Token/cost/call/time/concurrency budget attribution with stable terminal reason on exhaustion",
		persistence: "Budget and usage facts attached to attempts and runs",
		tests: ["packages/agent/test/harness/foundation-contracts.test.ts", "packages/agent/test/harness/agent-harness-runtime.test.ts", "packages/coding-agent/test/server/create-harness.test.ts"],
		laterConsumer: "14",
		laterCapabilityIds: [148, 149],
	},
	{
		id: 11,
		highLevelRows: rows("09"),
		implementationStages: stages("T6", "T8", "T12"),
		closure: "contract_sealed",
		ownerModule: "packages/agent/src/harness/foundation/gateway.ts",
		publicContract: "Two-layer scoped gateway contract: external executors reach models only through ScopedExecutionGateway and ScopedModelGateway; host provider credentials never reach executor surfaces",
		persistence: "No credential material in Role, ModelProfile, Binding, Session, receipts, events or logs",
		tests: [
			"packages/agent/test/harness/t6-executor-gateway-conformance.test.ts",
			"packages/agent/test/harness/foundation-capability-manifest.test.ts",
			"packages/agent/test/harness/foundation-contracts.test.ts",
		],
		laterConsumer: "13",
		laterCapabilityIds: [65, 114],
	},
	{
		id: 12,
		highLevelRows: rows("02"),
		implementationStages: stages("T1", "T5", "T12"),
		closure: "implemented",
		ownerModule: "packages/agent/src/harness/artifacts.ts",
		publicContract: "Image/attachment input converted to ArtifactRef inheriting permission, digest and retention policy",
		persistence: "Local content-addressed Artifact Store with manifest, digest, ACL and retention",
		tests: [
			"packages/agent/test/harness/context-t5-ledger.test.ts",
			"packages/agent/test/harness/agent-harness-runtime.test.ts",
			"packages/agent/test/harness/foundation-provider-conformance.test.ts",
			"packages/agent/test/agent-loop.test.ts",
		],
		laterConsumer: "14",
		laterCapabilityIds: [137, 149],
	},
	{
		id: 13,
		highLevelRows: rows("02"),
		implementationStages: stages("T1", "T3", "T6", "T12"),
		closure: "implemented",
		ownerModule: "packages/agent/src/harness/foundation/results.ts",
		publicContract: "Native structured output schema, validation, bounded retry normalized into AttemptReceipt and settled into TaskResult",
		persistence: "Structured output validation facts in the ledger",
		tests: ["packages/agent/test/harness/foundation-contracts.test.ts"],
		laterConsumer: "15",
		laterCapabilityIds: [141, 146],
	},
	{
		id: 14,
		highLevelRows: rows("02", "10A"),
		implementationStages: stages("T2", "T7", "T9", "T12"),
		closure: "implemented",
		ownerModule: "packages/agent/src/harness/foundation/goal-store.ts",
		publicContract: "Plan/Stage/Todo as versioned durable objects with stable ids, order and state",
		persistence: "Plan revision records in the Session ledger",
		tests: ["packages/agent/test/harness/foundation-t7-goal-store.test.ts"],
		laterConsumer: "15",
		laterCapabilityIds: [147],
	},
	{
		id: 15,
		highLevelRows: rows("02", "10A"),
		implementationStages: stages("T2", "T7", "T9", "T12"),
		closure: "implemented",
		ownerModule: "packages/agent/src/harness/foundation/goal-store.ts",
		publicContract: "GoalV1 create/edit/pause/resume/complete/clear with revision, idempotent commands and acceptance criteria",
		persistence: "Durable Goal records with tombstone on clear; history never deleted",
		tests: ["packages/agent/test/harness/foundation-t7-goal-store.test.ts"],
		laterConsumer: "15",
		laterCapabilityIds: [147],
	},
	{
		id: 16,
		highLevelRows: rows("02", "07", "10A"),
		implementationStages: stages("T2", "T7", "T8", "T9", "T12"),
		closure: "implemented",
		ownerModule: "packages/agent/src/harness/foundation/ask-store.ts",
		publicContract: "Durable Ask/Reply with timeout, recovery, escalation and audit; Ask resolves without granting permissions",
		persistence: "AskV1 records with pending/answered/expired/escalated/cancelled states",
		tests: ["packages/agent/test/harness/foundation-t7-ask-store.test.ts"],
		laterConsumer: "12B",
		laterCapabilityIds: [125],
	},
	{
		id: 17,
		highLevelRows: rows("02"),
		implementationStages: stages("T5", "T8", "T12"),
		closure: "contract_sealed",
		ownerModule: "packages/agent/src/harness/context/index.ts",
		publicContract: "Context fork modes none/all/recent-N/structured task package with inheritance matrix and snapshot digest",
		persistence: "ContextSnapshotV1 with revision, source, trust, token budget, summary and digest",
		tests: [
			"packages/agent/test/harness/context-t5-ledger.test.ts",
			"packages/agent/test/harness/context-t5-regressions.test.ts",
			"packages/agent/test/harness/foundation-contracts.test.ts",
		],
		laterConsumer: "12A",
		laterCapabilityIds: [95, 96],
	},
	{
		id: 18,
		highLevelRows: rows("02"),
		implementationStages: stages("T5", "T8", "T12"),
		closure: "regression_locked",
		ownerModule: "packages/agent/src/harness/context/index.ts",
		publicContract: "Instruction sources, path scoping, Managed Lock and inheritance decisions are queryable",
		persistence: "Instruction scope and inheritance facts in the ledger",
		tests: [
			"packages/agent/test/harness/context-t5-regressions.test.ts",
			"packages/agent/test/harness/foundation-contracts.test.ts",
			"packages/coding-agent/test/context-engine.test.ts",
		],
		laterConsumer: "14",
		laterCapabilityIds: [134],
	},
	{
		id: 19,
		highLevelRows: rows("02"),
		implementationStages: stages("T2", "T5", "T11", "T12"),
		closure: "regression_locked",
		ownerModule: "packages/agent/src/harness/compaction/compaction.ts",
		publicContract: "Compaction with version, input leaves, summary source, retention and resume boundary",
		persistence: "Compaction records with recovery origin in the Session ledger",
		tests: [
			"packages/agent/test/harness/context-t5-ledger.test.ts",
			"packages/agent/test/harness/context-t5-regressions.test.ts",
			"packages/agent/test/harness/compaction.test.ts",
			"packages/agent/test/harness/recovery-conformance.test.ts",
		],
		laterConsumer: "14",
		laterCapabilityIds: [143, 149],
	},
	{
		id: 20,
		highLevelRows: rows("02"),
		implementationStages: stages("T2", "T5", "T12"),
		closure: "implemented",
		ownerModule: "packages/agent/src/harness/memory/index.ts",
		publicContract: "Auto-scoped Memory with independent child scope, provenance check and cleanup policy",
		persistence: "Memory scope/provenance/retention records in the ledger",
		tests: [
			"packages/agent/test/harness/context-t5-regressions.test.ts",
			"packages/agent/test/harness/foundation-contracts.test.ts",
			"packages/agent/test/harness/session/memory.test.ts",
		],
		laterConsumer: "12A",
		laterCapabilityIds: [97],
	},
	{
		id: 21,
		highLevelRows: rows("01", "10A"),
		implementationStages: stages("T1", "T2", "T3", "T7", "T9", "T11", "T12"),
		closure: "regression_locked",
		ownerModule: "packages/agent/src/harness/session/index.ts",
		publicContract: "Session persistence and restore; a crashed active step resumes from the exact reducer-computed boundary",
		persistence: "Append-only Session JSONL ledger with atomic append and migration",
		tests: [
			"packages/agent/test/harness/agent-harness-runtime.test.ts",
			"packages/agent/test/harness/recovery-conformance.test.ts",
			"packages/agent/test/harness/session/jsonl.test.ts",
			"packages/agent/test/harness/session/t11r-recovery.test.ts",
		],
		laterConsumer: "14",
		laterCapabilityIds: [143],
	},
	{
		id: 22,
		highLevelRows: rows("01"),
		implementationStages: stages("T1", "T2", "T5", "T9", "T11", "T12"),
		closure: "regression_locked",
		ownerModule: "packages/agent/src/harness/session/index.ts",
		publicContract: "Fork/clone/import/export/share preserving lineage and Artifact associations",
		persistence: "Lineage and branch-summary records in the ledger",
		tests: [
			"packages/agent/test/harness/context-t5-ledger.test.ts",
			"packages/agent/test/harness/branch-summarization.test.ts",
			"packages/coding-agent/test/rpc-client-clone.test.ts",
		],
		laterConsumer: "14",
		laterCapabilityIds: [149],
	},
	{
		id: 23,
		highLevelRows: rows("01"),
		implementationStages: stages("T1", "T2", "T9", "T11", "T12"),
		closure: "regression_locked",
		ownerModule: "packages/agent/src/harness/session/index.ts",
		publicContract: "Session metadata contract covering rename/search/archive/ephemeral/from-PR",
		persistence: "Session metadata records in the ledger",
		tests: ["packages/agent/test/harness/session/jsonl.test.ts", "packages/agent/test/harness/agent-harness-runtime.test.ts"],
		laterConsumer: "15",
		laterCapabilityIds: [148, 150],
	},
	{
		id: 24,
		highLevelRows: rows("01"),
		implementationStages: stages("T1", "T2", "T5", "T9", "T11", "T12"),
		closure: "implemented",
		ownerModule: "packages/agent/src/harness/compaction/compaction.ts",
		publicContract: "Transcript/file dual-dimension Checkpoint, impact plan and fail-closed rewind",
		persistence: "Checkpoint and rewind records with impact plan before mutation",
		tests: [
			"packages/agent/test/harness/context-t5-ledger.test.ts",
			"packages/agent/test/harness/context-t5-regressions.test.ts",
			"packages/agent/test/harness/recovery-conformance.test.ts",
			"packages/agent/test/harness/compaction.test.ts",
		],
		laterConsumer: "14",
		laterCapabilityIds: [135, 139],
	},
	{
		id: 25,
		highLevelRows: rows("01"),
		implementationStages: stages("T1", "T2", "T3", "T5", "T9", "T11", "T12"),
		closure: "implemented",
		ownerModule: "packages/agent/src/harness/reducer.ts",
		publicContract: "Resume-from-summary and interrupted event synthesis from reducer-derived state",
		persistence: "Resume boundary facts derived from durable records",
		tests: [
			"packages/agent/test/harness/context-t5-regressions.test.ts",
			"packages/agent/test/harness/recovery-conformance.test.ts",
			"packages/agent/test/harness/reducer.test.ts",
		],
		laterConsumer: "14",
		laterCapabilityIds: [143],
	},
	{
		id: 26,
		highLevelRows: rows("01", "08", "10A"),
		implementationStages: stages("T1", "T2", "T3", "T7", "T9", "T11", "T12"),
		closure: "implemented",
		ownerModule: "packages/agent/src/harness/agent-harness.ts",
		publicContract: "Explicit Turn/Step/Inbox with queued/claimed/consumed/cancelled states",
		persistence: "Turn/Step/Inbox records in the Session ledger",
		tests: ["packages/agent/test/harness/agent-harness-runtime.test.ts", "packages/agent/test/harness/foundation-contracts.test.ts"],
		laterConsumer: "12B",
		laterCapabilityIds: [103, 123, 124],
	},
	{
		id: 27,
		highLevelRows: rows("01"),
		implementationStages: stages("T1", "T2", "T3", "T9", "T10", "T11", "T12"),
		closure: "implemented",
		ownerModule: "packages/agent/src/harness/foundation/observer.ts",
		publicContract: "Observer attach/reconnect, snapshot-buffer-live flow, cursor gap and multi-client continuity with single-writer constraint",
		persistence: "Observers read the ledger; they never write durable facts",
		tests: [
			"packages/agent/test/harness/events.test.ts",
			"packages/coding-agent/test/rpc-client-replay-recovery.test.ts",
		],
		laterConsumer: "14",
		laterCapabilityIds: [142, 143],
	},
	{
		id: 28,
		highLevelRows: rows("01"),
		implementationStages: stages("T1", "T2", "T3", "T5", "T11", "T12"),
		closure: "contract_sealed",
		ownerModule: "packages/agent/src/harness/context/index.ts",
		publicContract: "Prompt cache keyed by immutable prefix digest with sharing, invalidation reason and cost attribution",
		persistence: "Cache digest and invalidation facts in the ledger",
		tests: [
			"packages/agent/test/harness/context-t5-ledger.test.ts",
			"packages/agent/test/harness/context-t5-regressions.test.ts",
			"packages/agent/test/harness/foundation-contracts.test.ts",
			"packages/agent/test/harness/events.test.ts",
			"packages/agent/test/harness/foundation-provider-conformance.test.ts",
		],
		laterConsumer: "13",
		laterCapabilityIds: [110],
	},

	// ---- 29-46: runtime, extensions and tool system ----
	{
		id: 29,
		highLevelRows: rows("02", "10"),
		implementationStages: stages("T4", "T6", "T8", "T9", "T12"),
		closure: "regression_locked",
		ownerModule: "packages/agent/src/harness/skills.ts",
		publicContract: "Skill metadata with parameters, model role, effort, fork, tool policy and MCP selector; referenceable by Role selector",
		persistence: "Skill metadata records; skills stay content-addressed filesystem assets",
		tests: ["packages/agent/test/harness/skills.test.ts", "packages/coding-agent/test/sdk-skills.test.ts"],
		laterConsumer: "15",
		laterCapabilityIds: [147, 148],
	},
	{
		id: 30,
		highLevelRows: rows("02", "10"),
		implementationStages: stages("T4", "T8", "T9", "T12"),
		closure: "regression_locked",
		ownerModule: "packages/agent/src/harness/runtime-services.ts",
		publicContract: "Extension lifecycle with fixed ordering, error isolation and deterministic unload semantics",
		persistence: "Effect-scoped registration records with grouped cleanup",
		tests: ["packages/agent/test/harness/t4-runtime-lifecycle.test.ts", "packages/coding-agent/test/agent-session-capabilities.test.ts"],
		laterConsumer: "15",
		laterCapabilityIds: [147, 150],
	},
	{
		id: 31,
		highLevelRows: rows("02", "10"),
		implementationStages: stages("T4", "T8", "T9", "T12"),
		closure: "implemented",
		ownerModule: "packages/agent/src/harness/runtime-services.ts",
		publicContract: "Dynamic tool registration conflict, revision, override and reload rules",
		persistence: "Tool registration/revision facts in the ledger",
		tests: ["packages/agent/test/harness/t4-runtime-lifecycle.test.ts", "packages/coding-agent/test/agent-session-dynamic-tools.test.ts"],
		laterConsumer: "15",
		laterCapabilityIds: [147, 150],
	},
	{
		id: 32,
		highLevelRows: rows("09", "10"),
		implementationStages: stages("T4", "T8", "T12"),
		closure: "contract_sealed",
		ownerModule: "packages/coding-agent/src/core/mcp-tool-adapter.ts",
		publicContract: "stdio/HTTP MCP integrated through one executor-neutral projection with capability/policy boundaries preserved",
		persistence: "MCP pre-call durable records via the unified tool pipeline",
		tests: [
			"packages/coding-agent/test/mcp-lifecycle.test.ts",
			"packages/coding-agent/test/mcp-tool-adapter.test.ts",
		],
		laterConsumer: "13",
		laterCapabilityIds: [111, 112, 114],
	},
	{
		id: 33,
		highLevelRows: rows("10"),
		implementationStages: stages("T4", "T8", "T12"),
		closure: "regression_locked",
		ownerModule: "packages/coding-agent/src/core/mcp-lifecycle.ts",
		publicContract: "MCP OAuth/resources/prompts keeping the existing security boundary and adding hierarchical trimming",
		persistence: "OAuth and resource/prompt attachment records; credentials never enter the ledger",
		tests: ["packages/coding-agent/test/mcp-auth.test.ts", "packages/coding-agent/test/mcp-resource-prompt.test.ts"],
		laterConsumer: "14",
		laterCapabilityIds: [138, 150],
	},
	{
		id: 34,
		highLevelRows: rows("10"),
		implementationStages: stages("T4", "T8", "T12"),
		closure: "contract_sealed",
		ownerModule: "packages/agent/src/harness/foundation/binding.ts",
		publicContract: "all/none/named/except MCP inheritance selectors on Role/parent Binding with lower layers only tightening",
		persistence: "MCP selector resolution frozen into AgentBinding records",
		tests: [
			"packages/agent/test/harness/foundation-contracts.test.ts",
			"packages/agent/test/harness/foundation-provider-conformance.test.ts",
			"packages/agent/test/harness/t4-runtime-lifecycle.test.ts",
		],
		laterConsumer: "12A",
		laterCapabilityIds: [96, 110],
	},
	{
		id: 35,
		highLevelRows: rows("02", "05"),
		implementationStages: stages("T3", "T4", "T12"),
		closure: "implemented",
		ownerModule: "packages/agent/src/harness/tool-pipeline.ts",
		publicContract: "Fixed tool pipeline: prepare -> pre -> guard -> execute -> post -> finalize",
		persistence: "Tool intent and ToolReceipt durable records per invocation",
		tests: ["packages/agent/test/harness/t4-tool-runtime.test.ts", "packages/agent/test/harness/t4-tool-gateway.test.ts", "packages/agent/test/harness/t4-agent-harness-pipeline.test.ts"],
		laterConsumer: "11",
		laterCapabilityIds: [84, 87, 140],
	},
	{
		id: 36,
		highLevelRows: rows("02", "05"),
		implementationStages: stages("T2", "T3", "T4", "T11", "T12"),
		closure: "implemented",
		ownerModule: "packages/agent/src/harness/tool-pipeline.ts",
		publicContract: "Pre-call durable record, original/accepted argument digests, monotonic guard, no silent parameter mutation",
		persistence: "Argument digest and transform provenance facts in the ledger",
		tests: ["packages/agent/test/harness/t4-tool-runtime.test.ts", "packages/agent/test/harness/t4-agent-harness-pipeline.test.ts"],
	},
	{
		id: 37,
		highLevelRows: rows("02"),
		implementationStages: stages("T4", "T12"),
		closure: "implemented",
		ownerModule: "packages/agent/src/harness/runtime-services.ts",
		publicContract: "Runtime service provider/consumer with explicit service id, version, dependencies, and startup cycle validation",
		persistence: "Service DAG and registration records",
		tests: ["packages/agent/test/harness/t4-runtime-lifecycle.test.ts"],
		laterConsumer: "15",
		laterCapabilityIds: [147, 150],
	},
	{
		id: 38,
		highLevelRows: rows("02", "10"),
		implementationStages: stages("T4", "T6", "T12"),
		closure: "implemented",
		ownerModule: "packages/agent/src/harness/profile.ts",
		publicContract: "Deterministic Profile/Bundle/Patch composition with Global/Project Role override, conflict and source records",
		persistence: "Bundle/Patch composition and override records; Managed Lock never overridable",
		tests: ["packages/agent/test/harness/t4-runtime-lifecycle.test.ts"],
		laterConsumer: "14",
		laterCapabilityIds: [134],
	},
	{
		id: 39,
		highLevelRows: rows("02", "10"),
		implementationStages: stages("T4", "T12"),
		closure: "implemented",
		ownerModule: "packages/agent/src/harness/runtime-services.ts",
		publicContract: "Effect-scoped registration and unload with grouped cleanup, rollback and resource release",
		persistence: "Effect scope activation/teardown records",
		tests: ["packages/agent/test/harness/t4-runtime-lifecycle.test.ts"],
		laterConsumer: "15",
		laterCapabilityIds: [147, 150],
	},
	{
		id: 40,
		highLevelRows: rows("02", "03", "10"),
		implementationStages: stages("T1", "T2", "T3", "T4", "T9", "T10", "T11", "T12"),
		closure: "implemented",
		ownerModule: "packages/agent/src/harness/events.ts",
		publicContract: "Typed event catalog with producer, consumer, version and stable field declarations",
		persistence: "Durable events in the ledger with sequence, event id and timestamp",
		tests: ["packages/agent/test/harness/events.test.ts"],
		laterConsumer: "14",
		laterCapabilityIds: [142, 150],
	},
	{
		id: 41,
		highLevelRows: rows("02", "03", "10"),
		implementationStages: stages("T1", "T2", "T3", "T4", "T9", "T10", "T11", "T12"),
		closure: "implemented",
		ownerModule: "packages/agent/src/harness/events.ts",
		publicContract: "durable/live/derived event taxonomy with testable derivation rules",
		persistence: "Only durable facts persisted; live deltas are discardable",
		tests: ["packages/agent/test/harness/events.test.ts"],
		laterConsumer: "14",
		laterCapabilityIds: [142],
	},
	{
		id: 42,
		highLevelRows: rows("02", "10"),
		implementationStages: stages("T4", "T9", "T12"),
		closure: "implemented",
		ownerModule: "packages/agent/src/harness/plugins.ts",
		publicContract: "Plugin composite package can contain skills, extensions, MCP, agents, hooks, LSP, monitors, bin and settings",
		persistence: "Plugin manifest and activation records",
		tests: ["packages/agent/test/harness/t4-runtime-lifecycle.test.ts"],
		laterConsumer: "15",
		laterCapabilityIds: [147, 150],
	},
	{
		id: 43,
		highLevelRows: rows("02", "10"),
		implementationStages: stages("T4", "T9", "T12"),
		closure: "contract_sealed",
		ownerModule: "packages/agent/src/harness/plugins.ts",
		publicContract: "Local plugin namespace, manifest, signature, version and install/update/rollback lifecycle",
		persistence: "Staged activation with atomic switch and rollback point",
		tests: ["packages/agent/test/harness/t4-runtime-lifecycle.test.ts"],
		laterConsumer: "15",
		laterCapabilityIds: [147, 150],
	},
	{
		id: 44,
		highLevelRows: rows("02", "10"),
		implementationStages: stages("T4", "T6", "T9", "T12"),
		closure: "regression_locked",
		ownerModule: "packages/agent/src/harness/foundation/role-registry.ts",
		publicContract: "Config precedence with Managed Lock, Global/Project Role override, path activation, resolved preview and conflict report",
		persistence: "Resolution source and conflict records; resolved preview derivable",
		tests: ["packages/agent/test/harness/foundation-contracts.test.ts", "packages/agent/test/harness/t4-runtime-lifecycle.test.ts"],
		laterConsumer: "14",
		laterCapabilityIds: [134],
	},
	{
		id: 45,
		highLevelRows: rows("02", "03", "10"),
		implementationStages: stages("T3", "T4", "T9", "T10", "T12"),
		closure: "contract_sealed",
		ownerModule: "packages/coding-agent/src/core/runtime-session-surface.ts",
		publicContract: "TUI/headless/RPC/SDK shared RuntimeSession facade; other surfaces consume conformance adapters",
		persistence: "Surfaces never hold a second Session state authority",
		tests: [
			"packages/coding-agent/test/foundation-runtime-session-surfaces.test.ts",
			"packages/coding-agent/test/rpc-automation-run.test.ts",
		],
		laterConsumer: "15",
		laterCapabilityIds: [147, 150],
	},
	{
		id: 46,
		highLevelRows: rows("02", "10"),
		implementationStages: stages("T4", "T12"),
		closure: "contract_sealed",
		ownerModule: "packages/agent/src/harness/runtime-services.ts",
		publicContract: "Standard LSP/Monitor extension types, permissions, lifecycle and diagnostic events",
		persistence: "Diagnostic event records via the typed event catalog",
		tests: [
			"packages/agent/test/harness/t4-runtime-lifecycle.test.ts",
			"packages/agent/test/harness/events.test.ts",
			"packages/agent/test/harness/foundation-provider-conformance.test.ts",
		],
		laterConsumer: "15",
		laterCapabilityIds: [147, 150],
	},

	// ---- 47-73: platform control plane and protocol ----
	{
		id: 47,
		highLevelRows: rows("01", "04", "08", "10A"),
		implementationStages: stages("T1", "T2", "T3", "T7", "T8", "T9", "T11", "T12"),
		closure: "regression_locked",
		ownerModule: "packages/coding-agent/src/core/run-lifecycle.ts",
		publicContract: "Unified Run lifecycle for child and external runs with Host-exclusive RunReceipt terminal gate",
		persistence: "Run stream projected from typed durable events; Host writes the single RunReceipt",
		tests: ["packages/coding-agent/test/run-lifecycle.test.ts", "packages/coding-agent/test/rpc-task-graph.test.ts"],
		laterConsumer: "14",
		laterCapabilityIds: [141, 143],
	},
	{
		id: 48,
		highLevelRows: rows("02", "06"),
		implementationStages: stages("T1", "T6", "T8", "T12"),
		closure: "regression_locked",
		ownerModule: "packages/agent/src/harness/foundation/binding.ts",
		publicContract: "Task + RoleRevision + ModelProfileRevision + Policy resolved into an immutable, fingerprintable AgentBinding activated by BindingEpoch",
		persistence: "AgentBinding and BindingEpoch durable records",
		tests: ["packages/agent/test/harness/foundation-contracts.test.ts", "packages/agent/test/harness/foundation-provider-conformance.test.ts", "packages/agent/test/harness/agent-harness-runtime.test.ts"],
		laterConsumer: "12A",
		laterCapabilityIds: [96, 109, 110],
	},
	{
		id: 49,
		highLevelRows: rows("02"),
		implementationStages: stages("T1", "T2", "T3", "T5", "T8", "T12"),
		closure: "regression_locked",
		ownerModule: "packages/agent/src/harness/context/index.ts",
		publicContract: "Context Snapshot per Attempt with revision, source, summary and digest pinned to a BindingEpoch",
		persistence: "ContextSnapshotV1 records",
		tests: [
			"packages/agent/test/harness/context-t5-ledger.test.ts",
			"packages/agent/test/harness/context-t5-regressions.test.ts",
			"packages/agent/test/harness/foundation-contracts.test.ts",
		],
	},
	{
		id: 50,
		highLevelRows: rows("02", "09"),
		implementationStages: stages("T6", "T8", "T12"),
		closure: "contract_sealed",
		ownerModule: "packages/agent/src/harness/foundation/gateway.ts",
		publicContract: "Two-layer scoped gateway contract: external executors consume only ScopedExecutionGateway and ScopedModelGateway; CredentialTarget and CredentialLease are short-lived references without material",
		persistence: "Role, ModelProfile, Binding, BindingEpoch, Session, receipts, events and logs persist identity and route facts only; credential material stays outside the ledger",
		tests: [
			"packages/agent/test/harness/t6-executor-gateway-conformance.test.ts",
			"packages/agent/test/harness/foundation-t6-role-binding-results.test.ts",
			"packages/agent/test/harness/foundation-capability-manifest.test.ts",
		],
		laterConsumer: "13",
		laterCapabilityIds: [63, 65, 114],
	},
	{
		id: 51,
		highLevelRows: rows("02", "09"),
		implementationStages: stages("T4", "T6", "T8", "T12"),
		closure: "contract_sealed",
		ownerModule: "packages/coding-agent/src/core/capability-registry.ts",
		publicContract: "Unified capability descriptor/registry consumed by Role selectors, Worker, Subagent and External executors",
		persistence: "Capability registration and resolution records",
		tests: ["packages/coding-agent/test/capability-registry.test.ts", "packages/agent/test/harness/foundation-provider-conformance.test.ts"],
		laterConsumer: "11",
		laterCapabilityIds: [74, 77, 85],
	},
	{
		id: 52,
		highLevelRows: rows("02", "05", "06", "09", "10"),
		implementationStages: stages("T4", "T6", "T8", "T12"),
		closure: "regression_locked",
		ownerModule: "packages/coding-agent/src/core/execution-policy.ts",
		publicContract: "Policy/Sandbox inheritance, organization lock and unified review border fixed",
		persistence: "Execution policy ledger records",
		tests: ["packages/coding-agent/test/execution-policy-contract.test.ts", "packages/coding-agent/test/execution-policy.test.ts"],
		laterConsumer: "14",
		laterCapabilityIds: [133, 134, 135],
	},
	{
		id: 53,
		highLevelRows: rows("02", "09"),
		implementationStages: stages("T2", "T5", "T8", "T11", "T12"),
		closure: "regression_locked",
		ownerModule: "packages/coding-agent/src/core/execution-audit.ts",
		publicContract: "Audit/Replay/external.map with integrity, retention and export contracts",
		persistence: "Audit and replay records with external mapping",
		tests: ["packages/coding-agent/test/execution-audit-contract.test.ts", "packages/coding-agent/test/execution-audit-query.test.ts"],
		laterConsumer: "14",
		laterCapabilityIds: [139, 149],
	},
	{
		id: 54,
		highLevelRows: rows("02", "07"),
		implementationStages: stages("T7", "T8", "T12"),
		closure: "regression_locked",
		ownerModule: "packages/coding-agent/src/core/task-gate.ts",
		publicContract: "Tool approval, human ask and task stage gate classified so none can escalate another",
		persistence: "Gate state and approval records in the ledger",
		tests: ["packages/coding-agent/test/task-gate.test.ts", "packages/coding-agent/test/rpc-task-gate.test.ts"],
		laterConsumer: "15",
		laterCapabilityIds: [145, 147],
	},
	{
		id: 55,
		highLevelRows: rows("02", "08"),
		implementationStages: stages("T7", "T8", "T12"),
		closure: "contract_sealed",
		ownerModule: "packages/coding-agent/src/core/task-graph.ts",
		publicContract: "Task Graph nodes unified as Task; TaskExecutorProvider/Dispatch/Attempt/AttemptReceipt/TaskResult interfaces frozen; Run/Dispatch/Attempt are execution records",
		persistence: "Task graph, dispatch and attempt records; results settle into TaskResult",
		tests: ["packages/coding-agent/test/task-graph.test.ts", "packages/agent/test/harness/foundation-provider-conformance.test.ts"],
		laterConsumer: "12B",
		laterCapabilityIds: [119, 120, 121, 122],
	},
	{
		id: 56,
		highLevelRows: rows("01", "07", "08", "10A"),
		implementationStages: stages("T1", "T2", "T7", "T8", "T11", "T12"),
		closure: "implemented",
		ownerModule: "packages/agent/src/harness/foundation/identity.ts",
		publicContract: "ExecutionCorrelationV1 linking Session/Goal/Run/Task/Dispatch/Attempt/Turn/Step with revision and fencing token",
		persistence: "Correlation and lineage records referenced by every durable fact",
		tests: ["packages/agent/test/harness/recovery-conformance.test.ts", "packages/agent/test/harness/foundation-contracts.test.ts", "packages/coding-agent/test/rpc-task-graph.test.ts"],
		laterConsumer: "12A",
		laterCapabilityIds: [93, 114],
	},
	{
		id: 57,
		highLevelRows: rows("01", "07", "08", "09", "10A"),
		implementationStages: stages("T1", "T2", "T5", "T7", "T8", "T11", "T12"),
		closure: "regression_locked",
		ownerModule: "packages/agent/src/harness/foundation/identity.ts",
		publicContract: "Parent/ancestor/child/attempt lineage queries unified",
		persistence: "Lineage records derived from explicit id references",
		tests: [
			"packages/agent/test/harness/context-t5-regressions.test.ts",
			"packages/agent/test/harness/recovery-conformance.test.ts",
			"packages/agent/test/harness/foundation-contracts.test.ts",
			"packages/coding-agent/test/rpc-task-graph.test.ts",
		],
		laterConsumer: "12A",
		laterCapabilityIds: [93, 116],
	},
	{
		id: 58,
		highLevelRows: rows("01", "06", "07", "08"),
		implementationStages: stages("T1", "T2", "T5", "T6", "T8", "T11", "T12"),
		closure: "regression_locked",
		ownerModule: "packages/agent/src/harness/foundation/identity.ts",
		publicContract: "Fingerprint includes RoleRevision, ModelProfileRevision, Context, Policy, Capability and executor revision",
		persistence: "Fingerprint digests stored with bindings and attempts",
		tests: [
			"packages/agent/test/harness/context-t5-ledger.test.ts",
			"packages/agent/test/harness/foundation-contracts.test.ts",
			"packages/agent/test/harness/foundation-provider-conformance.test.ts",
			"packages/agent/test/harness/recovery-conformance.test.ts",
		],
		laterConsumer: "12B",
		laterCapabilityIds: [120, 122],
	},
	{
		id: 59,
		highLevelRows: rows("01", "07", "08"),
		implementationStages: stages("T1", "T2", "T3", "T8", "T10", "T11", "T12"),
		closure: "regression_locked",
		ownerModule: "packages/agent/src/harness/session/index.ts",
		publicContract: "Single-writer Session lease with fencing; stale attempt results isolated",
		persistence: "Writer lease, fencing token and revision records in the ledger",
		tests: [
			"packages/agent/test/harness/recovery-conformance.test.ts",
			"packages/agent/test/harness/session/jsonl.test.ts",
			"packages/agent/test/harness/session/t11r-recovery.test.ts",
		],
		laterConsumer: "14",
		laterCapabilityIds: [120, 143],
	},
	{
		id: 60,
		highLevelRows: rows("01", "03", "07", "08"),
		implementationStages: stages("T1", "T2", "T3", "T8", "T10", "T11", "T12"),
		closure: "regression_locked",
		ownerModule: "packages/agent/src/harness/foundation/observer.ts",
		publicContract: "Replay cursor, gap detection, atomic crash ordering and snapshot reconnect",
		persistence: "Cursor positions against the ledger; gaps fail with a stable error",
		tests: ["packages/agent/test/harness/events.test.ts", "packages/coding-agent/test/rpc-client-replay-recovery.test.ts"],
		laterConsumer: "14",
		laterCapabilityIds: [143],
	},
	{
		id: 61,
		highLevelRows: rows("02", "04", "05", "06", "08"),
		implementationStages: stages("T3", "T4", "T8", "T11", "T12"),
		closure: "regression_locked",
		ownerModule: "packages/agent/src/harness/tool-pipeline.ts",
		publicContract: "side-effect-unknown as a unified terminal state for model, tool, MCP, sandbox and external execution",
		persistence: "Side-effect state recorded on ToolReceipt and AttemptReceipt",
		tests: ["packages/agent/test/harness/t4-tool-runtime.test.ts", "packages/agent/test/harness/recovery-conformance.test.ts"],
		laterConsumer: "11",
		laterCapabilityIds: [82, 86],
	},
	{
		id: 62,
		highLevelRows: rows("09"),
		implementationStages: stages("T8", "T12"),
		closure: "contract_sealed",
		ownerModule: "packages/coding-agent/src/core/external-agent-adapter.ts",
		publicContract: "External Agent Adapter resume handle, capability negotiation and fake resume conformance",
		persistence: "External mapping and remote operation records",
		tests: ["packages/coding-agent/test/external-agent-adapter.test.ts", "packages/agent/test/harness/foundation-provider-conformance.test.ts"],
		laterConsumer: "13",
		laterCapabilityIds: [63, 64, 65],
	},
	{
		id: 63,
		highLevelRows: rows("09"),
		implementationStages: stages("T8", "T12"),
		closure: "contract_sealed",
		ownerModule: "packages/coding-agent/src/core/external-agent-adapter.ts",
		publicContract: "Claude/Codex/ACP start/cancel/continue/receipt mapping interfaces",
		persistence: "External session mapping and receipts normalized as execution records",
		tests: ["packages/coding-agent/test/external-agent-integration.test.ts", "packages/agent/test/harness/foundation-provider-conformance.test.ts"],
		laterConsumer: "13",
		laterCapabilityIds: [63, 64, 65],
	},
	{
		id: 64,
		highLevelRows: rows("09"),
		implementationStages: stages("T8", "T12"),
		closure: "contract_sealed",
		ownerModule: "packages/coding-agent/src/core/external-agent-adapter.ts",
		publicContract: "Agent/Tool/Skill/MCP/Sandbox config translators with exact-shape validation",
		persistence: "Translation and validation facts in the ledger",
		tests: ["packages/coding-agent/test/external-agent-adapter.test.ts", "packages/coding-agent/test/remote-operation-contract.test.ts", "packages/agent/test/harness/foundation-provider-conformance.test.ts"],
		laterConsumer: "13",
		laterCapabilityIds: [63, 64, 65],
	},
	{
		id: 65,
		highLevelRows: rows("06", "09"),
		implementationStages: stages("T6", "T8", "T12"),
		closure: "contract_sealed",
		ownerModule: "packages/coding-agent/src/core/task-credential-lease.ts",
		publicContract: "agent-owned/AOS-gateway modes with short-lived tokens and resource projection contracts",
		persistence: "Credential leases with scope, TTL, renew and revoke; material never persisted",
		tests: ["packages/coding-agent/test/task-credential-lease.test.ts", "packages/agent/test/harness/foundation-provider-conformance.test.ts"],
		laterConsumer: "13",
		laterCapabilityIds: [85, 136],
	},
	{
		id: 66,
		highLevelRows: rows("02", "09"),
		implementationStages: stages("T6", "T8", "T12"),
		closure: "implemented",
		ownerModule: "packages/agent/src/harness/foundation/role-registry.ts",
		publicContract: "Global/Project Role CRUD/copy/search/import/export, immutable RoleRevision, independent ModelProfile, source conflicts, Resolver, AgentBinding, AgentInstance; slug is not identity",
		persistence: "RoleDefinition/RoleRevision records with tombstone delete",
		tests: ["packages/agent/test/harness/agent-harness-runtime.test.ts", "packages/agent/test/harness/foundation-provider-conformance.test.ts", "packages/agent/test/harness/foundation-contracts.test.ts"],
		laterConsumer: "15",
		laterCapabilityIds: [147],
	},
	{
		id: 67,
		highLevelRows: rows("02", "06", "10A"),
		implementationStages: stages("T1", "T2", "T5", "T7", "T11", "T12"),
		closure: "implemented",
		ownerModule: "packages/agent/src/harness/artifacts.ts",
		publicContract: "Local content-addressed Artifact Store with manifest, digest, ACL and retention; Session holds only references",
		persistence: "Artifact manifests and digests; blobs content-addressed",
		tests: [
			"packages/agent/test/harness/context-t5-ledger.test.ts",
			"packages/agent/test/harness/context-t5-regressions.test.ts",
			"packages/agent/test/harness/foundation-provider-conformance.test.ts",
		],
		laterConsumer: "14",
		laterCapabilityIds: [137, 149],
	},
	{
		id: 68,
		highLevelRows: rows("01", "03"),
		implementationStages: stages("T1", "T3", "T8", "T9", "T10", "T11", "T12"),
		closure: "regression_locked",
		ownerModule: "packages/coding-agent/src/core/sdk.ts",
		publicContract: "Automation Host and SDK with stable versions, task control, subscription and recovery",
		persistence: "Automation host records over the shared RuntimeSession",
		tests: ["packages/coding-agent/test/rpc-automation-run.test.ts", "packages/coding-agent/test/sdk-session-manager.test.ts"],
		laterConsumer: "15",
		laterCapabilityIds: [150],
	},
	{
		id: 69,
		highLevelRows: rows("01", "03"),
		implementationStages: stages("T1", "T10", "T11", "T12"),
		closure: "implemented",
		ownerModule: "packages/coding-agent/src/modes/rpc/rpc-transport.ts",
		publicContract: "stdio/TCP/WebSocket transports with auth handshake, TLS config and remote-address policy; loopback default",
		persistence: "Transport framing only; it owns no Session or Run state",
		tests: ["packages/coding-agent/test/rpc-stdio-tcp-transcript.test.ts", "packages/coding-agent/test/rpc-transport.test.ts"],
		laterConsumer: "14",
		laterCapabilityIds: [88, 143],
	},
	{
		id: 70,
		highLevelRows: rows("01", "03"),
		implementationStages: stages("T1", "T2", "T9", "T10", "T11", "T12"),
		closure: "implemented",
		ownerModule: "packages/agent/src/harness/foundation/observer.ts",
		publicContract: "Server-side Session continuity with multiple observers and reconnection",
		persistence: "Server holds the Session; observers are read-only",
		tests: ["packages/coding-agent/test/rpc-client-replay-recovery.test.ts", "packages/agent/test/harness/events.test.ts"],
		laterConsumer: "14",
		laterCapabilityIds: [143],
	},
	{
		id: 71,
		highLevelRows: rows("02"),
		implementationStages: stages("T6", "T8", "T10", "T11", "T12"),
		closure: "contract_sealed",
		ownerModule: "packages/agent/src/harness/foundation/providers.ts",
		publicContract: "Tenant/identity/RBAC/quota/billing attribution interfaces with a built-in single-host default",
		persistence: "Single-host quota attribution records; no multi-tenant backend",
		tests: ["packages/coding-agent/test/server/create-harness.test.ts", "packages/agent/test/harness/foundation-provider-conformance.test.ts"],
		laterConsumer: "14",
		laterCapabilityIds: [148, 149],
	},
	{
		id: 72,
		highLevelRows: rows("01", "03"),
		implementationStages: stages("T1", "T2", "T8", "T10", "T11", "T12"),
		closure: "implemented",
		ownerModule: "packages/agent/src/harness/foundation/protocol.ts",
		publicContract: "Protocol compatibility matrix, feature negotiation, migration registry and rollback",
		persistence: "Migration plans with temp target and atomic replace; unknown schema fails closed",
		tests: [
			"packages/agent/test/harness/foundation-contracts.test.ts",
			"packages/agent/test/harness/session/t11r-recovery.test.ts",
		],
		laterConsumer: "14",
		laterCapabilityIds: [150],
	},
	{
		id: 73,
		highLevelRows: rows("02"),
		implementationStages: stages("T3", "T7", "T8", "T9", "T12"),
		closure: "implemented",
		ownerModule: "packages/agent/src/harness/foundation/workflow.ts",
		publicContract: "Local workflow evaluation dataset, result snapshots and quality/cost/recovery regression runner",
		persistence: "Workflow dataset and snapshot records",
		tests: [
			"packages/agent/test/harness/foundation-t12-workflow-evaluation.test.ts",
			"packages/agent/test/harness/recovery-conformance.test.ts",
		],
		laterConsumer: "14",
		laterCapabilityIds: [141, 148],
	},

	// ---- 98, 127-129, 145-146: pulled forward by row 10A ----
	{
		id: 98,
		highLevelRows: rows("08", "10A"),
		implementationStages: stages("T1", "T7", "T8", "T12"),
		closure: "contract_sealed",
		ownerModule: "packages/agent/src/harness/foundation/identity.ts",
		publicContract: "TaskEnvelopeV1 with goal, acceptance criteria, workspace, capability, budget and I/O; Task and Role responsibilities separated; Spawn creates an independent AgentInstance",
		persistence: "Task records persisted before any Binding resolution",
		tests: ["packages/agent/test/harness/foundation-contracts.test.ts", "packages/agent/test/harness/recovery-conformance.test.ts", "packages/agent/test/harness/foundation-provider-conformance.test.ts"],
		laterConsumer: "12A",
		laterCapabilityIds: [90, 95, 102, 114, 117],
	},
	{
		id: 127,
		highLevelRows: rows("08", "10A"),
		implementationStages: stages("T2", "T7", "T11", "T12"),
		closure: "implemented",
		ownerModule: "packages/agent/src/harness/foundation/workflow.ts",
		publicContract: "Versioned Workflow DSL with a migration registry",
		persistence: "Workflow DSL version records with forward-only migration",
		tests: ["packages/agent/test/harness/foundation-t7-workflow-store.test.ts"],
		laterConsumer: "12B",
		laterCapabilityIds: [130, 131],
	},
	{
		id: 128,
		highLevelRows: rows("08", "10A"),
		implementationStages: stages("T2", "T7", "T11", "T12"),
		closure: "implemented",
		ownerModule: "packages/agent/src/harness/foundation/workflow.ts",
		publicContract: "Unified Agent/Tool/Parallel/Gate/AwaitUser/Barrier/Acceptance Step types with input/output contracts",
		persistence: "Step state records pending/ready/running/waiting_user/awaiting_dispatch/blocked/succeeded/failed/cancelled/skipped",
		tests: ["packages/agent/test/harness/foundation-t7-workflow-store.test.ts"],
		laterConsumer: "15",
		laterCapabilityIds: [147],
	},
	{
		id: 129,
		highLevelRows: rows("08", "10A"),
		implementationStages: stages("T2", "T7", "T11", "T12"),
		closure: "implemented",
		ownerModule: "packages/agent/src/harness/foundation/workflow-store.ts",
		publicContract: "Durable pause/resume/stop/barrier/budget; cross-session steps stop at awaiting_dispatch without pretending to run",
		persistence: "Workflow terminal facts; recovery never restarts paused/stopped objects",
		tests: ["packages/agent/test/harness/foundation-t7-workflow-store.test.ts"],
		laterConsumer: "12B",
		laterCapabilityIds: [120, 123, 131],
	},
	{
		id: 145,
		highLevelRows: rows("10A"),
		implementationStages: stages("T2", "T7", "T8", "T9", "T10", "T12"),
		closure: "contract_sealed",
		ownerModule: "packages/coding-agent/src/core/sdk.ts",
		publicContract: "SDK/RPC intent operations for Gate/Cancel/Retry/Resume/Reassign on the frozen operation surface",
		persistence: "Intent command records over the shared RuntimeSession",
		tests: ["packages/coding-agent/test/sdk-session-manager.test.ts", "packages/coding-agent/test/rpc-client-replay-recovery.test.ts", "packages/coding-agent/test/public-api-contract.test.ts"],
		laterConsumer: "15",
		laterCapabilityIds: [147],
	},
	{
		id: 146,
		highLevelRows: rows("10A"),
		implementationStages: stages("T1", "T2", "T7", "T8", "T9", "T10", "T12"),
		closure: "contract_sealed",
		ownerModule: "packages/agent/src/harness/foundation/results.ts",
		publicContract: "TaskResultV1 with summary/Diff/Artifact/Test/evidence/error/provenance/validation referencing source AttemptReceipts; RunReceiptV1 expresses the Host terminal state separately",
		persistence: "TaskResult settlement and RunReceipt records with Host-exclusive terminal gate",
		tests: ["packages/agent/test/harness/foundation-contracts.test.ts", "packages/coding-agent/test/public-api-contract.test.ts"],
		laterConsumer: "15",
		laterCapabilityIds: [141, 148],
	},
] as const satisfies readonly FoundationCapabilityClosureV1[];

const futureOwners = [
	// ---- 74-89: Operation Worker (line 11) with ops on line 14 ----
	{
		id: 74,
		laterOwner: "11",
		title: "Sandbox Provider",
		description: "Production SandboxProvider backend with unified network, MCP and credential capability declarations.",
		consumedFoundationContracts: ["SandboxOperationProvider contract", "CapabilitySelectorV1", "CredentialTarget contract"],
	},
	{
		id: 75,
		laterOwner: "11",
		title: "remote.operation",
		description: "Independent-process and remote execution implementation of the existing transport-neutral remote.operation contract.",
		consumedFoundationContracts: ["SandboxOperationProvider contract", "transport contract (stdio/TCP/WebSocket)", "WorkerReceiptRefV1"],
	},
	{
		id: 76,
		laterOwner: "11",
		title: "Gondolin Local Sandbox Provider",
		description: "Local VM sandbox provider completing network, MCP and credential delivery.",
		consumedFoundationContracts: ["SandboxOperationProvider contract", "Policy/Sandbox inheritance & Managed Lock", "CredentialTarget contract"],
	},
	{
		id: 77,
		laterOwner: "11",
		title: "Sandbox Operation Worker",
		description: "Real independent subprocess executing a bounded Host-authorized sandbox operation and returning a WorkerReceipt.",
		consumedFoundationContracts: ["SandboxOperationProvider contract", "WorkerReceiptRefV1", "run cancel/deadline propagation", "ExecutionCorrelationV1"],
	},
	{
		id: 78,
		laterOwner: "11",
		title: "Worker Supervisor 与私有 RPC",
		description: "Supervisor responsible for worker startup, monitoring, restart, private RPC, cancellation and reclamation.",
		consumedFoundationContracts: ["SandboxOperationProvider contract", "transport contract (stdio/TCP/WebSocket)", "observer/cursor continuity contract"],
	},
	{
		id: 79,
		laterOwner: "11",
		title: "Operation Worker Profile",
		description: "Operation Worker profile schema, version and request fingerprint.",
		consumedFoundationContracts: ["ModelProfileV1", "fingerprint/idempotency contract"],
	},
	{
		id: 80,
		laterOwner: "11",
		title: "两阶段 Preflight/Activate",
		description: "Two-phase activation of side-effect resources once the Host has accepted the Run.",
		consumedFoundationContracts: ["Run lifecycle/terminal gate contract", "SandboxOperationProvider contract", "TaskEnvelopeV1"],
	},
	{
		id: 81,
		laterOwner: "11",
		title: "Operation Worker 身份、版本和打包",
		description: "Complete worker envelope, Node/Bun launcher and distribution packaging.",
		consumedFoundationContracts: ["ExecutionCorrelationV1/lineage", "protocol versioning/feature negotiation"],
	},
	{
		id: 82,
		laterOwner: "11",
		title: "Readiness、Heartbeat、Liveness",
		description: "Worker readiness, heartbeat, health, lease and lost-worker detection.",
		consumedFoundationContracts: ["writer lease/fencing contract", "run deadline propagation", "CredentialTarget contract"],
	},
	{
		id: 83,
		laterOwner: "11",
		title: "Cancel 与 Finalize",
		description: "Host-to-worker finalize and deterministic cancellation outcome.",
		consumedFoundationContracts: ["run cancel/deadline propagation", "side-effect-unknown semantics", "WorkerReceiptRefV1"],
	},
	{
		id: 84,
		laterOwner: "11",
		title: "Operation、Reclaim、WorkerReceipt",
		description: "WorkerReceipt expresses only a bounded operation and never settles Attempt, Task or Run.",
		consumedFoundationContracts: ["WorkerReceiptRefV1", "AttemptReceiptV1/TaskResultV1/RunReceiptV1 layering"],
	},
	{
		id: 85,
		laterOwner: "11",
		title: "Operation Worker Credential Delivery",
		description: "Production issuer, target, projection, receipt and revocation for worker credentials.",
		consumedFoundationContracts: ["CredentialTarget contract", "scoped ModelGateway contract", "redacted public projection contract"],
	},
	{
		id: 86,
		laterOwner: "11",
		title: "Operation Fencing 与 Reclaim",
		description: "lost / reclaim / reclaim_unknown states and orphan cleanup for worker operations.",
		consumedFoundationContracts: ["writer lease/fencing contract", "single-writer/fencing contract", "side-effect-unknown semantics"],
	},
	{
		id: 87,
		laterOwner: "11",
		title: "Partial Operation Result",
		description: "Streaming intermediate results, resume points and safe return to the Host.",
		consumedFoundationContracts: ["durable/live/derived event taxonomy", "WorkerReceiptRefV1"],
	},
	{
		id: 88,
		laterOwner: "14",
		title: "远程 Operation Worker 与跨主机安全",
		description: "Remote sandbox execution with authentication, TLS and network policy.",
		consumedFoundationContracts: ["transport contract (auth/TLS/address policy)", "session writer lease/fencing contract"],
	},
	{
		id: 89,
		laterOwner: "14",
		title: "Operation Worker Fleet 与运维状态",
		description: "starting / ready / running / lost / release fleet states and operational metrics.",
		consumedFoundationContracts: ["RuntimeService DAG/lifecycle contract", "typed event catalog", "observer/cursor continuity contract"],
	},

	// ---- 90-118: Native Subagent (line 12A) ----
	{
		id: 90,
		laterOwner: "12A",
		title: "原生 Child Agent Runtime",
		description: "Main-line ModelRuntime, Context and Agent Loop child instances.",
		consumedFoundationContracts: ["AgentHarness loop contract", "ContextSnapshotV1/fork modes", "ChildAgentProvider contract"],
	},
	{
		id: 91,
		laterOwner: "12A",
		title: "Agent Definition",
		description: "Reuses Foundation RoleDefinition/RoleRevision; adds child effort, tier, memory, MCP, isolation and I/O projection.",
		consumedFoundationContracts: ["RoleDefinitionV1/RoleRevisionV1", "ModelProfileV1", "AgentBindingV1/BindingEpochV1"],
	},
	{
		id: 92,
		laterOwner: "12A",
		title: "自动选择与显式调用",
		description: "Description-based auto-selection, explicit @agent invocation and run-as-main.",
		consumedFoundationContracts: ["Capability descriptor/registry", "RoleDefinitionV1 capabilitySelector"],
	},
	{
		id: 93,
		laterOwner: "12A",
		title: "Child Identity 与父子树",
		description: "Persistent child ids, parent, ancestor and depth in the lineage tree.",
		consumedFoundationContracts: ["ExecutionCorrelationV1/lineage", "AgentInstanceV1 (Agent-class providers only)"],
	},
	{
		id: 94,
		laterOwner: "12A",
		title: "Child Transcript 与 Resume",
		description: "Child transcript persistence and continue/resume by id.",
		consumedFoundationContracts: ["canonical Session ledger", "resume boundary/recovery contract", "AgentHarness operation driver"],
	},
	{
		id: 95,
		laterOwner: "12A",
		title: "Context Fork 模式",
		description: "Context fork modes none / all / recent-N / structured task package.",
		consumedFoundationContracts: ["ContextSnapshotV1/fork modes", "TaskEnvelopeV1", "compaction version/resume boundary"],
	},
	{
		id: 96,
		laterOwner: "12A",
		title: "资源继承矩阵",
		description: "Projects instructions, skills, MCP, model, sandbox and Git from the parent AgentBinding to children; only tightens.",
		consumedFoundationContracts: ["AgentBindingV1/BindingEpochV1", "MCP selector (all/none/named/except)", "Policy/Sandbox inheritance & Managed Lock"],
	},
	{
		id: 97,
		laterOwner: "12A",
		title: "独立 Child Memory",
		description: "Independent child memory directory, scope, inheritance and cleanup.",
		consumedFoundationContracts: ["Memory scope/provenance contract", "ContextSnapshotV1"],
	},
	{
		id: 99,
		laterOwner: "12A",
		title: "输入输出 Artifact 合同",
		description: "AttemptReceipt/TaskResult inputs, outputs, paths, digest and validation state.",
		consumedFoundationContracts: ["AttemptReceiptV1", "TaskResultV1", "ArtifactRefV1/local content-addressed store"],
	},
	{
		id: 100,
		laterOwner: "12A",
		title: "安全结果合同",
		description: "AttemptReceipt records one attempt; TaskResult unifies summary, artifacts, diff, tests, evidence, error, provenance, validation; RunReceipt expresses the Host terminal state.",
		consumedFoundationContracts: ["AttemptReceiptV1", "TaskResultV1", "RunReceiptV1"],
	},
	{
		id: 101,
		laterOwner: "12A",
		title: "结果防注入",
		description: "Validates and trims child output before it enters the parent context, with untrusted provenance marking.",
		consumedFoundationContracts: ["TaskResultV1 provenance", "ArtifactRefV1 validation", "redacted public projection contract"],
	},
	{
		id: 102,
		laterOwner: "12A",
		title: "Spawn",
		description: "Native spawn creates a new Task, Context and Dispatch; an Agent-class provider creates or binds the AgentInstance.",
		consumedFoundationContracts: ["TaskEnvelopeV1", "Dispatch/TaskExecutorProvider contract", "AgentInstanceV1 (Agent-class providers only)", "role.switch vs agent.spawn separation"],
	},
	{
		id: 103,
		laterOwner: "12A",
		title: "Send 与 Mailbox",
		description: "send_input, SendMessage, Mailbox and Ack for persistent child communication.",
		consumedFoundationContracts: ["Turn/Step/Inbox contract", "durable Ask/Reply contract"],
	},
	{
		id: 104,
		laterOwner: "12A",
		title: "Wait 与 Query",
		description: "wait_any, wait_all, query and timeout over child execution.",
		consumedFoundationContracts: ["TaskResultV1 settlement", "TaskExecutorProvider/Dispatch/Attempt contract"],
	},
	{
		id: 105,
		laterOwner: "12A",
		title: "Cancel、Kill、Close",
		description: "Child lifecycle states with graceful shutdown and forced reclamation.",
		consumedFoundationContracts: ["run cancel/deadline propagation", "side-effect-unknown semantics"],
	},
	{
		id: 106,
		laterOwner: "12A",
		title: "前台与后台运行",
		description: "Resumable background identity, notifications and re-attach.",
		consumedFoundationContracts: ["observer attach/cursor/gap contract", "RunReceiptV1 terminal gate"],
	},
	{
		id: 107,
		laterOwner: "12A",
		title: "并发、深度、Max Turns",
		description: "Native concurrency, depth and max-turns limits with queue-or-fail.",
		consumedFoundationContracts: ["budget/concurrency quota contract", "TaskEnvelopeV1"],
	},
	{
		id: 108,
		laterOwner: "12A",
		title: "Worktree 隔离与 Apply",
		description: "Child worktree create, apply, cleanup and fail-closed semantics.",
		consumedFoundationContracts: ["ContextSnapshotV1", "Policy/Sandbox inheritance & Managed Lock", "CheckpointV1/rewind impact plan"],
	},
	{
		id: 109,
		laterOwner: "12A",
		title: "Policy、Gate、Budget 继承",
		description: "Forces the parent Binding's Policy, Gate and Budget onto all descendants; role patches cannot loosen them.",
		consumedFoundationContracts: ["AgentBindingV1/BindingEpochV1", "Policy/Sandbox inheritance & Managed Lock", "budget/concurrency quota contract"],
	},
	{
		id: 110,
		laterOwner: "12A",
		title: "Per-child Model、Effort、Tier",
		description: "Child Role references a ModelProfile and freezes effort, tier, fallback, budget and source.",
		consumedFoundationContracts: ["RoleDefinitionV1/RoleRevisionV1", "ModelProfileV1", "AgentBindingV1 fingerprint"],
	},
	{
		id: 111,
		laterOwner: "12A",
		title: "Subagent Provider Registry",
		description: "In-process, fork, Agent Runtime Host, ACP, Codex, Claude and SDK subagent providers.",
		consumedFoundationContracts: ["TaskExecutorProvider/Dispatch/Attempt contract", "Capability descriptor/registry"],
	},
	{
		id: 112,
		laterOwner: "12A",
		title: "Provider Capability Negotiation",
		description: "Child lifecycle, resume and tool capability negotiation.",
		consumedFoundationContracts: ["TaskExecutorProvider contract", "protocol versioning/feature negotiation"],
	},
	{
		id: 113,
		laterOwner: "12A",
		title: "Continuation Manager",
		description: "Persists provider handles and resumes internal and external agents.",
		consumedFoundationContracts: ["ChildAgentProvider contract", "resume boundary/recovery contract"],
	},
	{
		id: 114,
		laterOwner: "12A",
		title: "内外部 Task Executor 统一池",
		description: "Unified capability description, Dispatch, Attempt and AttemptReceipt via TaskExecutorProvider; AgentInstance exists only on Agent-class providers.",
		consumedFoundationContracts: ["TaskExecutorProvider/Dispatch/Attempt contract", "AttemptReceiptV1", "AgentInstanceV1 (Agent-class providers only)"],
	},
	{
		id: 115,
		laterOwner: "12A",
		title: "Sibling Roster",
		description: "Team member state, capability, task and message address queries.",
		consumedFoundationContracts: ["ExecutionCorrelationV1/lineage", "typed event catalog"],
	},
	{
		id: 116,
		laterOwner: "12A",
		title: "Nested Spawn Reparent",
		description: "Depth policy, flat reparenting and ancestor constraints.",
		consumedFoundationContracts: ["ExecutionCorrelationV1/lineage", "AgentInstanceV1 (Agent-class providers only)"],
	},
	{
		id: 117,
		laterOwner: "12A",
		title: "Multi-attempt 与结果比较",
		description: "Compares multiple AttemptReceipts for one Task, selects and settles into a TaskResult.",
		consumedFoundationContracts: ["AttemptReceiptV1", "TaskResultV1 settlement", "task graph Task-node contract"],
	},
	{
		id: 118,
		laterOwner: "12A",
		title: "Chain、Parallel、Synthesis、Quorum",
		description: "Native multi-AgentInstance join, partial failure, synthesis, quorum and consensus.",
		consumedFoundationContracts: ["AttemptReceiptV1/TaskResultV1", "budget/concurrency quota contract"],
	},

	// ---- 119-126, 130-131: Coordinator / Workflow scheduler and handoff (line 12B) ----
	{
		id: 119,
		laterOwner: "12B",
		title: "Durable Task DAG",
		description: "Task node execution and dependency progression; Run, Dispatch and Attempt remain execution records.",
		consumedFoundationContracts: ["TaskEnvelopeV1", "task graph Task-node contract", "RunReceiptV1 terminal gate"],
	},
	{
		id: 120,
		laterOwner: "12B",
		title: "Queue、Claim、Ownership",
		description: "Durable queue, claim, lease, fencing and settlement for task execution.",
		consumedFoundationContracts: ["TaskExecutorProvider/Dispatch/Attempt contract", "writer lease/fencing contract"],
	},
	{
		id: 121,
		laterOwner: "12B",
		title: "自适应 Scheduler",
		description: "Scheduling by capability, trust, cost, latency, quality, load and affinity.",
		consumedFoundationContracts: ["Capability descriptor/registry", "budget/quota attribution contract", "TaskEnvelopeV1"],
	},
	{
		id: 122,
		laterOwner: "12B",
		title: "Fan-out、Fan-in、Join",
		description: "Native DAG fan-out/fan-in over Tasks and AttemptReceipts with partial failure and structured TaskResult synthesis.",
		consumedFoundationContracts: ["AttemptReceiptV1", "TaskResultV1", "ArtifactRefV1", "task graph Task-node contract"],
	},
	{
		id: 123,
		laterOwner: "12B",
		title: "跨 Session 编排",
		description: "Cross-session assignment, waiting, messaging and result reclamation.",
		consumedFoundationContracts: ["TaskResultV1/RunReceiptV1", "durable/live event correlation", "Session ledger continuity"],
	},
	{
		id: 124,
		laterOwner: "12B",
		title: "耐久协作消息协议",
		description: "Collaboration messages with type, thread, correlation, ack and replay.",
		consumedFoundationContracts: ["typed event catalog", "durable/live/derived event taxonomy", "RunReceiptV1"],
	},
	{
		id: 125,
		laterOwner: "12B",
		title: "Ask、Reply、Escalation",
		description: "Blocking ask/reply, escalation and explicit outcome settlement.",
		consumedFoundationContracts: ["AskV1 durable ask/reply", "TaskResultV1 validation", "RunReceiptV1 terminal gate"],
	},
	{
		id: 126,
		laterOwner: "12B",
		title: "Ownership Transfer",
		description: "Handoff with accept, reject, timeout and audit of task ownership.",
		consumedFoundationContracts: ["TaskEnvelopeV1", "RunReceiptV1", "writer lease/fencing contract", "audit/lineage accrual"],
	},
	{
		id: 130,
		laterOwner: "12B",
		title: "Cycle、Deadlock、Backpressure",
		description: "Cycle detection, deadlock detection, fairness and backpressure for workflows.",
		consumedFoundationContracts: ["Workflow DSL/Step types", "budget/concurrency quota contract"],
	},
	{
		id: 131,
		laterOwner: "12B",
		title: "Automation 与定时恢复",
		description: "Workflow timed wake-up, continuation and failure compensation.",
		consumedFoundationContracts: ["Workflow pause/resume/stop barrier", "TaskResultV1/RunReceiptV1"],
	},

	// ---- 132-144: execution security, integration and operations (lines 11/13/14) ----
	{
		id: 132,
		laterOwner: "13",
		title: "权限分类与 Capability Mode",
		description: "Mode persisted as a RoleRevision permission matrix (read, write, command, network, commit, push, merge); runtime only tightens.",
		consumedFoundationContracts: ["RoleDefinitionV1/RoleRevisionV1 permission matrix", "CapabilitySelectorV1", "AgentBindingV1/BindingEpochV1", "Policy/Sandbox inheritance & Managed Lock"],
	},
	{
		id: 133,
		laterOwner: "13",
		title: "Protected Paths 与 Reviewer",
		description: "Protected paths, reviewer and classifier with team-level enforced review.",
		consumedFoundationContracts: ["Policy/Sandbox inheritance & Managed Lock", "AgentBindingV1 source trace"],
	},
	{
		id: 134,
		laterOwner: "14",
		title: "Managed Requirements 与 Untrusted Project",
		description: "Organization locking and disabling hooks/rules for untrusted projects.",
		consumedFoundationContracts: ["Role resolver Managed Lock precedence", "Context instruction scope", "Policy/Sandbox inheritance & Managed Lock"],
	},
	{
		id: 135,
		laterOwner: "11",
		title: "Setup 与 Agent 两阶段安全",
		description: "Two-phase runner: setup online, agent offline, handover after removing secrets.",
		consumedFoundationContracts: ["SandboxOperationProvider contract", "CredentialTarget contract", "redacted public projection contract"],
	},
	{
		id: 136,
		laterOwner: "11",
		title: "Task Credential/Lease",
		description: "Wires the existing lease control plane into Operation Workers, external agents and production targets.",
		consumedFoundationContracts: ["CredentialTarget contract", "scoped ModelGateway contract", "TransportAdapter contract"],
	},
	{
		id: 137,
		laterOwner: "14",
		title: "Secret Projection 与 DLP",
		description: "Vault, short-lived projection, rotation, no-persistence and data-loss prevention.",
		consumedFoundationContracts: ["CredentialTarget contract", "redacted public projection contract"],
	},
	{
		id: 138,
		laterOwner: "13",
		title: "MCP 安全边界",
		description: "Role selector, child-agent inheritance approval and tool-level trimming for MCP.",
		consumedFoundationContracts: ["RoleDefinitionV1 capabilitySelector", "MCP selector (all/none/named/except)", "AgentBindingV1/BindingEpochV1", "ToolPipelineV1 guard"],
	},
	{
		id: 139,
		laterOwner: "14",
		title: "Audit 完整性与保留",
		description: "Layered result association, signing, tamper resistance, retention, export and deletion policies.",
		consumedFoundationContracts: ["AuditV1/ReplayV1/external.map", "AttemptReceiptV1/TaskResultV1/RunReceiptV1 association"],
	},
	{
		id: 140,
		laterOwner: "11",
		title: "Git、SSH、Handoff 等扩展",
		description: "Native governance, permission and unified receipts for Git/SSH/handoff extensions.",
		consumedFoundationContracts: ["ToolGateway contract", "ToolReceiptV1", "side-effect-unknown semantics"],
	},
	{
		id: 141,
		laterOwner: "14",
		title: "CI、PR、Cloud 交付",
		description: "Native PR/CI result objects, status tracking and claiming.",
		consumedFoundationContracts: ["TaskResultV1", "ArtifactRefV1 validation", "RunReceiptV1"],
	},
	{
		id: 142,
		laterOwner: "14",
		title: "Metrics、Tracing、SLO",
		description: "Metrics, traces, SLOs, indexing and centralized databases.",
		consumedFoundationContracts: ["typed event catalog", "telemetry schema contract"],
	},
	{
		id: 143,
		laterOwner: "14",
		title: "HA 与灾难恢复",
		description: "Leader election, backup, recovery and failover.",
		consumedFoundationContracts: ["Session ledger continuity", "writer lease/fencing contract", "replay cursor/gap contract"],
	},
	{
		id: 144,
		laterOwner: "14",
		title: "Task Graph 看板",
		description: "Operational dashboard for DAG, parent-child trees, Operation Workers, Child Agents and Attempt states.",
		consumedFoundationContracts: ["task graph Task-node contract", "typed event catalog", "AttemptReceiptV1"],
	},

	// ---- 147-150: integration and product delivery (lines 14/15) ----
	{
		id: 147,
		laterOwner: "15",
		title: "Role 与资源池配置面",
		description: "Role Studio persisting user Mode as RoleDefinition/RoleRevision with editors for ModelProfile, permission matrix, Rules/Skills/MCP, scope, import/export and resolved Binding preview.",
		consumedFoundationContracts: ["Role Registry CRUD API (C066)", "RoleRevisionV1 import/export", "ModelProfileV1", "AgentBindingV1 resolved preview"],
	},
	{
		id: 148,
		laterOwner: "15",
		title: "Usage、Cost、Audit 面板",
		description: "Usage, cost and audit panels aggregated by team, task, user and model.",
		consumedFoundationContracts: ["budget/quota attribution contract", "AuditV1/ReplayV1", "typed event catalog"],
	},
	{
		id: 149,
		laterOwner: "14",
		title: "数据保留与删除",
		description: "Retention periods for transcripts, artifacts, audit and memory.",
		consumedFoundationContracts: ["ArtifactStore retention contract", "Session ledger retention/tombstone", "AuditV1 retention/export"],
	},
	{
		id: 150,
		laterOwner: "14",
		title: "RPC Schema 与文档一致性",
		description: "Fixes schema/doc drift such as the sessionFile return-field difference in RPC documentation.",
		consumedFoundationContracts: ["protocol versioning/feature negotiation", "FoundationEnvelopeV1 command/event envelope"],
	},
] as const satisfies readonly FoundationFutureCapabilityOwnerV1[];

const foundationCapabilityClosures = closures.map((entry) => ({
	...entry,
	ownerModule: entry.ownerModule,
	tests: [...entry.tests],
})) satisfies readonly FoundationCapabilityClosureV1[];

/** All 79 closure entries (ids `1..73`, `98`, `127`, `128`, `129`, `145`, `146`). */
export const FOUNDATION_V1_CAPABILITY_CLOSURES: readonly FoundationCapabilityClosureV1[] = foundationCapabilityClosures;

/** All 71 future owner entries (ids `74..97`, `99..126`, `130..144`, `147..150`). */
export const FOUNDATION_V1_FUTURE_CAPABILITY_OWNERS: readonly FoundationFutureCapabilityOwnerV1[] = futureOwners;

/** Closure ids as a set for machine checks. */
export const FOUNDATION_V1_CLOSURE_IDS: ReadonlySet<number> = new Set(FOUNDATION_V1_CAPABILITY_CLOSURES.map((entry) => entry.id));

/** Future owner ids as a set for machine checks. */
export const FOUNDATION_V1_FUTURE_IDS: ReadonlySet<number> = new Set(FOUNDATION_V1_FUTURE_CAPABILITY_OWNERS.map((entry) => entry.id));

/** Look up a closure entry by capability id. */
export function foundationClosureById(id: number): FoundationCapabilityClosureV1 | undefined {
	return FOUNDATION_V1_CAPABILITY_CLOSURES.find((entry) => entry.id === id);
}

/** Look up a future owner entry by capability id. */
export function foundationFutureOwnerById(id: number): FoundationFutureCapabilityOwnerV1 | undefined {
	return FOUNDATION_V1_FUTURE_CAPABILITY_OWNERS.find((entry) => entry.id === id);
}
