/**
 * Core modules shared between all run modes.
 */

export {
	AgentSession,
	type AgentSessionConfig,
	type AgentSessionEvent,
	type AgentSessionEventListener,
	type ModelCycleResult,
	type PromptOptions,
	type SessionStats,
} from "./agent-session.ts";
export {
	createAgentRuntimeCompositionFactory,
	createWorkerSandboxComposition,
	type AgentRuntimeComposition,
	type AgentRuntimeCompositionContext,
	type AgentRuntimeCompositionFactory,
	type AgentRuntimeCompositionOptions,
	type ExternalConnectorProductAuthority,
	type ExternalConnectorRegistryFactory,
	type SchedulerCompositionFactory,
	type SchedulerRuntimeOptions,
	type SubagentCompositionFactory,
	type TaskCredentialProviderFactory,
	type ToolGatewayCatalog,
	type ToolGatewayCatalogFactory,
	type ToolGatewayFactory,
	type WorkerSandboxComposition,
	type WorkerSandboxFactory,
	type WorkerSandboxCompositionOptions,
} from "./agent-runtime-composition.ts";
export {
	EXTERNAL_CONNECTOR_TARGET_CONFIG_SCHEMA_VERSION,
	ExternalConnectorTargetConfigError,
	buildExternalConnectorTargetConfig,
	resolveExternalConnectorTargetConfig,
	type ExternalConnectorAccountReference,
	type ExternalConnectorCapabilityCeiling,
	type ExternalConnectorCapabilityNarrowing,
	type ExternalConnectorModelAccess,
	type ExternalConnectorResolvedTarget,
	type ExternalConnectorTargetAuthority,
	type ExternalConnectorTargetCatalogConfig,
	type ExternalConnectorTargetConfig,
	type ExternalConnectorTargetConfigBuildOptions,
	type ExternalConnectorTargetConfigErrorReason,
	type ExternalConnectorTargetDefinition,
	type ExternalConnectorTargetSelectionConfig,
	type ExternalConnectorTargetSelectionSource,
	type ExternalConnectorTrustedTarget,
} from "./external-connector-target-config.ts";
export {
	AgentSessionRuntime,
	type CreateAgentSessionRuntimeFactory,
	type CreateAgentSessionRuntimeResult,
	createAgentSessionRuntime,
} from "./agent-session-runtime.ts";
export {
	RUNTIME_SESSION_SURFACES,
	createRuntimeSessionSurfaceAdapter,
	isRuntimeSessionSurface,
	type RuntimeSessionSurfaceAdapter,
	type RuntimeSessionSurface,
} from "./runtime-session-surface.ts";
export {
	type AgentSessionRuntimeDiagnostic,
	type AgentSessionServices,
	type CreateAgentSessionFromServicesOptions,
	type CreateAgentSessionServicesOptions,
	createAgentSessionFromServices,
	createAgentSessionServices,
} from "./agent-session-services.ts";
export { type BashExecutorOptions, type BashResult, executeBashWithOperations } from "./bash-executor.ts";
export {
	classifyExternalToolPolicyOperation,
	type ExternalToolPolicyOperationInput,
} from "./external-tool-policy-operation.ts";
export type { CompactionResult } from "./compaction/index.ts";
export { createEventBus, type EventBus, type EventBusController } from "./event-bus.ts";
export {
	EXECUTION_ASSOCIATION_CUSTOM_TYPE,
	EXECUTION_ASSOCIATION_SCHEMA_VERSION,
	type ExecutionAssociationRecord,
	type ExecutionAssociationSession,
	getExecutionAssociations,
	isExecutionAssociationRecord,
	parseExecutionAssociation,
} from "./execution-association.ts";
export {
	classifyAssistantFailure,
	classifyProviderFailure,
	type ExecutionErrorClassification,
	type ExecutionErrorKind,
	type ProviderFailureClassificationOptions,
} from "./execution-error.ts";
export {
	type ExecutionPolicyProfile,
	calculatePolicyReviewScopeDigest,
	classifyProtectedPathOperation,
	createPolicyReviewEvidence,
	isCanonicalReviewScopeDigest,
	isCanonicalWorkspaceRelativePath,
	isPolicyEffect,
	isPolicyReviewEvidence,
	isPolicyReviewRequirement,
	type PolicyApprovalOutcome,
	type PolicyApprovalRequest,
	type PolicyApprovalSource,
	type PolicyBinding,
	type PolicyDecision,
	PolicyError,
	POLICY_EFFECTS,
	POLICY_REVIEWER_KINDS,
	POLICY_REVIEW_REQUIREMENTS,
	type PolicyErrorCode,
	type PolicyEffect,
	type PolicyReviewDecision,
	type PolicyReviewEvidence,
	type PolicyReviewEvidenceResolution,
	type PolicyReviewerIdentity,
	type PolicyReviewerKind,
	type PolicyReviewRequirement,
	type ProtectedPathClassification,
	type ProtectedPathPolicy,
	type ProtectedPathRule,
	type PublicPolicySummary,
	resolveExecutionPolicy,
	resolveExecutionPolicyProfile,
	resolvePolicyReviewEvidence,
	resolveTaskCredentialPreflight,
	TASK_CREDENTIAL_POLICY_RESOURCES,
	TASK_CREDENTIAL_PREFLIGHT_OPERATIONS,
	type TaskCredentialGatePreflight,
	type TaskCredentialPolicyResource,
	type TaskCredentialPreflightInput,
	type TaskCredentialPreflightOperation,
	type TaskCredentialPreflightResult,
	type TaskCredentialProviderPreflight,
	type TaskCredentialSandboxPreflight,
	taskCredentialPolicyResource,
	isTaskCredentialPolicyResource,
} from "./execution-policy.ts";
export type { PolicyApprovalLedgerRecord, PolicyApprovalLedgerResolution } from "./execution-policy-ledger.ts";
export {
	REMOTE_ARTIFACT_KINDS,
	REMOTE_OPERATION_ERROR_CATEGORIES,
	REMOTE_OPERATION_CUSTOM_TYPE,
	REMOTE_OPERATION_LEDGER_SCHEMA_VERSION,
	REMOTE_OPERATION_SCHEMA_VERSION,
	REMOTE_OPERATION_SIDE_EFFECT_STATES,
	REMOTE_OPERATION_STATUSES,
	RemoteOperationError,
	createSessionRemoteOperationLedger,
	executeRemoteOperation,
	isRemoteOperationReceipt,
	isTaskLeaseReference,
	startRemoteOperation,
	toRemoteOperationErrorInfo,
	type ArtifactReference,
	type OperationId,
	type RemoteArtifactKind,
	type RemoteArtifactRef,
	type RemoteArtifactReference,
	type RemoteOperationBindingRefs,
	type RemoteOperationErrorCategory,
	type RemoteOperationErrorCode,
	type RemoteOperationErrorInfo,
	type RemoteOperationExecutionContext,
	type RemoteOperationHandle,
	type RemoteOperationHeartbeat,
	type RemoteOperationId,
	type RemoteOperationInvoker,
	type RemoteOperationLease,
	type RemoteOperationLeaseId,
	type RemoteOperationLedger,
	type RemoteOperationLedgerSession,
	type RemoteOperationProvider,
	type RemoteOperationReceipt,
	type RemoteOperationRequest,
	type RemoteOperationResult,
	type RemoteOperationRunStatus,
	type RemoteOperationSideEffectState,
	type RemoteOperationStartOptions,
	type RemoteOperationStatus,
	type RemoteOperationTerminalStatus,
	type RemoteOperationTransport,
	type RemoteOperationTaskLeaseVerifier,
	type TaskLeaseReference,
	type TaskLeaseVerificationResult,
} from "./remote-operation.ts";
// Task Credential / Lease core contract (safe public records only; no
// material-bearing types or handles are exported).
export {
	TASK_CREDENTIAL_ACTION,
	TASK_CREDENTIAL_DELIVERY_STATUS,
	TASK_CREDENTIAL_ERROR_CODES,
	TASK_CREDENTIAL_SCHEMA_VERSION,
	TASK_CREDENTIAL_STATUS,
	TaskCredentialError,
	type TaskCredentialAction,
	type TaskCredentialDeliveryReceipt,
	type TaskCredentialDeliveryStatus,
	type TaskCredentialErrorCode,
	type TaskCredentialErrorView,
	type TaskCredentialGrant,
	type TaskCredentialIssueRequest,
	type TaskCredentialScope,
	type TaskCredentialStatus,
	type TaskCredentialTransitionOptions,
	type TaskCredentialTtlBounds,
	type TaskExecutionBinding,
} from "./task-credential-lease.ts";
export {
	createTaskCredentialNullTarget,
	type TaskCredentialIssuer,
	type TaskCredentialProvider,
	type TaskCredentialProviderAvailability,
	type TaskCredentialProviderIssueRequest,
	type TaskCredentialProviderProjectRequest,
	type TaskCredentialProviderReceipt,
	type TaskCredentialProviderReceiptStatus,
	type TaskCredentialProviderRenewRequest,
	type TaskCredentialProviderRevokeRequest,
	type TaskCredentialTarget,
	type TaskCredentialTargetCapabilities,
	type TaskCredentialTargetCapabilitiesRequest,
	type TaskCredentialTargetRenewRequest,
	type TaskCredentialTargetRevokeRequest,
} from "./task-credential-provider.ts";
export {
	TASK_CREDENTIAL_CUSTOM_TYPE,
	createTaskCredentialStore,
	TaskCredentialStore,
	type TaskCredentialFoldResult,
	type TaskCredentialPersistedAction,
	type TaskCredentialSession,
	type TaskCredentialStoreIssueRequest,
	type TaskCredentialStoreOptions,
	type TaskCredentialStoreProjectRequest,
	type TaskCredentialStoreRenewRequest,
	type TaskCredentialStoreResult,
	type TaskCredentialStoreRevokeRequest,
	type TaskCredentialStoreSettleRequest,
	type TaskCredentialTransition,
	type TaskCredentialWarning,
	type TaskCredentialWarningCode,
} from "./task-credential-store.ts";
export { areExperimentalFeaturesEnabled } from "./experimental.ts";
// Extensions system
export {
	type AgentEndEvent,
	type AgentSettledEvent,
	type AgentStartEvent,
	type AgentToolResult,
	type AgentToolUpdateCallback,
	type BeforeAgentStartEvent,
	type BeforeAgentStartEventResult,
	type BuildSystemPromptOptions,
	type ContextEvent,
	defineTool,
	discoverAndLoadExtensions,
	type ExecOptions,
	type ExecResult,
	type Extension,
	type ExtensionAPI,
	type ExtensionCommandContext,
	type ExtensionContext,
	type ExtensionError,
	type ExtensionEvent,
	type ExtensionFactory,
	type ExtensionFlag,
	type ExtensionHandler,
	ExtensionRunner,
	type ExtensionShortcut,
	type ExtensionUIContext,
	type InlineExtension,
	type LoadExtensionsResult,
	type MessageRenderer,
	type RegisteredCommand,
	type SessionBeforeCompactEvent,
	type SessionBeforeForkEvent,
	type SessionBeforeSwitchEvent,
	type SessionBeforeTreeEvent,
	type SessionCompactEvent,
	type SessionShutdownEvent,
	type SessionStartEvent,
	type SessionTreeEvent,
	type ToolCallEvent,
	type ToolCallEventResult,
	type ToolDefinition,
	type ToolRenderResultOptions,
	type ToolResultEvent,
	type TurnEndEvent,
	type TurnStartEvent,
	type WorkingIndicatorOptions,
} from "./extensions/index.ts";
export {
	createOperationBoundary,
	type OperationBoundary,
	type OperationBoundaryOptions,
} from "./operation-boundary.ts";
export {
	createSessionBranchBoundary,
	createSessionCheckpoint,
	getSessionBoundaries,
	isSessionBoundaryRecord,
	recoverSessionCheckpoint,
	SESSION_BOUNDARY_CUSTOM_TYPE,
	SESSION_BOUNDARY_SCHEMA_VERSION,
	SessionBoundaryError,
	type SessionBoundaryKind,
	type SessionBoundaryRecord,
	type SessionBoundaryStatus,
} from "./session-boundary.ts";
export { createSyntheticSourceInfo } from "./source-info.ts";
export {
	PROMPT_TASK_DEPENDENCY_NAMES,
	PromptTaskCompositionError,
	createPromptTaskAdapter,
	type PromptTaskAdapter,
	type PromptTaskCompositionDependencies,
	type PromptTaskCompositionErrorCode,
	type PromptTaskCompositionRootOptions,
	type PromptTaskDependencyContext,
	type PromptTaskDependencyName,
	type PromptTaskDependencyResolution,
	type PromptTaskDependency,
	type PromptTaskEnvelopeInput,
	type PromptTaskExecution,
	type PromptTaskIdentity,
	type PromptTaskInput,
	type PromptTaskSettlement,
} from "./prompt-task-adapter.ts";
